using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace BarkAndBarker.Game.Items
{
    public static class Misc
    {
        public static readonly List<string> ItemIDs = new List<string>()
        {
            "Id_Item_ValentineCandies",
            "Id_Item_TrollBlood_5001",
            "Id_Item_SilverCoin",
            "Id_Item_SkullKey",
            "Id_Item_SoulHeart",
            "Id_Item_SoulTorq_3001",
            "Id_Item_SoulTorq_4001",
            "Id_Item_SoulTorq_5001",
            "Id_Item_SoulTorq_6001",
            "Id_Item_SoulTorq_7001",

            "Id_Item_BlueSapphire_1001",
            "Id_Item_BlueSapphire_2001",
            "Id_Item_BlueSapphire_3001",
            "Id_Item_BlueSapphire_4001",
            "Id_Item_BlueSapphire_5001",
            "Id_Item_BlueSapphire_6001",
            "Id_Item_BlueSapphire_7001",

            "Id_Item_RubysilverIngots_5001",
            "Id_Item_RubysilverOres_5001",
            "Id_Item_RubysilverPowder_5001",

            "Id_Item_GoldCoinBag",
            "Id_Item_GoldCoinChest",
            "Id_Item_GoldCoinPurse",
            "Id_Item_GoldCoins",

            "Id_Item_CoinPurse",

            "Id_Item_CandyCane",
            "Id_Item_CandyCorns",

            "Id_Item_CobaltIngots_4001",
            "Id_Item_CobaltOres_4001",
            "Id_Item_CobaltPowder_4001",

            "Id_Item_CeremonialDagger_1001",
            "Id_Item_CeremonialDagger_2001",
            "Id_Item_CeremonialDagger_3001",
            "Id_Item_CeremonialDagger_4001",
            "Id_Item_CeremonialDagger_5001",
            "Id_Item_CeremonialDagger_6001",
            "Id_Item_CeremonialDagger_7001",

            "Id_Item_Diamond_1001",
            "Id_Item_Diamond_2001",
            "Id_Item_Diamond_3001",
            "Id_Item_Diamond_4001",
            "Id_Item_Diamond_5001",
            "Id_Item_Diamond_6001",
            "Id_Item_Diamond_7001",

            "Id_Item_Emerald_1001",
            "Id_Item_Emerald_2001",
            "Id_Item_Emerald_3001",
            "Id_Item_Emerald_4001",
            "Id_Item_Emerald_5001",
            "Id_Item_Emerald_6001",
            "Id_Item_Emerald_7001",

            "Id_Item_GemNecklace_1001",
            "Id_Item_GemNecklace_2001",
            "Id_Item_GemNecklace_3001",
            "Id_Item_GemNecklace_4001",
            "Id_Item_GemNecklace_5001",
            "Id_Item_GemNecklace_6001",
            "Id_Item_GemNecklace_7001",

            "Id_Item_GemRing_1001",
            "Id_Item_GemRing_2001",
            "Id_Item_GemRing_3001",
            "Id_Item_GemRing_4001",
            "Id_Item_GemRing_5001",
            "Id_Item_GemRing_6001",
            "Id_Item_GemRing_7001",

            "Id_Item_GoldBand_1001",
            "Id_Item_GoldBand_2001",
            "Id_Item_GoldBand_3001",
            "Id_Item_GoldBand_4001",
            "Id_Item_GoldBand_5001",
            "Id_Item_GoldBand_6001",
            "Id_Item_GoldBand_7001",

            "Id_Item_GoldBangle1B_1001",
            "Id_Item_GoldBangle1B_2001",
            "Id_Item_GoldBangle1B_3001",
            "Id_Item_GoldBangle1B_4001",
            "Id_Item_GoldBangle1B_5001",
            "Id_Item_GoldBangle1B_6001",
            "Id_Item_GoldBangle1B_7001",

            "Id_Item_GoldBangle1C_1001",
            "Id_Item_GoldBangle1C_2001",
            "Id_Item_GoldBangle1C_3001",
            "Id_Item_GoldBangle1C_4001",
            "Id_Item_GoldBangle1C_5001",
            "Id_Item_GoldBangle1C_6001",
            "Id_Item_GoldBangle1C_7001",

            "Id_Item_GoldBangle1D_1001",
            "Id_Item_GoldBangle1D_2001",
            "Id_Item_GoldBangle1D_3001",
            "Id_Item_GoldBangle1D_4001",
            "Id_Item_GoldBangle1D_5001",
            "Id_Item_GoldBangle1D_6001",
            "Id_Item_GoldBangle1D_7001",

            "Id_Item_GoldBangle1E_1001",
            "Id_Item_GoldBangle1E_2001",
            "Id_Item_GoldBangle1E_3001",
            "Id_Item_GoldBangle1E_4001",
            "Id_Item_GoldBangle1E_5001",
            "Id_Item_GoldBangle1E_6001",
            "Id_Item_GoldBangle1E_7001",

            "Id_Item_GoldBangle1H_1001",
            "Id_Item_GoldBangle1H_2001",
            "Id_Item_GoldBangle1H_3001",
            "Id_Item_GoldBangle1H_4001",
            "Id_Item_GoldBangle1H_5001",
            "Id_Item_GoldBangle1H_6001",
            "Id_Item_GoldBangle1H_7001",

            "Id_Item_GoldBangle1I_1001",
            "Id_Item_GoldBangle1I_2001",
            "Id_Item_GoldBangle1I_3001",
            "Id_Item_GoldBangle1I_4001",
            "Id_Item_GoldBangle1I_5001",
            "Id_Item_GoldBangle1I_6001",
            "Id_Item_GoldBangle1I_7001",

            "Id_Item_GoldBangle1J_1001",
            "Id_Item_GoldBangle1J_2001",
            "Id_Item_GoldBangle1J_3001",
            "Id_Item_GoldBangle1J_4001",
            "Id_Item_GoldBangle1J_5001",
            "Id_Item_GoldBangle1J_6001",
            "Id_Item_GoldBangle1J_7001",

            "Id_Item_GoldBangle2D_1001",
            "Id_Item_GoldBangle2D_2001",
            "Id_Item_GoldBangle2D_3001",
            "Id_Item_GoldBangle2D_4001",
            "Id_Item_GoldBangle2D_5001",
            "Id_Item_GoldBangle2D_6001",
            "Id_Item_GoldBangle2D_7001",

            "Id_Item_GoldBangle2G_1001",
            "Id_Item_GoldBangle2G_2001",
            "Id_Item_GoldBangle2G_3001",
            "Id_Item_GoldBangle2G_4001",
            "Id_Item_GoldBangle2G_5001",
            "Id_Item_GoldBangle2G_6001",
            "Id_Item_GoldBangle2G_7001",

            "Id_Item_GoldBangle2H_1001",
            "Id_Item_GoldBangle2H_2001",
            "Id_Item_GoldBangle2H_3001",
            "Id_Item_GoldBangle2H_4001",
            "Id_Item_GoldBangle2H_5001",
            "Id_Item_GoldBangle2H_6001",
            "Id_Item_GoldBangle2H_7001",

            "Id_Item_GoldBowl_1001",
            "Id_Item_GoldBowl_2001",
            "Id_Item_GoldBowl_3001",
            "Id_Item_GoldBowl_4001",
            "Id_Item_GoldBowl_5001",
            "Id_Item_GoldBowl_6001",
            "Id_Item_GoldBowl_7001",

            "Id_Item_GoldCandelabra_1001",
            "Id_Item_GoldCandelabra_2001",
            "Id_Item_GoldCandelabra_3001",
            "Id_Item_GoldCandelabra_4001",
            "Id_Item_GoldCandelabra_5001",
            "Id_Item_GoldCandelabra_6001",
            "Id_Item_GoldCandelabra_7001",

            "Id_Item_GoldCandleHolder_1001",
            "Id_Item_GoldCandleHolder_2001",
            "Id_Item_GoldCandleHolder_3001",
            "Id_Item_GoldCandleHolder_4001",
            "Id_Item_GoldCandleHolder_5001",
            "Id_Item_GoldCandleHolder_6001",
            "Id_Item_GoldCandleHolder_7001",

            "Id_Item_GoldCandlePlatter_1001",
            "Id_Item_GoldCandlePlatter_2001",
            "Id_Item_GoldCandlePlatter_3001",
            "Id_Item_GoldCandlePlatter_4001",
            "Id_Item_GoldCandlePlatter_5001",
            "Id_Item_GoldCandlePlatter_6001",
            "Id_Item_GoldCandlePlatter_7001",

            "Id_Item_GoldChaliceA_1001",
            "Id_Item_GoldChaliceA_2001",
            "Id_Item_GoldChaliceA_3001",
            "Id_Item_GoldChaliceA_4001",
            "Id_Item_GoldChaliceA_5001",
            "Id_Item_GoldChaliceA_6001",
            "Id_Item_GoldChaliceA_7001",
            "Id_Item_GoldChaliceB_1001",
            "Id_Item_GoldChaliceB_2001",
            "Id_Item_GoldChaliceB_3001",
            "Id_Item_GoldChaliceB_4001",
            "Id_Item_GoldChaliceB_5001",
            "Id_Item_GoldChaliceB_6001",
            "Id_Item_GoldChaliceB_7001",

            "Id_Item_GoldCrown_1001",
            "Id_Item_GoldCrown_2001",
            "Id_Item_GoldCrown_3001",
            "Id_Item_GoldCrown_4001",
            "Id_Item_GoldCrown_5001",
            "Id_Item_GoldCrown_6001",
            "Id_Item_GoldCrown_7001",
            
            "Id_Item_GoldWaterpot_1001",
            "Id_Item_GoldWaterpot_2001",
            "Id_Item_GoldWaterpot_3001",
            "Id_Item_GoldWaterpot_4001",
            "Id_Item_GoldWaterpot_5001",
            "Id_Item_GoldWaterpot_6001",
            "Id_Item_GoldWaterpot_7001",

            "Id_Item_LargeScroll_1001",
            "Id_Item_LargeScroll_2001",
            "Id_Item_LargeScroll_3001",
            "Id_Item_LargeScroll_4001",
            "Id_Item_LargeScroll_5001",
            "Id_Item_LargeScroll_6001",
            "Id_Item_LargeScroll_7001",

            "Id_Item_MetalCup_1001",
            "Id_Item_MetalCup_2001",
            "Id_Item_MetalCup_3001",
            "Id_Item_MetalCup_4001",
            "Id_Item_MetalCup_5001",
            "Id_Item_MetalCup_6001",
            "Id_Item_MetalCup_7001",


            "Id_Item_PearlNecklace_1001",
            "Id_Item_PearlNecklace_2001",
            "Id_Item_PearlNecklace_3001",
            "Id_Item_PearlNecklace_4001",
            "Id_Item_PearlNecklace_5001",
            "Id_Item_PearlNecklace_6001",
            "Id_Item_PearlNecklace_7001",
            "Id_Item_PhoenixChoker_3001",
            "Id_Item_PhoenixChoker_4001",
            "Id_Item_PhoenixChoker_5001",
            "Id_Item_PhoenixChoker_6001",
            "Id_Item_PhoenixChoker_7001",

            "Id_Item_Ruby_1001",
            "Id_Item_Ruby_2001",
            "Id_Item_Ruby_3001",
            "Id_Item_Ruby_4001",
            "Id_Item_Ruby_5001",
            "Id_Item_Ruby_6001",
            "Id_Item_Ruby_7001",

            "Id_Item_SilverChalice_1001",
            "Id_Item_SilverChalice_2001",
            "Id_Item_SilverChalice_3001",
            "Id_Item_SilverChalice_4001",
            "Id_Item_SilverChalice_5001",
            "Id_Item_SilverChalice_6001",
            "Id_Item_SilverChalice_7001",

            "Id_Item_WindLocket_3001",
            "Id_Item_WindLocket_4001",
            "Id_Item_WindLocket_5001",
            "Id_Item_WindLocket_6001",
            "Id_Item_WindLocket_7001",
        };
    }
}
