// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: _PacketCommand.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DC.Packet
{

    /// <summary>Holder for reflection information generated from _PacketCommand.proto</summary>
    public static partial class PacketCommandReflection
    {

        #region Descriptor
        /// <summary>File descriptor for _PacketCommand.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static PacketCommandReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "ChRfUGFja2V0Q29tbWFuZC5wcm90bxIJREMuUGFja2V0IhAKDlNDMlNfQUxJ",
                  "VkVfUkVRIhAKDlNTMkNfQUxJVkVfUkVTIhQKElNDMlNfUkVDT05ORUNUX1JF",
                  "USIkChJTUzJDX1JFQ09OTkVDVF9SRVMSDgoGcmVzdWx0GAEgASgNIkEKHlNT",
                  "MkNfQ09OTkVDVF9TRVJWSUNFX0lORk9fSlNPThIRCglpcEFkZHJlc3MYASAB",
                  "KAkSDAoEcG9ydBgCIAEoDSqJSQoNUGFja2V0Q29tbWFuZBIPCgtQQUNLRVRf",
                  "Tk9ORRAAEhEKDUMyU19BTElWRV9SRVEQARIRCg1TMkNfQUxJVkVfUkVTEAIS",
                  "FQoRQzJTX1JFQ09OTkVDVF9SRVEQAxIVChFTMkNfUkVDT05ORUNUX1JFUxAE",
                  "EhkKFUMyU19BQ0NPVU5UX0xPR0lOX1JFURALEhkKFVMyQ19BQ0NPVU5UX0xP",
                  "R0lOX1JFUxAMEiQKIEMyU19BQ0NPVU5UX0NIQVJBQ1RFUl9DUkVBVEVfUkVR",
                  "EA8SJAogUzJDX0FDQ09VTlRfQ0hBUkFDVEVSX0NSRUFURV9SRVMQEBIiCh5D",
                  "MlNfQUNDT1VOVF9DSEFSQUNURVJfTElTVF9SRVEQERIiCh5TMkNfQUNDT1VO",
                  "VF9DSEFSQUNURVJfTElTVF9SRVMQEhIkCiBDMlNfQUNDT1VOVF9DSEFSQUNU",
                  "RVJfREVMRVRFX1JFURATEiQKIFMyQ19BQ0NPVU5UX0NIQVJBQ1RFUl9ERUxF",
                  "VEVfUkVTEBQSFwoTQzJTX0xPQkJZX0VOVEVSX1JFURAVEhcKE1MyQ19MT0JC",
                  "WV9FTlRFUl9SRVMQFhIgChxDMlNfQUNDT1VOVF9BR1JFRV9BTlNXRVJfUkVR",
                  "EBcSIAocUzJDX0FDQ09VTlRfQUdSRUVfQU5TV0VSX1JFUxAYEiIKHkMyU19D",
                  "SEFSQUNURVJfU0VMRUNUX0VOVEVSX1JFURApEiIKHlMyQ19DSEFSQUNURVJf",
                  "U0VMRUNUX0VOVEVSX1JFUxAqEiAKHEMyU19MT0JCWV9DSEFSQUNURVJfSU5G",
                  "T19SRVEQKxIgChxTMkNfTE9CQllfQ0hBUkFDVEVSX0lORk9fUkVTECwSGgoW",
                  "QzJTX09QRU5fTE9CQllfTUFQX1JFURAtEhoKFlMyQ19PUEVOX0xPQkJZX01B",
                  "UF9SRVMQLhIfChtDMlNfTE9CQllfUkVHSU9OX1NFTEVDVF9SRVEQLxIfChtT",
                  "MkNfTE9CQllfUkVHSU9OX1NFTEVDVF9SRVMQMBIhCh1DMlNfTE9CQllfRU5U",
                  "RVJfRlJPTV9HQU1FX1JFURAxEiEKHVMyQ19MT0JCWV9FTlRFUl9GUk9NX0dB",
                  "TUVfUkVTEDISKAokQzJTX0xPQkJZX0dBTUVfRElGRklDVUxUWV9TRUxFQ1Rf",
                  "UkVREDMSKAokUzJDX0xPQkJZX0dBTUVfRElGRklDVUxUWV9TRUxFQ1RfUkVT",
                  "EDQSJwojUzJDX0xPQkJZX0FDQ09VTlRfQ1VSUkVOQ1lfTElTVF9OT1QQNRIi",
                  "Ch5TMkNfTE9CQllfQ0hBUkFDVEVSX0FDVElPTl9OT1QQNhIkCiBTMkNfTE9C",
                  "QllfUkVQT1JUX1BVTklTSF9MSVNUX05PVBA3EhkKFE1JTl9JTlZFTlRPUllf",
                  "UEFDS0VUEPQDEhsKFkMyU19JTlZFTlRPUllfSU5GT19SRVEQ9QMSGwoWUzJD",
                  "X0lOVkVOVE9SWV9JTkZPX1JFUxD2AxIhChxDMlNfSU5WRU5UT1JZX0FMTF9V",
                  "UERBVEVfUkVREPcDEiEKHFMyQ19JTlZFTlRPUllfQUxMX1VQREFURV9SRVMQ",
                  "+AMSJAofQzJTX0lOVkVOVE9SWV9TSU5HTEVfVVBEQVRFX1JFURD5AxIkCh9T",
                  "MkNfSU5WRU5UT1JZX1NJTkdMRV9VUERBVEVfUkVTEPoDEhsKFkMyU19JTlZF",
                  "TlRPUllfTU9WRV9SRVEQ+wMSGwoWUzJDX0lOVkVOVE9SWV9NT1ZFX1JFUxD8",
                  "AxIcChdDMlNfSU5WRU5UT1JZX01FUkdFX1JFURD9AxIcChdTMkNfSU5WRU5U",
                  "T1JZX01FUkdFX1JFUxD+AxIbChZDMlNfSU5WRU5UT1JZX1NXQVBfUkVREP8D",
                  "EhsKFlMyQ19JTlZFTlRPUllfU1dBUF9SRVMQgAQSIQocQzJTX0lOVkVOVE9S",
                  "WV9TUExJVF9NT1ZFX1JFURCBBBIhChxTMkNfSU5WRU5UT1JZX1NQTElUX01P",
                  "VkVfUkVTEIIEEiIKHUMyU19JTlZFTlRPUllfU1BMSVRfTUVSR0VfUkVREIME",
                  "EiIKHVMyQ19JTlZFTlRPUllfU1BMSVRfTUVSR0VfUkVTEIQEEiEKHEMyU19J",
                  "TlZFTlRPUllfU1BMSVRfU1dBUF9SRVEQhQQSIQocUzJDX0lOVkVOVE9SWV9T",
                  "UExJVF9TV0FQX1JFUxCGBBItCihDMlNfSU5WRU5UT1JZX1RXT19IQU5ERURf",
                  "V0VBUE9OX1NXQVBfUkVREIcEEi0KKFMyQ19JTlZFTlRPUllfVFdPX0hBTkRF",
                  "RF9XRUFQT05fU1dBUF9SRVMQiAQSGQoUQzJTX1NUT1JBR0VfSU5GT19SRVEQ",
                  "pwQSGQoUUzJDX1NUT1JBR0VfSU5GT19SRVMQqAQSGQoUTUFYX0lOVkVOVE9S",
                  "WV9QQUNLRVQQ2AQSGwoWQzJTX0FVVE9fTUFUQ0hfUkVHX1JFURDvBRIbChZT",
                  "MkNfQVVUT19NQVRDSF9SRUdfUkVTEPAFEh4KGVMyQ19FTlRFUl9HQU1FX1NF",
                  "UlZFUl9OT1QQ8QUSIAobQzJTX0dBTUVfRU5URVJfQ09NUExFVEVfTk9UEPIF",
                  "EiAKG1MyQ19BVVRPX01BVENIX1JFR19URUFNX05PVBDzBRIdChhDMlNfUkVD",
                  "T05ORUNUX0lOR0FNRV9SRVEQ9AUSHQoYUzJDX1JFQ09OTkVDVF9JTkdBTUVf",
                  "UkVTEPUFEhcKEk1JTl9SQU5LSU5HX1BBQ0tFVBCgBhIaChVDMlNfUkFOS0lO",
                  "R19SQU5HRV9SRVEQoQYSGgoVUzJDX1JBTktJTkdfUkFOR0VfUkVTEKIGEhsK",
                  "FkMyU19SQU5LSU5HX05FQVJCWV9SRVEQowYSGwoWUzJDX1JBTktJTkdfTkVB",
                  "UkJZX1JFUxCkBhIeChlDMlNfUkFOS0lOR19DSEFSQUNURVJfUkVREKUGEh4K",
                  "GVMyQ19SQU5LSU5HX0NIQVJBQ1RFUl9SRVMQpgYSFwoSTUFYX1JBTktJTkdf",
                  "UEFDS0VUEL4GEhYKEU1JTl9GUklFTkRfUEFDS0VUEIQHEhgKE0MyU19GUklF",
                  "TkRfTElTVF9SRVEQhQcSGAoTUzJDX0ZSSUVORF9MSVNUX1JFUxCGBxIcChdD",
                  "MlNfRlJJRU5EX0xJU1RfQUxMX1JFURCHBxIcChdTMkNfRlJJRU5EX0xJU1Rf",
                  "QUxMX1JFUxCIBxIYChNDMlNfRlJJRU5EX0ZJTkRfUkVREIkHEhgKE1MyQ19G",
                  "UklFTkRfRklORF9SRVMQigcSFgoRTUFYX0ZSSUVORF9QQUNLRVQQtgcSFQoQ",
                  "TUlOX1BBUlRZX1BBQ0tFVBDoBxIZChRDMlNfUEFSVFlfSU5WSVRFX1JFURDp",
                  "BxIZChRTMkNfUEFSVFlfSU5WSVRFX1JFUxDqBxIZChRTMkNfUEFSVFlfSU5W",
                  "SVRFX05PVBDrBxIgChtDMlNfUEFSVFlfSU5WSVRFX0FOU1dFUl9SRVEQ7AcS",
                  "IAobUzJDX1BBUlRZX0lOVklURV9BTlNXRVJfUkVTEO0HEicKIlMyQ19QQVJU",
                  "WV9JTlZJVEVfQU5TV0VSX1JFU1VMVF9OT1QQ7gcSFwoSQzJTX1BBUlRZX0VY",
                  "SVRfUkVREO8HEhcKElMyQ19QQVJUWV9FWElUX1JFUxDwBxIeChlTMkNfUEFS",
                  "VFlfTUVNQkVSX0lORk9fTk9UEPEHEhgKE0MyU19QQVJUWV9SRUFEWV9SRVEQ",
                  "8gcSGAoTUzJDX1BBUlRZX1JFQURZX1JFUxDzBxIkCh9TMkNfUEFSVFlfRVFV",
                  "SVBfSVRFTV9DSEFOR0VfTk9UEPQHEiAKG1MyQ19QQVJUWV9SRUdJT05fQ0hB",
                  "TkdFX05PVBD1BxIiCh1TMkNfUEFSVFlfTE9DQVRJT05fVVBEQVRFX05PVBD2",
                  "BxImCiFTMkNfUEFSVFlfQ0hBUkFDVEVSX1NLSU5fTElTVF9OT1QQ9wcSKAoj",
                  "UzJDX1BBUlRZX0NIQVJBQ1RFUl9TS0lOX0NIQU5HRV9OT1QQ+AcSIQocUzJD",
                  "X1BBUlRZX0lURU1fU0tJTl9MSVNUX05PVBD5BxIjCh5TMkNfUEFSVFlfSVRF",
                  "TV9TS0lOX0NIQU5HRV9OT1QQ+gcSKQokUzJDX1BBUlRZX0dBTUVfRElGRklD",
                  "VUxUWV9DSEFOR0VfTk9UEPsHEh4KGUMyU19QQVJUWV9NRU1CRVJfS0lDS19S",
                  "RVEQ/AcSHgoZUzJDX1BBUlRZX01FTUJFUl9LSUNLX1JFUxD9BxIXChJDMlNf",
                  "UEFSVFlfQ0hBVF9SRVEQ/gcSFwoSUzJDX1BBUlRZX0NIQVRfUkVTEP8HEhcK",
                  "ElMyQ19QQVJUWV9DSEFUX05PVBCACBIfChpTMkNfUEFSVFlfUkVBRFlfQ0hB",
                  "TkdFX05PVBCBCBIdChhTMkNfUEFSVFlfS0lDS0VEX09VVF9OT1QQgggSIAob",
                  "UzJDX1BBUlRZX01FTUJFUl9BQ1RJT05fTk9UEIMIEh8KGkMyU19QQVJUWV9T",
                  "VEFSVF9BQ1RJT05fUkVREIQIEh8KGlMyQ19QQVJUWV9TVEFSVF9BQ1RJT05f",
                  "UkVTEIUIEh8KGlMyQ19QQVJUWV9TVEFSVF9BQ1RJT05fTk9UEIYIEhUKEE1B",
                  "WF9QQVJUWV9QQUNLRVQQ/ggSEgoNTUlOX0dNX1BBQ0tFVBCwCRIgChtDMlNf",
                  "R01fUEFSVFlfQUxMX1JBTkRPTV9SRVEQsQkSIAobUzJDX0dNX1BBUlRZX0FM",
                  "TF9SQU5ET01fUkVTELIJEhIKDU1BWF9HTV9QQUNLRVQQlAoSGAoTTUlOX01F",
                  "UkNIQU5UX1BBQ0tFVBDGChIaChVDMlNfTUVSQ0hBTlRfTElTVF9SRVEQxwoS",
                  "GgoVUzJDX01FUkNIQU5UX0xJU1RfUkVTEMgKEikKJEMyU19NRVJDSEFOVF9T",
                  "VE9DS19CVVlfSVRFTV9MSVNUX1JFURDJChIpCiRTMkNfTUVSQ0hBTlRfU1RP",
                  "Q0tfQlVZX0lURU1fTElTVF9SRVMQygoSLwoqQzJTX01FUkNIQU5UX1NUT0NL",
                  "X1NFTExfQkFDS19JVEVNX0xJU1RfUkVREMsKEi8KKlMyQ19NRVJDSEFOVF9T",
                  "VE9DS19TRUxMX0JBQ0tfSVRFTV9MSVNUX1JFUxDMChIfChpDMlNfTUVSQ0hB",
                  "TlRfU1RPQ0tfQlVZX1JFURDNChIfChpTMkNfTUVSQ0hBTlRfU1RPQ0tfQlVZ",
                  "X1JFUxDOChIlCiBDMlNfTUVSQ0hBTlRfU1RPQ0tfU0VMTF9CQUNLX1JFURDP",
                  "ChIlCiBTMkNfTUVSQ0hBTlRfU1RPQ0tfU0VMTF9CQUNLX1JFUxDQChIoCiND",
                  "MlNfTUVSQ0hBTlRfU0VSVklDRV9DUkFGVF9MSVNUX1JFURDRChIoCiNTMkNf",
                  "TUVSQ0hBTlRfU0VSVklDRV9DUkFGVF9MSVNUX1JFUxDSChIjCh5DMlNfTUVS",
                  "Q0hBTlRfU0VSVklDRV9DUkFGVF9SRVEQ0woSIwoeUzJDX01FUkNIQU5UX1NF",
                  "UlZJQ0VfQ1JBRlRfUkVTENQKEiQKH0MyU19NRVJDSEFOVF9TRVJWSUNFX1JF",
                  "UEFJUl9SRVEQ1QoSJAofUzJDX01FUkNIQU5UX1NFUlZJQ0VfUkVQQUlSX1JF",
                  "UxDWChIgChtDMlNfTUVSQ0hBTlRfUVVFU1RfTElTVF9SRVEQ1woSIAobUzJD",
                  "X01FUkNIQU5UX1FVRVNUX0xJU1RfUkVTENgKEhsKFkMyU19NRVJDSEFOVF9R",
                  "VUVTVF9SRVEQ2QoSGwoWUzJDX01FUkNIQU5UX1FVRVNUX1JFUxDaChIYChNN",
                  "QVhfTUVSQ0hBTlRfUEFDS0VUEMAMEhUKEE1JTl9LQVJNQV9QQUNLRVQQ8gwS",
                  "HgoZQzJTX0tBUk1BX1JFUE9SVF9MSVNUX1JFURDzDBIeChlTMkNfS0FSTUFf",
                  "UkVQT1JUX0xJU1RfUkVTEPQMEiAKG0MyU19LQVJNQV9SRVBPUlRfQUNUSU9O",
                  "X1JFURD1DBIgChtTMkNfS0FSTUFfUkVQT1JUX0FDVElPTl9SRVMQ9gwSIAob",
                  "UzJDX0tBUk1BX1JBVElOR19VUERBVEVfTk9UEPcMEhUKEE1BWF9LQVJNQV9Q",
                  "QUNLRVQQpA0SFQoQTUlOX1RSQURFX1BBQ0tFVBDQDxIfChpDMlNfVFJBREVf",
                  "Q0hBTk5FTF9MSVNUX1JFURDRDxIfChpTMkNfVFJBREVfQ0hBTk5FTF9MSVNU",
                  "X1JFUxDSDxIhChxDMlNfVFJBREVfQ0hBTk5FTF9TRUxFQ1RfUkVRENMPEiEK",
                  "HFMyQ19UUkFERV9DSEFOTkVMX1NFTEVDVF9SRVMQ1A8SHwoaQzJTX1RSQURF",
                  "X0NIQU5ORUxfRVhJVF9SRVEQ1Q8SHwoaUzJDX1RSQURFX0NIQU5ORUxfRVhJ",
                  "VF9SRVMQ1g8SJAofQzJTX1RSQURFX0NIQU5ORUxfVVNFUl9MSVNUX1JFURDX",
                  "DxIkCh9TMkNfVFJBREVfQ0hBTk5FTF9VU0VSX0xJU1RfUkVTENgPEiYKIVMy",
                  "Q19UUkFERV9DSEFOTkVMX1VTRVJfVVBEQVRFX05PVBDZDxIfChpDMlNfVFJB",
                  "REVfQ0hBTk5FTF9DSEFUX1JFURDbDxIfChpTMkNfVFJBREVfQ0hBTk5FTF9D",
                  "SEFUX1JFUxDcDxIqCiVDMlNfVFJBREVfQ0hBTk5FTF9DSEFUX1RFWFRfUkFO",
                  "R0VfUkVREN0PEioKJVMyQ19UUkFERV9DSEFOTkVMX0NIQVRfVEVYVF9SQU5H",
                  "RV9SRVMQ3g8SKQokQzJTX1RSQURFX01FTUJFUlNISVBfUkVRVUlSRU1FTlRf",
                  "UkVREO4PEikKJFMyQ19UUkFERV9NRU1CRVJTSElQX1JFUVVJUkVNRU5UX1JF",
                  "UxDvDxIdChhDMlNfVFJBREVfTUVNQkVSU0hJUF9SRVEQ8A8SHQoYUzJDX1RS",
                  "QURFX01FTUJFUlNISVBfUkVTEPEPEhoKFUMyU19UUkFERV9SRVFVRVNUX1JF",
                  "URDyDxIaChVTMkNfVFJBREVfUkVRVUVTVF9SRVMQ8w8SGgoVUzJDX1RSQURF",
                  "X1JFUVVFU1RfTk9UEPQPEhkKFEMyU19UUkFERV9BTlNXRVJfUkVREPUPEhkK",
                  "FFMyQ19UUkFERV9BTlNXRVJfUkVTEPYPEiEKHFMyQ19UUkFERV9BTlNXRVJf",
                  "UkVGVVNBTF9OT1QQ9w8SGgoVUzJDX1RSQURJTkdfQkVHSU5fTk9UEIIQEhoK",
                  "FUMyU19UUkFESU5HX0NMT1NFX1JFURCDEBIaChVTMkNfVFJBRElOR19DTE9T",
                  "RV9SRVMQhBASGQoUQzJTX1RSQURJTkdfQ0hBVF9SRVEQhRASGQoUUzJDX1RS",
                  "QURJTkdfQ0hBVF9SRVMQhhASIAobQzJTX1RSQURJTkdfSVRFTV9VUERBVEVf",
                  "UkVREIcQEiAKG1MyQ19UUkFESU5HX0lURU1fVVBEQVRFX1JFUxCIEBIaChVD",
                  "MlNfVFJBRElOR19SRUFEWV9SRVEQiRASGgoVUzJDX1RSQURJTkdfUkVBRFlf",
                  "UkVTEIoQEhoKFVMyQ19UUkFESU5HX1JFQURZX05PVBCLEBIcChdTMkNfVFJB",
                  "RElOR19DT05GSVJNX05PVBCMEBIiCh1DMlNfVFJBRElOR19DT05GSVJNX1JF",
                  "QURZX1JFURCNEBIiCh1TMkNfVFJBRElOR19DT05GSVJNX1JFQURZX1JFUxCO",
                  "EBIiCh1TMkNfVFJBRElOR19DT05GSVJNX1JFQURZX05PVBCPEBIjCh5DMlNf",
                  "VFJBRElOR19DT05GSVJNX0NBTkNFTF9SRVEQkBASIwoeUzJDX1RSQURJTkdf",
                  "Q09ORklSTV9DQU5DRUxfUkVTEJEQEhsKFlMyQ19UUkFESU5HX1JFU1VMVF9O",
                  "T1QQkhASFQoQTUFYX1RSQURFX1BBQ0tFVBD8ERIZChRNSU5fQ1VTVE9NSVpF",
                  "X1BBQ0tFVBCuEhIlCiBDMlNfQ1VTVE9NSVpFX0NIQVJBQ1RFUl9JTkZPX1JF",
                  "URCvEhIlCiBTMkNfQ1VTVE9NSVpFX0NIQVJBQ1RFUl9JTkZPX1JFUxCwEhIg",
                  "ChtDMlNfQ1VTVE9NSVpFX0lURU1fSU5GT19SRVEQsRISIAobUzJDX0NVU1RP",
                  "TUlaRV9JVEVNX0lORk9fUkVTELISEiEKHEMyU19DVVNUT01JWkVfRU1PVEVf",
                  "SU5GT19SRVEQsxISIQocUzJDX0NVU1RPTUlaRV9FTU9URV9JTkZPX1JFUxC0",
                  "EhIiCh1DMlNfQ1VTVE9NSVpFX0FDVElPTl9JTkZPX1JFURC1EhIiCh1TMkNf",
                  "Q1VTVE9NSVpFX0FDVElPTl9JTkZPX1JFUxC2EhImCiFDMlNfQ1VTVE9NSVpF",
                  "X0NIQVJBQ1RFUl9NT1VOVF9SRVEQwhISJgohUzJDX0NVU1RPTUlaRV9DSEFS",
                  "QUNURVJfTU9VTlRfUkVTEMMSEigKI0MyU19DVVNUT01JWkVfQ0hBUkFDVEVS",
                  "X1VOTU9VTlRfUkVREMQSEigKI1MyQ19DVVNUT01JWkVfQ0hBUkFDVEVSX1VO",
                  "TU9VTlRfUkVTEMUSEiEKHEMyU19DVVNUT01JWkVfSVRFTV9NT1VOVF9SRVEQ",
                  "zBISIQocUzJDX0NVU1RPTUlaRV9JVEVNX01PVU5UX1JFUxDNEhIjCh5DMlNf",
                  "Q1VTVE9NSVpFX0lURU1fVU5NT1VOVF9SRVEQzhISIwoeUzJDX0NVU1RPTUla",
                  "RV9JVEVNX1VOTU9VTlRfUkVTEM8SEiIKHUMyU19DVVNUT01JWkVfRU1PVEVf",
                  "TU9VTlRfUkVRENYSEiIKHVMyQ19DVVNUT01JWkVfRU1PVEVfTU9VTlRfUkVT",
                  "ENcSEiQKH0MyU19DVVNUT01JWkVfRU1PVEVfVU5NT1VOVF9SRVEQ2BISJAof",
                  "UzJDX0NVU1RPTUlaRV9FTU9URV9VTk1PVU5UX1JFUxDZEhIjCh5DMlNfQ1VT",
                  "VE9NSVpFX0FDVElPTl9NT1VOVF9SRVEQ4BISIwoeUzJDX0NVU1RPTUlaRV9B",
                  "Q1RJT05fTU9VTlRfUkVTEOESEiUKIEMyU19DVVNUT01JWkVfQUNUSU9OX1VO",
                  "TU9VTlRfUkVREOISEiUKIFMyQ19DVVNUT01JWkVfQUNUSU9OX1VOTU9VTlRf",
                  "UkVTEOMSEhkKFE1BWF9DVVNUT01JWkVfUEFDS0VUEJITEhQKD01JTl9TSE9Q",
                  "X1BBQ0tFVBDFExIlCiBDMlNfU0hPUF9DSEFSQUNURVJfU0tJTl9MSVNUX1JF",
                  "URDGExIlCiBTMkNfU0hPUF9DSEFSQUNURVJfU0tJTl9MSVNUX1JFUxDHExIg",
                  "ChtDMlNfU0hPUF9JVEVNX1NLSU5fTElTVF9SRVEQyBMSIAobUzJDX1NIT1Bf",
                  "SVRFTV9TS0lOX0xJU1RfUkVTEMkTEhwKF0MyU19TSE9QX0VNT1RFX0xJU1Rf",
                  "UkVREMoTEhwKF1MyQ19TSE9QX0VNT1RFX0xJU1RfUkVTEMsTEh0KGEMyU19T",
                  "SE9QX0FDVElPTl9MSVNUX1JFURDMExIdChhTMkNfU0hPUF9BQ1RJT05fTElT",
                  "VF9SRVMQzRMSJAofQzJTX1NIT1BfQ0hBUkFDVEVSX1NLSU5fQlVZX1JFURDY",
                  "ExIkCh9TMkNfU0hPUF9DSEFSQUNURVJfU0tJTl9CVVlfUkVTENkTEh8KGkMy",
                  "U19TSE9QX0lURU1fU0tJTl9CVVlfUkVRENoTEh8KGlMyQ19TSE9QX0lURU1f",
                  "U0tJTl9CVVlfUkVTENsTEhsKFkMyU19TSE9QX0VNT1RFX0JVWV9SRVEQ3BMS",
                  "GwoWUzJDX1NIT1BfRU1PVEVfQlVZX1JFUxDdExIcChdDMlNfU0hPUF9BQ1RJ",
                  "T05fQlVZX1JFURDeExIcChdTMkNfU0hPUF9BQ1RJT05fQlVZX1JFUxDfExIU",
                  "Cg9NQVhfU0hPUF9QQUNLRVQQqBQSFQoQTUlOX0NMQVNTX1BBQ0tFVBC4FxId",
                  "ChhDMlNfQ0xBU1NfTEVWRUxfSU5GT19SRVEQuRcSHQoYUzJDX0NMQVNTX0xF",
                  "VkVMX0lORk9fUkVTELoXEh0KGEMyU19DTEFTU19FUVVJUF9JTkZPX1JFURDX",
                  "FxIdChhTMkNfQ0xBU1NfRVFVSVBfSU5GT19SRVMQ2BcSHAoXQzJTX0NMQVNT",
                  "X1BFUktfTElTVF9SRVEQ4RcSHAoXUzJDX0NMQVNTX1BFUktfTElTVF9SRVMQ",
                  "4hcSHQoYQzJTX0NMQVNTX1NLSUxMX0xJU1RfUkVREOMXEh0KGFMyQ19DTEFT",
                  "U19TS0lMTF9MSVNUX1JFUxDkFxIdChhDMlNfQ0xBU1NfU1BFTExfTElTVF9S",
                  "RVEQ5RcSHQoYUzJDX0NMQVNTX1NQRUxMX0xJU1RfUkVTEOYXEhwKF0MyU19D",
                  "TEFTU19JVEVNX01PVkVfUkVREOsXEhwKF1MyQ19DTEFTU19JVEVNX01PVkVf",
                  "UkVTEOwXEiIKHUMyU19DTEFTU19TUEVMTF9TTE9UX01PVkVfUkVREO0XEiIK",
                  "HVMyQ19DTEFTU19TUEVMTF9TTE9UX01PVkVfUkVTEO4XEigKI0MyU19DTEFT",
                  "U19TUEVMTF9TRVFVRU5DRV9DSEFOR0VfUkVREO8XEigKI1MyQ19DTEFTU19T",
                  "UEVMTF9TRVFVRU5DRV9DSEFOR0VfUkVTEPAXEhUKEE1BWF9DTEFTU19QQUNL",
                  "RVQQnBgSHgoZTUlOX0dBVEhFUklOR19IQUxMX1BBQ0tFVBCAGRIoCiNDMlNf",
                  "R0FUSEVSSU5HX0hBTExfQ0hBTk5FTF9MSVNUX1JFURCBGRIoCiNTMkNfR0FU",
                  "SEVSSU5HX0hBTExfQ0hBTk5FTF9MSVNUX1JFUxCCGRIqCiVDMlNfR0FUSEVS",
                  "SU5HX0hBTExfQ0hBTk5FTF9TRUxFQ1RfUkVREIMZEioKJVMyQ19HQVRIRVJJ",
                  "TkdfSEFMTF9DSEFOTkVMX1NFTEVDVF9SRVMQhBkSKAojQzJTX0dBVEhFUklO",
                  "R19IQUxMX0NIQU5ORUxfRVhJVF9SRVEQhRkSKAojUzJDX0dBVEhFUklOR19I",
                  "QUxMX0NIQU5ORUxfRVhJVF9SRVMQhhkSLQooQzJTX0dBVEhFUklOR19IQUxM",
                  "X0NIQU5ORUxfVVNFUl9MSVNUX1JFURCHGRItCihTMkNfR0FUSEVSSU5HX0hB",
                  "TExfQ0hBTk5FTF9VU0VSX0xJU1RfUkVTEIgZEi8KKlMyQ19HQVRIRVJJTkdf",
                  "SEFMTF9DSEFOTkVMX1VTRVJfVVBEQVRFX05PVBCJGRIoCiNDMlNfR0FUSEVS",
                  "SU5HX0hBTExfQ0hBTk5FTF9DSEFUX1JFURCUGRIoCiNTMkNfR0FUSEVSSU5H",
                  "X0hBTExfQ0hBTk5FTF9DSEFUX1JFUxCVGRIoCiNTMkNfR0FUSEVSSU5HX0hB",
                  "TExfQ0hBTk5FTF9DSEFUX05PVBCWGRIwCitDMlNfR0FUSEVSSU5HX0hBTExf",
                  "VEFSR0VUX0VRVUlQUEVEX0lURU1fUkVREJ4ZEjAKK1MyQ19HQVRIRVJJTkdf",
                  "SEFMTF9UQVJHRVRfRVFVSVBQRURfSVRFTV9SRVMQnxkSHgoZTUFYX0dBVEhF",
                  "UklOR19IQUxMX1BBQ0tFVBDkGRIUCg9NSU5fTUVUQV9QQUNLRVQQkE4SGgoV",
                  "QzJTX01FVEFfTE9DQVRJT05fUkVREJFOEhoKFVMyQ19NRVRBX0xPQ0FUSU9O",
                  "X1JFUxCSThIcChdDMlNfQkxPQ0tfQ0hBUkFDVEVSX1JFURCaThIcChdTMkNf",
                  "QkxPQ0tfQ0hBUkFDVEVSX1JFUxCbThIeChlDMlNfVU5CTE9DS19DSEFSQUNU",
                  "RVJfUkVREJxOEh4KGVMyQ19VTkJMT0NLX0NIQVJBQ1RFUl9SRVMQnU4SIQoc",
                  "QzJTX0JMT0NLX0NIQVJBQ1RFUl9MSVNUX1JFURCeThIhChxTMkNfQkxPQ0tf",
                  "Q0hBUkFDVEVSX0xJU1RfUkVTEJ9OEhUKEEMyU19IQUNLX0xPR19SRVEQrk4S",
                  "FQoQUzJDX0hBQ0tfTE9HX1JFUxCvThIbChZTMkNfU0VSVklDRV9QT0xJQ1lf",
                  "Tk9UEMJOEiAKG1MyQ19IQUNLX0NIRUNLX0RMTF9MSVNUX05PVBDDThIVChBD",
                  "MlNfUkVfTE9HSU5fUkVREMxOEhUKEFMyQ19SRV9MT0dJTl9SRVMQzU4SGAoT",
                  "UzJDX0NMT1NFRF9HQU1FX05PVBDOThIiCh1DMlNfSVJPTl9TSElFTERfU0NB",
                  "Tl9JTkZPX1JFURDgThIiCh1TMkNfSVJPTl9TSElFTERfU0NBTl9JTkZPX1JF",
                  "UxDhThIdChhTMkNfT1BFUkFURV9BTk5PVU5DRV9OT1QQhFISFAoPTUFYX01F",
                  "VEFfUEFDS0VUEPhVKq0WCgxQYWNrZXRSZXN1bHQSDwoLUkVTVUxUX05PTkUQ",
                  "ABILCgdTVUNDRVNTEAESEAoMRkFJTF9HRU5FUkFMEAoSEQoNRkFJTF9TSE9S",
                  "VEFHRRALEhEKDUZBSUxfTk9fVkFMVUUQDBIbChdGQUlMX0RVUExJQ0FURV9O",
                  "SUNLTkFNRRANEisKJ0ZBSUxfQ0hBUkFDVEVSX05JQ0tOQU1FX0xFTkdUSF9T",
                  "SE9SVEFHRRAOEicKI0ZBSUxfQ0hBUkFDVEVSX05JQ0tOQU1FX0xFTkdUSF9P",
                  "VkVSEA8SGAoURkFJTF9DSEFUQUNURVJfQ0xBU1MQEBIfChtGQUlMX0NIQVJB",
                  "Q1RFUl9CQURfTklDS05BTUUQERIcChhGQUlMX0NIQVJBQ1RFUl9NQVhfQ09V",
                  "TlQQEhInCiNGQUlMX1BBUlRZX0lOVklURV9PRkZMSU5FX0NIQVJBQ1RFUhAZ",
                  "EigKJEZBSUxfUEFSVFlfSU5WSVRFX05PX0xPQkJZX0NIQVJBQ1RFUhAaEiMK",
                  "H0ZBSUxfUEFSVFlfSU5WSVRFX0FMUkVBRFlfUEFSVFkQGxIhCh1GQUlMX1BB",
                  "UlRZX0lOVklURV9NRU1CRVJfRlVMTBAcEhwKGEZBSUxfRVhJVF9QQVJUWV9O",
                  "T19QQVJUWRAeEiYKIkZBSUxfRVhJVF9BTFJFQURZX0dBTUVfU1RBUlRfUEFS",
                  "VFkQHxIlCiFGQUlMX1BBUlRZX0lOVklURV9BTlNXRVJfREVDTElORUQQIBIl",
                  "CiFGQUlMX1BBUlRZX1RBUkdFVF9CTE9DS19DSEFSQUNURVIQIRIkCiBGQUlM",
                  "X1BBUlRZX1lPVV9CTE9DS0VEX0NIQVJBQ1RFUhAiEiAKHEZBSUxfUEFSVFlf",
                  "RFVQTElDQVRFX1JFUVVFU1QQIxIkCiBGQUlMX1BBUlRZX0lOVklURV9UQVJH",
                  "RVRfVFJBRElORxAkEhwKGEZBSUxfUEFSVFlfQ0hBVF9OT19QQVJUWRAlEhoK",
                  "FkZBSUxfUEFSVFlfSVNfTUFUQ0hJTkcQJhIqCiZGQUlMX1BBUlRZX1JFQURZ",
                  "X1NIT1JUQUdFX0VOVFJBTkNFX0ZFRRAnEiwKKEZBSUxfUEFSVFlfUkVBRFlf",
                  "U0hPUlRBR0VfRU5UUkFOQ0VfTEVWRUwQKBIrCidGQUlMX0NIQVJBQ1RFUl9T",
                  "RUxFQ1RfRU5URVJfSVNfTUFUQ0hJTkcQMhIpCiVGQUlMX0NIQVJBQ1RFUl9T",
                  "RUxFQ1RfRU5URVJfTk9UX0xPQkJZEDMSIAocRkFJTF9QQVJUWV9SRUFEWV9J",
                  "U19NQVRDSElORxA3EhkKFUZBSUxfTUVSQ0hBTlRfTk9fT1BFThA8EiEKHUZB",
                  "SUxfQ0xBU1NfTk9UX0ZPVU5EX09MRF9JVEVNEGQSIQodRkFJTF9DTEFTU19O",
                  "T1RfRk9VTkRfTkVXX0lURU0QZRIhCh1GQUlMX0NMQVNTX05FV19JVEVNX0NP",
                  "TkRJVElPThBmEhMKD0ZBSUxfQ0xBU1NfU1dBUBBnEiwKKEZBSUxfQ0xBU1Nf",
                  "RVFVSVBfV0VBUE9OX01BU1RFUllfT0xEX0lURU0QaBIjCh9GQUlMX0NMQVNT",
                  "X05PVF9GT1VORF9TUEVMTF9JVEVNEGkSKQolRkFJTF9DTEFTU19EVVBMSUNB",
                  "VEVfRVFVSVBfU1BFTExfSVRFTRBqEhwKF0ZBSUxfQ0hBVF9NQVhfUk9PTV9V",
                  "U0VSEIIBEiIKHUZBSUxfQ0hBVF9TRUxFQ1RfQUxSRUFEWV9ST09NEIMBEiQK",
                  "H0ZBSUxfQ0hBVF9TRUxFQ1RfTk9UX01FTUJFUlNISVAQhAESJQogRkFJTF9D",
                  "SEFUX1NFTEVDVF9OT1RfRVhJU1RTX1JPT00QhQESJQogRkFJTF9DSEFUX1dI",
                  "SVNQRVJfTk9UX0ZPVU5EX1VTRVIQhgESIwoeRkFJTF9DSEFUX0VYSVRfTk9U",
                  "X0VYSVNUU19ST09NEIwBEi0KKEZBSUxfQ0hBVF9FWElUX0NBTk5PVF9MRUFW",
                  "RV9EVVJJTkdfVFJBREUQjQESJwoiRkFJTF9UUkFERV9SRVFVSVJFTUVOVF9T",
                  "SE9SVEFHRV9MVhCWARIpCiRGQUlMX1RSQURFX1JFUVVJUkVNRU5UX1NIT1JU",
                  "QUdFX0dPTEQQlwESIgodRkFJTF9UUkFERV9BTFJFQURZX01FTUJFUlNISVAQ",
                  "mAESHAoXRkFJTF9UUkFERV9UQVJHRVRfQkxPQ0sQmQESIQocRkFJTF9UUkFE",
                  "RV9EVVBMSUNBVEVfUkVRVUVTVBCaARIpCiRGQUlMX1RSQURFX1JFUVVFU1Rf",
                  "Tk9UX0ZPVU5EX0NIQU5ORUwQmwESIQocRkFJTF9UUkFERV9BTlNXRVJfTk9f",
                  "Q0hBTk5FTBCcARIgChtGQUlMX1RSQURJTkdfTk9UX0ZPVU5EX1VTRVIQoQES",
                  "IQocRkFJTF9UUkFESU5HX0FMUkVBRFlfVFJBRElORxCiARIfChpGQUlMX1RS",
                  "QURJTkdfTk9fTUVNQkVSU0hJUBCjARIkCh9GQUlMX1RSQURJTkdfU0hPUlRB",
                  "R0VfTUlORV9HT0xEEKQBEiYKIUZBSUxfVFJBRElOR19TSE9SVEFHRV9UQVJH",
                  "RVRfR09MRBClARIfChpGQUlMX1RSQURJTkdfSU5HQU1FX1RBUkdFVBCmARIg",
                  "ChtGQUlMX1RSQURJTkdfTk9UX0ZPVU5EX0lURU0QpwESHgoZRkFJTF9UUkFE",
                  "SU5HX0FMUkVBRFlfSVRFTRCoARImCiFGQUlMX1RSQURJTkdfTk9UX0ZPVU5E",
                  "X0VNUFRZX1NMT1QQqQESJQogRkFJTF9UUkFESU5HX1JFQURZX1NIT1JUQUdF",
                  "X0dPTEQQqgESMAorRkFJTF9UUkFESU5HX05PVF9GT1VORF9FTVBUWV9JTlZF",
                  "TlRPUllfU0xPVBCrARIhChxGQUlMX0JMT0NLX0NIQVJBQ1RFUl9BTFJFQURZ",
                  "ELQBEh8KGkZBSUxfQkxPQ0tfQ0hBUkFDVEVSX0xJTUlUELUBEiMKHkZBSUxf",
                  "QkxPQ0tfQ0hBUkFDVEVSX05PVF9GT1VORBC2ARIlCiBGQUlMX1VOQkxPQ0tf",
                  "Q0hBUkFDVEVSX05PVF9GT1VORBC3ARIdChhGQUlMX0NIQVRfTk9UX0ZPVU5E",
                  "X1VTRVIQvgESHwoaRkFJTF9GUklFTkRfRklORF9OT1RfRk9VTkQQyQESIgod",
                  "RkFJTF9DVVNUT01JWkVfTk9UX0ZPVU5EX0lURU0Q+gESJAofRkFJTF9DVVNU",
                  "T01JWkVfVU5FUVVJUFBFRF9DTEFTUxD7ARIuCilGQUlMX0NVU1RPTUlaRV9O",
                  "T19NT1VOVElOR19TTE9UX0FWQUlMQUJMRRD8ARIhChxGQUlMX0NVU1RPTUla",
                  "RV9NQVhJTVVNX0xJTUlUEP0BEhsKFkZBSUxfU0hPUF9BTFJFQURZX0lURU0Q",
                  "jgISJQogRkFJTF9TSE9QX0lURU1fU0hPUlRBR0VfQ1VSUkVOQ1kQjwISHgoZ",
                  "RkFJTF9LQVJNQV9OT1RfRk9VTkRfVVNFUhCsAhIlCiBGQUlMX0tBUk1BX1NI",
                  "T1JUQUdFX1RJQ0tFVF9DT1VOVBCtAhIhChxGQUlMX0tBUk1BX0lNUE9TU0lC",
                  "TEVfQUNUSU9OEK4CEh0KGEZBSUxfS0FSTUFfQUxSRUFEWV9WT1RFUxCvAhIt",
                  "CihGQUlMX0tBUk1BX0JBRF9DSEFSQUNURVJfSU1QT1NTSUJMRV9WT1RFELAC",
                  "EicKIkZBSUxfR0FUSEVSSU5HX0hBTExfTk9UX0ZPVU5EX1VTRVIQwAJCGAoL",
                  "Y29tLnBhY2tldHNCB3BhY2tldHNQAGIGcHJvdG8z"));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { },
                new pbr::GeneratedClrTypeInfo(new[] { typeof(global::DC.Packet.PacketCommand), typeof(global::DC.Packet.PacketResult), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SC2S_ALIVE_REQ), global::DC.Packet.SC2S_ALIVE_REQ.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SS2C_ALIVE_RES), global::DC.Packet.SS2C_ALIVE_RES.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SC2S_RECONNECT_REQ), global::DC.Packet.SC2S_RECONNECT_REQ.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SS2C_RECONNECT_RES), global::DC.Packet.SS2C_RECONNECT_RES.Parser, new[]{ "Result" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SS2C_CONNECT_SERVICE_INFO_JSON), global::DC.Packet.SS2C_CONNECT_SERVICE_INFO_JSON.Parser, new[]{ "IpAddress", "Port" }, null, null, null, null)
                }));
        }
        #endregion

    }
    #region Enums
    public enum PacketCommand
    {
        [pbr::OriginalName("PACKET_NONE")] PacketNone = 0,
        [pbr::OriginalName("C2S_ALIVE_REQ")] C2SAliveReq = 1,
        [pbr::OriginalName("S2C_ALIVE_RES")] S2CAliveRes = 2,
        [pbr::OriginalName("C2S_RECONNECT_REQ")] C2SReconnectReq = 3,
        [pbr::OriginalName("S2C_RECONNECT_RES")] S2CReconnectRes = 4,
        [pbr::OriginalName("C2S_ACCOUNT_LOGIN_REQ")] C2SAccountLoginReq = 11,
        [pbr::OriginalName("S2C_ACCOUNT_LOGIN_RES")] S2CAccountLoginRes = 12,
        [pbr::OriginalName("C2S_ACCOUNT_CHARACTER_CREATE_REQ")] C2SAccountCharacterCreateReq = 15,
        [pbr::OriginalName("S2C_ACCOUNT_CHARACTER_CREATE_RES")] S2CAccountCharacterCreateRes = 16,
        [pbr::OriginalName("C2S_ACCOUNT_CHARACTER_LIST_REQ")] C2SAccountCharacterListReq = 17,
        [pbr::OriginalName("S2C_ACCOUNT_CHARACTER_LIST_RES")] S2CAccountCharacterListRes = 18,
        [pbr::OriginalName("C2S_ACCOUNT_CHARACTER_DELETE_REQ")] C2SAccountCharacterDeleteReq = 19,
        [pbr::OriginalName("S2C_ACCOUNT_CHARACTER_DELETE_RES")] S2CAccountCharacterDeleteRes = 20,
        [pbr::OriginalName("C2S_LOBBY_ENTER_REQ")] C2SLobbyEnterReq = 21,
        [pbr::OriginalName("S2C_LOBBY_ENTER_RES")] S2CLobbyEnterRes = 22,
        [pbr::OriginalName("C2S_ACCOUNT_AGREE_ANSWER_REQ")] C2SAccountAgreeAnswerReq = 23,
        [pbr::OriginalName("S2C_ACCOUNT_AGREE_ANSWER_RES")] S2CAccountAgreeAnswerRes = 24,
        [pbr::OriginalName("C2S_CHARACTER_SELECT_ENTER_REQ")] C2SCharacterSelectEnterReq = 41,
        [pbr::OriginalName("S2C_CHARACTER_SELECT_ENTER_RES")] S2CCharacterSelectEnterRes = 42,
        [pbr::OriginalName("C2S_LOBBY_CHARACTER_INFO_REQ")] C2SLobbyCharacterInfoReq = 43,
        [pbr::OriginalName("S2C_LOBBY_CHARACTER_INFO_RES")] S2CLobbyCharacterInfoRes = 44,
        [pbr::OriginalName("C2S_OPEN_LOBBY_MAP_REQ")] C2SOpenLobbyMapReq = 45,
        [pbr::OriginalName("S2C_OPEN_LOBBY_MAP_RES")] S2COpenLobbyMapRes = 46,
        [pbr::OriginalName("C2S_LOBBY_REGION_SELECT_REQ")] C2SLobbyRegionSelectReq = 47,
        [pbr::OriginalName("S2C_LOBBY_REGION_SELECT_RES")] S2CLobbyRegionSelectRes = 48,
        [pbr::OriginalName("C2S_LOBBY_ENTER_FROM_GAME_REQ")] C2SLobbyEnterFromGameReq = 49,
        [pbr::OriginalName("S2C_LOBBY_ENTER_FROM_GAME_RES")] S2CLobbyEnterFromGameRes = 50,
        [pbr::OriginalName("C2S_LOBBY_GAME_DIFFICULTY_SELECT_REQ")] C2SLobbyGameDifficultySelectReq = 51,
        [pbr::OriginalName("S2C_LOBBY_GAME_DIFFICULTY_SELECT_RES")] S2CLobbyGameDifficultySelectRes = 52,
        [pbr::OriginalName("S2C_LOBBY_ACCOUNT_CURRENCY_LIST_NOT")] S2CLobbyAccountCurrencyListNot = 53,
        [pbr::OriginalName("S2C_LOBBY_CHARACTER_ACTION_NOT")] S2CLobbyCharacterActionNot = 54,
        [pbr::OriginalName("S2C_LOBBY_REPORT_PUNISH_LIST_NOT")] S2CLobbyReportPunishListNot = 55,
        [pbr::OriginalName("MIN_INVENTORY_PACKET")] MinInventoryPacket = 500,
        [pbr::OriginalName("C2S_INVENTORY_INFO_REQ")] C2SInventoryInfoReq = 501,
        [pbr::OriginalName("S2C_INVENTORY_INFO_RES")] S2CInventoryInfoRes = 502,
        [pbr::OriginalName("C2S_INVENTORY_ALL_UPDATE_REQ")] C2SInventoryAllUpdateReq = 503,
        [pbr::OriginalName("S2C_INVENTORY_ALL_UPDATE_RES")] S2CInventoryAllUpdateRes = 504,
        [pbr::OriginalName("C2S_INVENTORY_SINGLE_UPDATE_REQ")] C2SInventorySingleUpdateReq = 505,
        [pbr::OriginalName("S2C_INVENTORY_SINGLE_UPDATE_RES")] S2CInventorySingleUpdateRes = 506,
        [pbr::OriginalName("C2S_INVENTORY_MOVE_REQ")] C2SInventoryMoveReq = 507,
        [pbr::OriginalName("S2C_INVENTORY_MOVE_RES")] S2CInventoryMoveRes = 508,
        [pbr::OriginalName("C2S_INVENTORY_MERGE_REQ")] C2SInventoryMergeReq = 509,
        [pbr::OriginalName("S2C_INVENTORY_MERGE_RES")] S2CInventoryMergeRes = 510,
        [pbr::OriginalName("C2S_INVENTORY_SWAP_REQ")] C2SInventorySwapReq = 511,
        [pbr::OriginalName("S2C_INVENTORY_SWAP_RES")] S2CInventorySwapRes = 512,
        [pbr::OriginalName("C2S_INVENTORY_SPLIT_MOVE_REQ")] C2SInventorySplitMoveReq = 513,
        [pbr::OriginalName("S2C_INVENTORY_SPLIT_MOVE_RES")] S2CInventorySplitMoveRes = 514,
        [pbr::OriginalName("C2S_INVENTORY_SPLIT_MERGE_REQ")] C2SInventorySplitMergeReq = 515,
        [pbr::OriginalName("S2C_INVENTORY_SPLIT_MERGE_RES")] S2CInventorySplitMergeRes = 516,
        [pbr::OriginalName("C2S_INVENTORY_SPLIT_SWAP_REQ")] C2SInventorySplitSwapReq = 517,
        [pbr::OriginalName("S2C_INVENTORY_SPLIT_SWAP_RES")] S2CInventorySplitSwapRes = 518,
        [pbr::OriginalName("C2S_INVENTORY_TWO_HANDED_WEAPON_SWAP_REQ")] C2SInventoryTwoHandedWeaponSwapReq = 519,
        [pbr::OriginalName("S2C_INVENTORY_TWO_HANDED_WEAPON_SWAP_RES")] S2CInventoryTwoHandedWeaponSwapRes = 520,
        [pbr::OriginalName("C2S_STORAGE_INFO_REQ")] C2SStorageInfoReq = 551,
        [pbr::OriginalName("S2C_STORAGE_INFO_RES")] S2CStorageInfoRes = 552,
        [pbr::OriginalName("MAX_INVENTORY_PACKET")] MaxInventoryPacket = 600,
        [pbr::OriginalName("C2S_AUTO_MATCH_REG_REQ")] C2SAutoMatchRegReq = 751,
        [pbr::OriginalName("S2C_AUTO_MATCH_REG_RES")] S2CAutoMatchRegRes = 752,
        [pbr::OriginalName("S2C_ENTER_GAME_SERVER_NOT")] S2CEnterGameServerNot = 753,
        [pbr::OriginalName("C2S_GAME_ENTER_COMPLETE_NOT")] C2SGameEnterCompleteNot = 754,
        [pbr::OriginalName("S2C_AUTO_MATCH_REG_TEAM_NOT")] S2CAutoMatchRegTeamNot = 755,
        [pbr::OriginalName("C2S_RECONNECT_INGAME_REQ")] C2SReconnectIngameReq = 756,
        [pbr::OriginalName("S2C_RECONNECT_INGAME_RES")] S2CReconnectIngameRes = 757,
        [pbr::OriginalName("MIN_RANKING_PACKET")] MinRankingPacket = 800,
        [pbr::OriginalName("C2S_RANKING_RANGE_REQ")] C2SRankingRangeReq = 801,
        [pbr::OriginalName("S2C_RANKING_RANGE_RES")] S2CRankingRangeRes = 802,
        [pbr::OriginalName("C2S_RANKING_NEARBY_REQ")] C2SRankingNearbyReq = 803,
        [pbr::OriginalName("S2C_RANKING_NEARBY_RES")] S2CRankingNearbyRes = 804,
        [pbr::OriginalName("C2S_RANKING_CHARACTER_REQ")] C2SRankingCharacterReq = 805,
        [pbr::OriginalName("S2C_RANKING_CHARACTER_RES")] S2CRankingCharacterRes = 806,
        [pbr::OriginalName("MAX_RANKING_PACKET")] MaxRankingPacket = 830,
        [pbr::OriginalName("MIN_FRIEND_PACKET")] MinFriendPacket = 900,
        [pbr::OriginalName("C2S_FRIEND_LIST_REQ")] C2SFriendListReq = 901,
        [pbr::OriginalName("S2C_FRIEND_LIST_RES")] S2CFriendListRes = 902,
        [pbr::OriginalName("C2S_FRIEND_LIST_ALL_REQ")] C2SFriendListAllReq = 903,
        [pbr::OriginalName("S2C_FRIEND_LIST_ALL_RES")] S2CFriendListAllRes = 904,
        [pbr::OriginalName("C2S_FRIEND_FIND_REQ")] C2SFriendFindReq = 905,
        [pbr::OriginalName("S2C_FRIEND_FIND_RES")] S2CFriendFindRes = 906,
        [pbr::OriginalName("MAX_FRIEND_PACKET")] MaxFriendPacket = 950,
        [pbr::OriginalName("MIN_PARTY_PACKET")] MinPartyPacket = 1000,
        [pbr::OriginalName("C2S_PARTY_INVITE_REQ")] C2SPartyInviteReq = 1001,
        [pbr::OriginalName("S2C_PARTY_INVITE_RES")] S2CPartyInviteRes = 1002,
        [pbr::OriginalName("S2C_PARTY_INVITE_NOT")] S2CPartyInviteNot = 1003,
        [pbr::OriginalName("C2S_PARTY_INVITE_ANSWER_REQ")] C2SPartyInviteAnswerReq = 1004,
        [pbr::OriginalName("S2C_PARTY_INVITE_ANSWER_RES")] S2CPartyInviteAnswerRes = 1005,
        [pbr::OriginalName("S2C_PARTY_INVITE_ANSWER_RESULT_NOT")] S2CPartyInviteAnswerResultNot = 1006,
        [pbr::OriginalName("C2S_PARTY_EXIT_REQ")] C2SPartyExitReq = 1007,
        [pbr::OriginalName("S2C_PARTY_EXIT_RES")] S2CPartyExitRes = 1008,
        [pbr::OriginalName("S2C_PARTY_MEMBER_INFO_NOT")] S2CPartyMemberInfoNot = 1009,
        [pbr::OriginalName("C2S_PARTY_READY_REQ")] C2SPartyReadyReq = 1010,
        [pbr::OriginalName("S2C_PARTY_READY_RES")] S2CPartyReadyRes = 1011,
        [pbr::OriginalName("S2C_PARTY_EQUIP_ITEM_CHANGE_NOT")] S2CPartyEquipItemChangeNot = 1012,
        [pbr::OriginalName("S2C_PARTY_REGION_CHANGE_NOT")] S2CPartyRegionChangeNot = 1013,
        [pbr::OriginalName("S2C_PARTY_LOCATION_UPDATE_NOT")] S2CPartyLocationUpdateNot = 1014,
        [pbr::OriginalName("S2C_PARTY_CHARACTER_SKIN_LIST_NOT")] S2CPartyCharacterSkinListNot = 1015,
        [pbr::OriginalName("S2C_PARTY_CHARACTER_SKIN_CHANGE_NOT")] S2CPartyCharacterSkinChangeNot = 1016,
        [pbr::OriginalName("S2C_PARTY_ITEM_SKIN_LIST_NOT")] S2CPartyItemSkinListNot = 1017,
        [pbr::OriginalName("S2C_PARTY_ITEM_SKIN_CHANGE_NOT")] S2CPartyItemSkinChangeNot = 1018,
        [pbr::OriginalName("S2C_PARTY_GAME_DIFFICULTY_CHANGE_NOT")] S2CPartyGameDifficultyChangeNot = 1019,
        [pbr::OriginalName("C2S_PARTY_MEMBER_KICK_REQ")] C2SPartyMemberKickReq = 1020,
        [pbr::OriginalName("S2C_PARTY_MEMBER_KICK_RES")] S2CPartyMemberKickRes = 1021,
        [pbr::OriginalName("C2S_PARTY_CHAT_REQ")] C2SPartyChatReq = 1022,
        [pbr::OriginalName("S2C_PARTY_CHAT_RES")] S2CPartyChatRes = 1023,
        [pbr::OriginalName("S2C_PARTY_CHAT_NOT")] S2CPartyChatNot = 1024,
        [pbr::OriginalName("S2C_PARTY_READY_CHANGE_NOT")] S2CPartyReadyChangeNot = 1025,
        [pbr::OriginalName("S2C_PARTY_KICKED_OUT_NOT")] S2CPartyKickedOutNot = 1026,
        [pbr::OriginalName("S2C_PARTY_MEMBER_ACTION_NOT")] S2CPartyMemberActionNot = 1027,
        [pbr::OriginalName("C2S_PARTY_START_ACTION_REQ")] C2SPartyStartActionReq = 1028,
        [pbr::OriginalName("S2C_PARTY_START_ACTION_RES")] S2CPartyStartActionRes = 1029,
        [pbr::OriginalName("S2C_PARTY_START_ACTION_NOT")] S2CPartyStartActionNot = 1030,
        [pbr::OriginalName("MAX_PARTY_PACKET")] MaxPartyPacket = 1150,
        [pbr::OriginalName("MIN_GM_PACKET")] MinGmPacket = 1200,
        [pbr::OriginalName("C2S_GM_PARTY_ALL_RANDOM_REQ")] C2SGmPartyAllRandomReq = 1201,
        [pbr::OriginalName("S2C_GM_PARTY_ALL_RANDOM_RES")] S2CGmPartyAllRandomRes = 1202,
        [pbr::OriginalName("MAX_GM_PACKET")] MaxGmPacket = 1300,
        [pbr::OriginalName("MIN_MERCHANT_PACKET")] MinMerchantPacket = 1350,
        [pbr::OriginalName("C2S_MERCHANT_LIST_REQ")] C2SMerchantListReq = 1351,
        [pbr::OriginalName("S2C_MERCHANT_LIST_RES")] S2CMerchantListRes = 1352,
        [pbr::OriginalName("C2S_MERCHANT_STOCK_BUY_ITEM_LIST_REQ")] C2SMerchantStockBuyItemListReq = 1353,
        [pbr::OriginalName("S2C_MERCHANT_STOCK_BUY_ITEM_LIST_RES")] S2CMerchantStockBuyItemListRes = 1354,
        [pbr::OriginalName("C2S_MERCHANT_STOCK_SELL_BACK_ITEM_LIST_REQ")] C2SMerchantStockSellBackItemListReq = 1355,
        [pbr::OriginalName("S2C_MERCHANT_STOCK_SELL_BACK_ITEM_LIST_RES")] S2CMerchantStockSellBackItemListRes = 1356,
        [pbr::OriginalName("C2S_MERCHANT_STOCK_BUY_REQ")] C2SMerchantStockBuyReq = 1357,
        [pbr::OriginalName("S2C_MERCHANT_STOCK_BUY_RES")] S2CMerchantStockBuyRes = 1358,
        [pbr::OriginalName("C2S_MERCHANT_STOCK_SELL_BACK_REQ")] C2SMerchantStockSellBackReq = 1359,
        [pbr::OriginalName("S2C_MERCHANT_STOCK_SELL_BACK_RES")] S2CMerchantStockSellBackRes = 1360,
        [pbr::OriginalName("C2S_MERCHANT_SERVICE_CRAFT_LIST_REQ")] C2SMerchantServiceCraftListReq = 1361,
        [pbr::OriginalName("S2C_MERCHANT_SERVICE_CRAFT_LIST_RES")] S2CMerchantServiceCraftListRes = 1362,
        [pbr::OriginalName("C2S_MERCHANT_SERVICE_CRAFT_REQ")] C2SMerchantServiceCraftReq = 1363,
        [pbr::OriginalName("S2C_MERCHANT_SERVICE_CRAFT_RES")] S2CMerchantServiceCraftRes = 1364,
        [pbr::OriginalName("C2S_MERCHANT_SERVICE_REPAIR_REQ")] C2SMerchantServiceRepairReq = 1365,
        [pbr::OriginalName("S2C_MERCHANT_SERVICE_REPAIR_RES")] S2CMerchantServiceRepairRes = 1366,
        [pbr::OriginalName("C2S_MERCHANT_QUEST_LIST_REQ")] C2SMerchantQuestListReq = 1367,
        [pbr::OriginalName("S2C_MERCHANT_QUEST_LIST_RES")] S2CMerchantQuestListRes = 1368,
        [pbr::OriginalName("C2S_MERCHANT_QUEST_REQ")] C2SMerchantQuestReq = 1369,
        [pbr::OriginalName("S2C_MERCHANT_QUEST_RES")] S2CMerchantQuestRes = 1370,
        [pbr::OriginalName("MAX_MERCHANT_PACKET")] MaxMerchantPacket = 1600,
        [pbr::OriginalName("MIN_KARMA_PACKET")] MinKarmaPacket = 1650,
        [pbr::OriginalName("C2S_KARMA_REPORT_LIST_REQ")] C2SKarmaReportListReq = 1651,
        [pbr::OriginalName("S2C_KARMA_REPORT_LIST_RES")] S2CKarmaReportListRes = 1652,
        [pbr::OriginalName("C2S_KARMA_REPORT_ACTION_REQ")] C2SKarmaReportActionReq = 1653,
        [pbr::OriginalName("S2C_KARMA_REPORT_ACTION_RES")] S2CKarmaReportActionRes = 1654,
        [pbr::OriginalName("S2C_KARMA_RATING_UPDATE_NOT")] S2CKarmaRatingUpdateNot = 1655,
        [pbr::OriginalName("MAX_KARMA_PACKET")] MaxKarmaPacket = 1700,
        [pbr::OriginalName("MIN_TRADE_PACKET")] MinTradePacket = 2000,
        [pbr::OriginalName("C2S_TRADE_CHANNEL_LIST_REQ")] C2STradeChannelListReq = 2001,
        [pbr::OriginalName("S2C_TRADE_CHANNEL_LIST_RES")] S2CTradeChannelListRes = 2002,
        [pbr::OriginalName("C2S_TRADE_CHANNEL_SELECT_REQ")] C2STradeChannelSelectReq = 2003,
        [pbr::OriginalName("S2C_TRADE_CHANNEL_SELECT_RES")] S2CTradeChannelSelectRes = 2004,
        [pbr::OriginalName("C2S_TRADE_CHANNEL_EXIT_REQ")] C2STradeChannelExitReq = 2005,
        [pbr::OriginalName("S2C_TRADE_CHANNEL_EXIT_RES")] S2CTradeChannelExitRes = 2006,
        [pbr::OriginalName("C2S_TRADE_CHANNEL_USER_LIST_REQ")] C2STradeChannelUserListReq = 2007,
        [pbr::OriginalName("S2C_TRADE_CHANNEL_USER_LIST_RES")] S2CTradeChannelUserListRes = 2008,
        [pbr::OriginalName("S2C_TRADE_CHANNEL_USER_UPDATE_NOT")] S2CTradeChannelUserUpdateNot = 2009,
        [pbr::OriginalName("C2S_TRADE_CHANNEL_CHAT_REQ")] C2STradeChannelChatReq = 2011,
        [pbr::OriginalName("S2C_TRADE_CHANNEL_CHAT_RES")] S2CTradeChannelChatRes = 2012,
        [pbr::OriginalName("C2S_TRADE_CHANNEL_CHAT_TEXT_RANGE_REQ")] C2STradeChannelChatTextRangeReq = 2013,
        [pbr::OriginalName("S2C_TRADE_CHANNEL_CHAT_TEXT_RANGE_RES")] S2CTradeChannelChatTextRangeRes = 2014,
        [pbr::OriginalName("C2S_TRADE_MEMBERSHIP_REQUIREMENT_REQ")] C2STradeMembershipRequirementReq = 2030,
        [pbr::OriginalName("S2C_TRADE_MEMBERSHIP_REQUIREMENT_RES")] S2CTradeMembershipRequirementRes = 2031,
        [pbr::OriginalName("C2S_TRADE_MEMBERSHIP_REQ")] C2STradeMembershipReq = 2032,
        [pbr::OriginalName("S2C_TRADE_MEMBERSHIP_RES")] S2CTradeMembershipRes = 2033,
        [pbr::OriginalName("C2S_TRADE_REQUEST_REQ")] C2STradeRequestReq = 2034,
        [pbr::OriginalName("S2C_TRADE_REQUEST_RES")] S2CTradeRequestRes = 2035,
        [pbr::OriginalName("S2C_TRADE_REQUEST_NOT")] S2CTradeRequestNot = 2036,
        [pbr::OriginalName("C2S_TRADE_ANSWER_REQ")] C2STradeAnswerReq = 2037,
        [pbr::OriginalName("S2C_TRADE_ANSWER_RES")] S2CTradeAnswerRes = 2038,
        [pbr::OriginalName("S2C_TRADE_ANSWER_REFUSAL_NOT")] S2CTradeAnswerRefusalNot = 2039,
        [pbr::OriginalName("S2C_TRADING_BEGIN_NOT")] S2CTradingBeginNot = 2050,
        [pbr::OriginalName("C2S_TRADING_CLOSE_REQ")] C2STradingCloseReq = 2051,
        [pbr::OriginalName("S2C_TRADING_CLOSE_RES")] S2CTradingCloseRes = 2052,
        [pbr::OriginalName("C2S_TRADING_CHAT_REQ")] C2STradingChatReq = 2053,
        [pbr::OriginalName("S2C_TRADING_CHAT_RES")] S2CTradingChatRes = 2054,
        [pbr::OriginalName("C2S_TRADING_ITEM_UPDATE_REQ")] C2STradingItemUpdateReq = 2055,
        [pbr::OriginalName("S2C_TRADING_ITEM_UPDATE_RES")] S2CTradingItemUpdateRes = 2056,
        [pbr::OriginalName("C2S_TRADING_READY_REQ")] C2STradingReadyReq = 2057,
        [pbr::OriginalName("S2C_TRADING_READY_RES")] S2CTradingReadyRes = 2058,
        [pbr::OriginalName("S2C_TRADING_READY_NOT")] S2CTradingReadyNot = 2059,
        [pbr::OriginalName("S2C_TRADING_CONFIRM_NOT")] S2CTradingConfirmNot = 2060,
        [pbr::OriginalName("C2S_TRADING_CONFIRM_READY_REQ")] C2STradingConfirmReadyReq = 2061,
        [pbr::OriginalName("S2C_TRADING_CONFIRM_READY_RES")] S2CTradingConfirmReadyRes = 2062,
        [pbr::OriginalName("S2C_TRADING_CONFIRM_READY_NOT")] S2CTradingConfirmReadyNot = 2063,
        [pbr::OriginalName("C2S_TRADING_CONFIRM_CANCEL_REQ")] C2STradingConfirmCancelReq = 2064,
        [pbr::OriginalName("S2C_TRADING_CONFIRM_CANCEL_RES")] S2CTradingConfirmCancelRes = 2065,
        [pbr::OriginalName("S2C_TRADING_RESULT_NOT")] S2CTradingResultNot = 2066,
        [pbr::OriginalName("MAX_TRADE_PACKET")] MaxTradePacket = 2300,
        [pbr::OriginalName("MIN_CUSTOMIZE_PACKET")] MinCustomizePacket = 2350,
        [pbr::OriginalName("C2S_CUSTOMIZE_CHARACTER_INFO_REQ")] C2SCustomizeCharacterInfoReq = 2351,
        [pbr::OriginalName("S2C_CUSTOMIZE_CHARACTER_INFO_RES")] S2CCustomizeCharacterInfoRes = 2352,
        [pbr::OriginalName("C2S_CUSTOMIZE_ITEM_INFO_REQ")] C2SCustomizeItemInfoReq = 2353,
        [pbr::OriginalName("S2C_CUSTOMIZE_ITEM_INFO_RES")] S2CCustomizeItemInfoRes = 2354,
        [pbr::OriginalName("C2S_CUSTOMIZE_EMOTE_INFO_REQ")] C2SCustomizeEmoteInfoReq = 2355,
        [pbr::OriginalName("S2C_CUSTOMIZE_EMOTE_INFO_RES")] S2CCustomizeEmoteInfoRes = 2356,
        [pbr::OriginalName("C2S_CUSTOMIZE_ACTION_INFO_REQ")] C2SCustomizeActionInfoReq = 2357,
        [pbr::OriginalName("S2C_CUSTOMIZE_ACTION_INFO_RES")] S2CCustomizeActionInfoRes = 2358,
        [pbr::OriginalName("C2S_CUSTOMIZE_CHARACTER_MOUNT_REQ")] C2SCustomizeCharacterMountReq = 2370,
        [pbr::OriginalName("S2C_CUSTOMIZE_CHARACTER_MOUNT_RES")] S2CCustomizeCharacterMountRes = 2371,
        [pbr::OriginalName("C2S_CUSTOMIZE_CHARACTER_UNMOUNT_REQ")] C2SCustomizeCharacterUnmountReq = 2372,
        [pbr::OriginalName("S2C_CUSTOMIZE_CHARACTER_UNMOUNT_RES")] S2CCustomizeCharacterUnmountRes = 2373,
        [pbr::OriginalName("C2S_CUSTOMIZE_ITEM_MOUNT_REQ")] C2SCustomizeItemMountReq = 2380,
        [pbr::OriginalName("S2C_CUSTOMIZE_ITEM_MOUNT_RES")] S2CCustomizeItemMountRes = 2381,
        [pbr::OriginalName("C2S_CUSTOMIZE_ITEM_UNMOUNT_REQ")] C2SCustomizeItemUnmountReq = 2382,
        [pbr::OriginalName("S2C_CUSTOMIZE_ITEM_UNMOUNT_RES")] S2CCustomizeItemUnmountRes = 2383,
        [pbr::OriginalName("C2S_CUSTOMIZE_EMOTE_MOUNT_REQ")] C2SCustomizeEmoteMountReq = 2390,
        [pbr::OriginalName("S2C_CUSTOMIZE_EMOTE_MOUNT_RES")] S2CCustomizeEmoteMountRes = 2391,
        [pbr::OriginalName("C2S_CUSTOMIZE_EMOTE_UNMOUNT_REQ")] C2SCustomizeEmoteUnmountReq = 2392,
        [pbr::OriginalName("S2C_CUSTOMIZE_EMOTE_UNMOUNT_RES")] S2CCustomizeEmoteUnmountRes = 2393,
        [pbr::OriginalName("C2S_CUSTOMIZE_ACTION_MOUNT_REQ")] C2SCustomizeActionMountReq = 2400,
        [pbr::OriginalName("S2C_CUSTOMIZE_ACTION_MOUNT_RES")] S2CCustomizeActionMountRes = 2401,
        [pbr::OriginalName("C2S_CUSTOMIZE_ACTION_UNMOUNT_REQ")] C2SCustomizeActionUnmountReq = 2402,
        [pbr::OriginalName("S2C_CUSTOMIZE_ACTION_UNMOUNT_RES")] S2CCustomizeActionUnmountRes = 2403,
        [pbr::OriginalName("MAX_CUSTOMIZE_PACKET")] MaxCustomizePacket = 2450,
        [pbr::OriginalName("MIN_SHOP_PACKET")] MinShopPacket = 2501,
        [pbr::OriginalName("C2S_SHOP_CHARACTER_SKIN_LIST_REQ")] C2SShopCharacterSkinListReq = 2502,
        [pbr::OriginalName("S2C_SHOP_CHARACTER_SKIN_LIST_RES")] S2CShopCharacterSkinListRes = 2503,
        [pbr::OriginalName("C2S_SHOP_ITEM_SKIN_LIST_REQ")] C2SShopItemSkinListReq = 2504,
        [pbr::OriginalName("S2C_SHOP_ITEM_SKIN_LIST_RES")] S2CShopItemSkinListRes = 2505,
        [pbr::OriginalName("C2S_SHOP_EMOTE_LIST_REQ")] C2SShopEmoteListReq = 2506,
        [pbr::OriginalName("S2C_SHOP_EMOTE_LIST_RES")] S2CShopEmoteListRes = 2507,
        [pbr::OriginalName("C2S_SHOP_ACTION_LIST_REQ")] C2SShopActionListReq = 2508,
        [pbr::OriginalName("S2C_SHOP_ACTION_LIST_RES")] S2CShopActionListRes = 2509,
        [pbr::OriginalName("C2S_SHOP_CHARACTER_SKIN_BUY_REQ")] C2SShopCharacterSkinBuyReq = 2520,
        [pbr::OriginalName("S2C_SHOP_CHARACTER_SKIN_BUY_RES")] S2CShopCharacterSkinBuyRes = 2521,
        [pbr::OriginalName("C2S_SHOP_ITEM_SKIN_BUY_REQ")] C2SShopItemSkinBuyReq = 2522,
        [pbr::OriginalName("S2C_SHOP_ITEM_SKIN_BUY_RES")] S2CShopItemSkinBuyRes = 2523,
        [pbr::OriginalName("C2S_SHOP_EMOTE_BUY_REQ")] C2SShopEmoteBuyReq = 2524,
        [pbr::OriginalName("S2C_SHOP_EMOTE_BUY_RES")] S2CShopEmoteBuyRes = 2525,
        [pbr::OriginalName("C2S_SHOP_ACTION_BUY_REQ")] C2SShopActionBuyReq = 2526,
        [pbr::OriginalName("S2C_SHOP_ACTION_BUY_RES")] S2CShopActionBuyRes = 2527,
        [pbr::OriginalName("MAX_SHOP_PACKET")] MaxShopPacket = 2600,
        [pbr::OriginalName("MIN_CLASS_PACKET")] MinClassPacket = 3000,
        [pbr::OriginalName("C2S_CLASS_LEVEL_INFO_REQ")] C2SClassLevelInfoReq = 3001,
        [pbr::OriginalName("S2C_CLASS_LEVEL_INFO_RES")] S2CClassLevelInfoRes = 3002,
        [pbr::OriginalName("C2S_CLASS_EQUIP_INFO_REQ")] C2SClassEquipInfoReq = 3031,
        [pbr::OriginalName("S2C_CLASS_EQUIP_INFO_RES")] S2CClassEquipInfoRes = 3032,
        [pbr::OriginalName("C2S_CLASS_PERK_LIST_REQ")] C2SClassPerkListReq = 3041,
        [pbr::OriginalName("S2C_CLASS_PERK_LIST_RES")] S2CClassPerkListRes = 3042,
        [pbr::OriginalName("C2S_CLASS_SKILL_LIST_REQ")] C2SClassSkillListReq = 3043,
        [pbr::OriginalName("S2C_CLASS_SKILL_LIST_RES")] S2CClassSkillListRes = 3044,
        [pbr::OriginalName("C2S_CLASS_SPELL_LIST_REQ")] C2SClassSpellListReq = 3045,
        [pbr::OriginalName("S2C_CLASS_SPELL_LIST_RES")] S2CClassSpellListRes = 3046,
        [pbr::OriginalName("C2S_CLASS_ITEM_MOVE_REQ")] C2SClassItemMoveReq = 3051,
        [pbr::OriginalName("S2C_CLASS_ITEM_MOVE_RES")] S2CClassItemMoveRes = 3052,
        [pbr::OriginalName("C2S_CLASS_SPELL_SLOT_MOVE_REQ")] C2SClassSpellSlotMoveReq = 3053,
        [pbr::OriginalName("S2C_CLASS_SPELL_SLOT_MOVE_RES")] S2CClassSpellSlotMoveRes = 3054,
        [pbr::OriginalName("C2S_CLASS_SPELL_SEQUENCE_CHANGE_REQ")] C2SClassSpellSequenceChangeReq = 3055,
        [pbr::OriginalName("S2C_CLASS_SPELL_SEQUENCE_CHANGE_RES")] S2CClassSpellSequenceChangeRes = 3056,
        [pbr::OriginalName("MAX_CLASS_PACKET")] MaxClassPacket = 3100,
        [pbr::OriginalName("MIN_GATHERING_HALL_PACKET")] MinGatheringHallPacket = 3200,
        [pbr::OriginalName("C2S_GATHERING_HALL_CHANNEL_LIST_REQ")] C2SGatheringHallChannelListReq = 3201,
        [pbr::OriginalName("S2C_GATHERING_HALL_CHANNEL_LIST_RES")] S2CGatheringHallChannelListRes = 3202,
        [pbr::OriginalName("C2S_GATHERING_HALL_CHANNEL_SELECT_REQ")] C2SGatheringHallChannelSelectReq = 3203,
        [pbr::OriginalName("S2C_GATHERING_HALL_CHANNEL_SELECT_RES")] S2CGatheringHallChannelSelectRes = 3204,
        [pbr::OriginalName("C2S_GATHERING_HALL_CHANNEL_EXIT_REQ")] C2SGatheringHallChannelExitReq = 3205,
        [pbr::OriginalName("S2C_GATHERING_HALL_CHANNEL_EXIT_RES")] S2CGatheringHallChannelExitRes = 3206,
        [pbr::OriginalName("C2S_GATHERING_HALL_CHANNEL_USER_LIST_REQ")] C2SGatheringHallChannelUserListReq = 3207,
        [pbr::OriginalName("S2C_GATHERING_HALL_CHANNEL_USER_LIST_RES")] S2CGatheringHallChannelUserListRes = 3208,
        [pbr::OriginalName("S2C_GATHERING_HALL_CHANNEL_USER_UPDATE_NOT")] S2CGatheringHallChannelUserUpdateNot = 3209,
        [pbr::OriginalName("C2S_GATHERING_HALL_CHANNEL_CHAT_REQ")] C2SGatheringHallChannelChatReq = 3220,
        [pbr::OriginalName("S2C_GATHERING_HALL_CHANNEL_CHAT_RES")] S2CGatheringHallChannelChatRes = 3221,
        [pbr::OriginalName("S2C_GATHERING_HALL_CHANNEL_CHAT_NOT")] S2CGatheringHallChannelChatNot = 3222,
        [pbr::OriginalName("C2S_GATHERING_HALL_TARGET_EQUIPPED_ITEM_REQ")] C2SGatheringHallTargetEquippedItemReq = 3230,
        [pbr::OriginalName("S2C_GATHERING_HALL_TARGET_EQUIPPED_ITEM_RES")] S2CGatheringHallTargetEquippedItemRes = 3231,
        [pbr::OriginalName("MAX_GATHERING_HALL_PACKET")] MaxGatheringHallPacket = 3300,
        [pbr::OriginalName("MIN_META_PACKET")] MinMetaPacket = 10000,
        [pbr::OriginalName("C2S_META_LOCATION_REQ")] C2SMetaLocationReq = 10001,
        [pbr::OriginalName("S2C_META_LOCATION_RES")] S2CMetaLocationRes = 10002,
        [pbr::OriginalName("C2S_BLOCK_CHARACTER_REQ")] C2SBlockCharacterReq = 10010,
        [pbr::OriginalName("S2C_BLOCK_CHARACTER_RES")] S2CBlockCharacterRes = 10011,
        [pbr::OriginalName("C2S_UNBLOCK_CHARACTER_REQ")] C2SUnblockCharacterReq = 10012,
        [pbr::OriginalName("S2C_UNBLOCK_CHARACTER_RES")] S2CUnblockCharacterRes = 10013,
        [pbr::OriginalName("C2S_BLOCK_CHARACTER_LIST_REQ")] C2SBlockCharacterListReq = 10014,
        [pbr::OriginalName("S2C_BLOCK_CHARACTER_LIST_RES")] S2CBlockCharacterListRes = 10015,
        [pbr::OriginalName("C2S_HACK_LOG_REQ")] C2SHackLogReq = 10030,
        [pbr::OriginalName("S2C_HACK_LOG_RES")] S2CHackLogRes = 10031,
        [pbr::OriginalName("S2C_SERVICE_POLICY_NOT")] S2CServicePolicyNot = 10050,
        [pbr::OriginalName("S2C_HACK_CHECK_DLL_LIST_NOT")] S2CHackCheckDllListNot = 10051,
        [pbr::OriginalName("C2S_RE_LOGIN_REQ")] C2SReLoginReq = 10060,
        [pbr::OriginalName("S2C_RE_LOGIN_RES")] S2CReLoginRes = 10061,
        [pbr::OriginalName("S2C_CLOSED_GAME_NOT")] S2CClosedGameNot = 10062,
        [pbr::OriginalName("C2S_IRON_SHIELD_SCAN_INFO_REQ")] C2SIronShieldScanInfoReq = 10080,
        [pbr::OriginalName("S2C_IRON_SHIELD_SCAN_INFO_RES")] S2CIronShieldScanInfoRes = 10081,
        [pbr::OriginalName("S2C_OPERATE_ANNOUNCE_NOT")] S2COperateAnnounceNot = 10500,
        [pbr::OriginalName("MAX_META_PACKET")] MaxMetaPacket = 11000,
    }

    public enum PacketResult
    {
        [pbr::OriginalName("RESULT_NONE")] ResultNone = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("FAIL_GENERAL")] FailGeneral = 10,
        [pbr::OriginalName("FAIL_SHORTAGE")] FailShortage = 11,
        [pbr::OriginalName("FAIL_NO_VALUE")] FailNoValue = 12,
        [pbr::OriginalName("FAIL_DUPLICATE_NICKNAME")] FailDuplicateNickname = 13,
        [pbr::OriginalName("FAIL_CHARACTER_NICKNAME_LENGTH_SHORTAGE")] FailCharacterNicknameLengthShortage = 14,
        [pbr::OriginalName("FAIL_CHARACTER_NICKNAME_LENGTH_OVER")] FailCharacterNicknameLengthOver = 15,
        [pbr::OriginalName("FAIL_CHATACTER_CLASS")] FailChatacterClass = 16,
        [pbr::OriginalName("FAIL_CHARACTER_BAD_NICKNAME")] FailCharacterBadNickname = 17,
        [pbr::OriginalName("FAIL_CHARACTER_MAX_COUNT")] FailCharacterMaxCount = 18,
        [pbr::OriginalName("FAIL_PARTY_INVITE_OFFLINE_CHARACTER")] FailPartyInviteOfflineCharacter = 25,
        [pbr::OriginalName("FAIL_PARTY_INVITE_NO_LOBBY_CHARACTER")] FailPartyInviteNoLobbyCharacter = 26,
        [pbr::OriginalName("FAIL_PARTY_INVITE_ALREADY_PARTY")] FailPartyInviteAlreadyParty = 27,
        [pbr::OriginalName("FAIL_PARTY_INVITE_MEMBER_FULL")] FailPartyInviteMemberFull = 28,
        [pbr::OriginalName("FAIL_EXIT_PARTY_NO_PARTY")] FailExitPartyNoParty = 30,
        [pbr::OriginalName("FAIL_EXIT_ALREADY_GAME_START_PARTY")] FailExitAlreadyGameStartParty = 31,
        [pbr::OriginalName("FAIL_PARTY_INVITE_ANSWER_DECLINED")] FailPartyInviteAnswerDeclined = 32,
        [pbr::OriginalName("FAIL_PARTY_TARGET_BLOCK_CHARACTER")] FailPartyTargetBlockCharacter = 33,
        [pbr::OriginalName("FAIL_PARTY_YOU_BLOCKED_CHARACTER")] FailPartyYouBlockedCharacter = 34,
        [pbr::OriginalName("FAIL_PARTY_DUPLICATE_REQUEST")] FailPartyDuplicateRequest = 35,
        [pbr::OriginalName("FAIL_PARTY_INVITE_TARGET_TRADING")] FailPartyInviteTargetTrading = 36,
        [pbr::OriginalName("FAIL_PARTY_CHAT_NO_PARTY")] FailPartyChatNoParty = 37,
        [pbr::OriginalName("FAIL_PARTY_IS_MATCHING")] FailPartyIsMatching = 38,
        [pbr::OriginalName("FAIL_PARTY_READY_SHORTAGE_ENTRANCE_FEE")] FailPartyReadyShortageEntranceFee = 39,
        [pbr::OriginalName("FAIL_PARTY_READY_SHORTAGE_ENTRANCE_LEVEL")] FailPartyReadyShortageEntranceLevel = 40,
        [pbr::OriginalName("FAIL_CHARACTER_SELECT_ENTER_IS_MATCHING")] FailCharacterSelectEnterIsMatching = 50,
        [pbr::OriginalName("FAIL_CHARACTER_SELECT_ENTER_NOT_LOBBY")] FailCharacterSelectEnterNotLobby = 51,
        [pbr::OriginalName("FAIL_PARTY_READY_IS_MATCHING")] FailPartyReadyIsMatching = 55,
        [pbr::OriginalName("FAIL_MERCHANT_NO_OPEN")] FailMerchantNoOpen = 60,
        [pbr::OriginalName("FAIL_CLASS_NOT_FOUND_OLD_ITEM")] FailClassNotFoundOldItem = 100,
        [pbr::OriginalName("FAIL_CLASS_NOT_FOUND_NEW_ITEM")] FailClassNotFoundNewItem = 101,
        [pbr::OriginalName("FAIL_CLASS_NEW_ITEM_CONDITION")] FailClassNewItemCondition = 102,
        [pbr::OriginalName("FAIL_CLASS_SWAP")] FailClassSwap = 103,
        [pbr::OriginalName("FAIL_CLASS_EQUIP_WEAPON_MASTERY_OLD_ITEM")] FailClassEquipWeaponMasteryOldItem = 104,
        [pbr::OriginalName("FAIL_CLASS_NOT_FOUND_SPELL_ITEM")] FailClassNotFoundSpellItem = 105,
        [pbr::OriginalName("FAIL_CLASS_DUPLICATE_EQUIP_SPELL_ITEM")] FailClassDuplicateEquipSpellItem = 106,
        [pbr::OriginalName("FAIL_CHAT_MAX_ROOM_USER")] FailChatMaxRoomUser = 130,
        [pbr::OriginalName("FAIL_CHAT_SELECT_ALREADY_ROOM")] FailChatSelectAlreadyRoom = 131,
        [pbr::OriginalName("FAIL_CHAT_SELECT_NOT_MEMBERSHIP")] FailChatSelectNotMembership = 132,
        [pbr::OriginalName("FAIL_CHAT_SELECT_NOT_EXISTS_ROOM")] FailChatSelectNotExistsRoom = 133,
        [pbr::OriginalName("FAIL_CHAT_WHISPER_NOT_FOUND_USER")] FailChatWhisperNotFoundUser = 134,
        [pbr::OriginalName("FAIL_CHAT_EXIT_NOT_EXISTS_ROOM")] FailChatExitNotExistsRoom = 140,
        [pbr::OriginalName("FAIL_CHAT_EXIT_CANNOT_LEAVE_DURING_TRADE")] FailChatExitCannotLeaveDuringTrade = 141,
        [pbr::OriginalName("FAIL_TRADE_REQUIREMENT_SHORTAGE_LV")] FailTradeRequirementShortageLv = 150,
        [pbr::OriginalName("FAIL_TRADE_REQUIREMENT_SHORTAGE_GOLD")] FailTradeRequirementShortageGold = 151,
        [pbr::OriginalName("FAIL_TRADE_ALREADY_MEMBERSHIP")] FailTradeAlreadyMembership = 152,
        [pbr::OriginalName("FAIL_TRADE_TARGET_BLOCK")] FailTradeTargetBlock = 153,
        [pbr::OriginalName("FAIL_TRADE_DUPLICATE_REQUEST")] FailTradeDuplicateRequest = 154,
        [pbr::OriginalName("FAIL_TRADE_REQUEST_NOT_FOUND_CHANNEL")] FailTradeRequestNotFoundChannel = 155,
        [pbr::OriginalName("FAIL_TRADE_ANSWER_NO_CHANNEL")] FailTradeAnswerNoChannel = 156,
        [pbr::OriginalName("FAIL_TRADING_NOT_FOUND_USER")] FailTradingNotFoundUser = 161,
        [pbr::OriginalName("FAIL_TRADING_ALREADY_TRADING")] FailTradingAlreadyTrading = 162,
        [pbr::OriginalName("FAIL_TRADING_NO_MEMBERSHIP")] FailTradingNoMembership = 163,
        [pbr::OriginalName("FAIL_TRADING_SHORTAGE_MINE_GOLD")] FailTradingShortageMineGold = 164,
        [pbr::OriginalName("FAIL_TRADING_SHORTAGE_TARGET_GOLD")] FailTradingShortageTargetGold = 165,
        [pbr::OriginalName("FAIL_TRADING_INGAME_TARGET")] FailTradingIngameTarget = 166,
        [pbr::OriginalName("FAIL_TRADING_NOT_FOUND_ITEM")] FailTradingNotFoundItem = 167,
        [pbr::OriginalName("FAIL_TRADING_ALREADY_ITEM")] FailTradingAlreadyItem = 168,
        [pbr::OriginalName("FAIL_TRADING_NOT_FOUND_EMPTY_SLOT")] FailTradingNotFoundEmptySlot = 169,
        [pbr::OriginalName("FAIL_TRADING_READY_SHORTAGE_GOLD")] FailTradingReadyShortageGold = 170,
        [pbr::OriginalName("FAIL_TRADING_NOT_FOUND_EMPTY_INVENTORY_SLOT")] FailTradingNotFoundEmptyInventorySlot = 171,
        [pbr::OriginalName("FAIL_BLOCK_CHARACTER_ALREADY")] FailBlockCharacterAlready = 180,
        [pbr::OriginalName("FAIL_BLOCK_CHARACTER_LIMIT")] FailBlockCharacterLimit = 181,
        [pbr::OriginalName("FAIL_BLOCK_CHARACTER_NOT_FOUND")] FailBlockCharacterNotFound = 182,
        [pbr::OriginalName("FAIL_UNBLOCK_CHARACTER_NOT_FOUND")] FailUnblockCharacterNotFound = 183,
        [pbr::OriginalName("FAIL_CHAT_NOT_FOUND_USER")] FailChatNotFoundUser = 190,
        [pbr::OriginalName("FAIL_FRIEND_FIND_NOT_FOUND")] FailFriendFindNotFound = 201,
        [pbr::OriginalName("FAIL_CUSTOMIZE_NOT_FOUND_ITEM")] FailCustomizeNotFoundItem = 250,
        [pbr::OriginalName("FAIL_CUSTOMIZE_UNEQUIPPED_CLASS")] FailCustomizeUnequippedClass = 251,
        [pbr::OriginalName("FAIL_CUSTOMIZE_NO_MOUNTING_SLOT_AVAILABLE")] FailCustomizeNoMountingSlotAvailable = 252,
        [pbr::OriginalName("FAIL_CUSTOMIZE_MAXIMUM_LIMIT")] FailCustomizeMaximumLimit = 253,
        [pbr::OriginalName("FAIL_SHOP_ALREADY_ITEM")] FailShopAlreadyItem = 270,
        [pbr::OriginalName("FAIL_SHOP_ITEM_SHORTAGE_CURRENCY")] FailShopItemShortageCurrency = 271,
        [pbr::OriginalName("FAIL_KARMA_NOT_FOUND_USER")] FailKarmaNotFoundUser = 300,
        [pbr::OriginalName("FAIL_KARMA_SHORTAGE_TICKET_COUNT")] FailKarmaShortageTicketCount = 301,
        [pbr::OriginalName("FAIL_KARMA_IMPOSSIBLE_ACTION")] FailKarmaImpossibleAction = 302,
        [pbr::OriginalName("FAIL_KARMA_ALREADY_VOTES")] FailKarmaAlreadyVotes = 303,
        [pbr::OriginalName("FAIL_KARMA_BAD_CHARACTER_IMPOSSIBLE_VOTE")] FailKarmaBadCharacterImpossibleVote = 304,
        [pbr::OriginalName("FAIL_GATHERING_HALL_NOT_FOUND_USER")] FailGatheringHallNotFoundUser = 320,
    }

    #endregion

    #region Messages
    public sealed partial class SC2S_ALIVE_REQ : pb::IMessage<SC2S_ALIVE_REQ>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<SC2S_ALIVE_REQ> _parser = new pb::MessageParser<SC2S_ALIVE_REQ>(() => new SC2S_ALIVE_REQ());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SC2S_ALIVE_REQ> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::DC.Packet.PacketCommandReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SC2S_ALIVE_REQ()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SC2S_ALIVE_REQ(SC2S_ALIVE_REQ other) : this()
        {
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SC2S_ALIVE_REQ Clone()
        {
            return new SC2S_ALIVE_REQ(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as SC2S_ALIVE_REQ);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SC2S_ALIVE_REQ other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SC2S_ALIVE_REQ other)
        {
            if (other == null)
            {
                return;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                }
            }
        }
#endif

    }

    public sealed partial class SS2C_ALIVE_RES : pb::IMessage<SS2C_ALIVE_RES>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<SS2C_ALIVE_RES> _parser = new pb::MessageParser<SS2C_ALIVE_RES>(() => new SS2C_ALIVE_RES());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SS2C_ALIVE_RES> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::DC.Packet.PacketCommandReflection.Descriptor.MessageTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_ALIVE_RES()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_ALIVE_RES(SS2C_ALIVE_RES other) : this()
        {
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_ALIVE_RES Clone()
        {
            return new SS2C_ALIVE_RES(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as SS2C_ALIVE_RES);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SS2C_ALIVE_RES other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SS2C_ALIVE_RES other)
        {
            if (other == null)
            {
                return;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                }
            }
        }
#endif

    }

    public sealed partial class SC2S_RECONNECT_REQ : pb::IMessage<SC2S_RECONNECT_REQ>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<SC2S_RECONNECT_REQ> _parser = new pb::MessageParser<SC2S_RECONNECT_REQ>(() => new SC2S_RECONNECT_REQ());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SC2S_RECONNECT_REQ> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::DC.Packet.PacketCommandReflection.Descriptor.MessageTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SC2S_RECONNECT_REQ()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SC2S_RECONNECT_REQ(SC2S_RECONNECT_REQ other) : this()
        {
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SC2S_RECONNECT_REQ Clone()
        {
            return new SC2S_RECONNECT_REQ(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as SC2S_RECONNECT_REQ);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SC2S_RECONNECT_REQ other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SC2S_RECONNECT_REQ other)
        {
            if (other == null)
            {
                return;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                }
            }
        }
#endif

    }

    public sealed partial class SS2C_RECONNECT_RES : pb::IMessage<SS2C_RECONNECT_RES>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<SS2C_RECONNECT_RES> _parser = new pb::MessageParser<SS2C_RECONNECT_RES>(() => new SS2C_RECONNECT_RES());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SS2C_RECONNECT_RES> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::DC.Packet.PacketCommandReflection.Descriptor.MessageTypes[3]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_RECONNECT_RES()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_RECONNECT_RES(SS2C_RECONNECT_RES other) : this()
        {
            result_ = other.result_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_RECONNECT_RES Clone()
        {
            return new SS2C_RECONNECT_RES(this);
        }

        /// <summary>Field number for the "result" field.</summary>
        public const int ResultFieldNumber = 1;
        private uint result_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Result
        {
            get { return result_; }
            set
            {
                result_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as SS2C_RECONNECT_RES);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SS2C_RECONNECT_RES other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Result != other.Result) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Result != 0) hash ^= Result.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Result != 0)
            {
                output.WriteRawTag(8);
                output.WriteUInt32(Result);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (Result != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Result);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SS2C_RECONNECT_RES other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Result != 0)
            {
                Result = other.Result;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadUInt32();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            Result = input.ReadUInt32();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class SS2C_CONNECT_SERVICE_INFO_JSON : pb::IMessage<SS2C_CONNECT_SERVICE_INFO_JSON>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<SS2C_CONNECT_SERVICE_INFO_JSON> _parser = new pb::MessageParser<SS2C_CONNECT_SERVICE_INFO_JSON>(() => new SS2C_CONNECT_SERVICE_INFO_JSON());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SS2C_CONNECT_SERVICE_INFO_JSON> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::DC.Packet.PacketCommandReflection.Descriptor.MessageTypes[4]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_CONNECT_SERVICE_INFO_JSON()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_CONNECT_SERVICE_INFO_JSON(SS2C_CONNECT_SERVICE_INFO_JSON other) : this()
        {
            ipAddress_ = other.ipAddress_;
            port_ = other.port_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_CONNECT_SERVICE_INFO_JSON Clone()
        {
            return new SS2C_CONNECT_SERVICE_INFO_JSON(this);
        }

        /// <summary>Field number for the "ipAddress" field.</summary>
        public const int IpAddressFieldNumber = 1;
        private string ipAddress_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string IpAddress
        {
            get { return ipAddress_; }
            set
            {
                ipAddress_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "port" field.</summary>
        public const int PortFieldNumber = 2;
        private uint port_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Port
        {
            get { return port_; }
            set
            {
                port_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as SS2C_CONNECT_SERVICE_INFO_JSON);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SS2C_CONNECT_SERVICE_INFO_JSON other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (IpAddress != other.IpAddress) return false;
            if (Port != other.Port) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (IpAddress.Length != 0) hash ^= IpAddress.GetHashCode();
            if (Port != 0) hash ^= Port.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (IpAddress.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(IpAddress);
      }
      if (Port != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Port);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (IpAddress.Length != 0)
            {
                output.WriteRawTag(10);
                output.WriteString(IpAddress);
            }
            if (Port != 0)
            {
                output.WriteRawTag(16);
                output.WriteUInt32(Port);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (IpAddress.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(IpAddress);
            }
            if (Port != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Port);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SS2C_CONNECT_SERVICE_INFO_JSON other)
        {
            if (other == null)
            {
                return;
            }
            if (other.IpAddress.Length != 0)
            {
                IpAddress = other.IpAddress;
            }
            if (other.Port != 0)
            {
                Port = other.Port;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            IpAddress = input.ReadString();
            break;
          }
          case 16: {
            Port = input.ReadUInt32();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 10:
                        {
                            IpAddress = input.ReadString();
                            break;
                        }
                    case 16:
                        {
                            Port = input.ReadUInt32();
                            break;
                        }
                }
            }
        }
#endif

    }

    #endregion

}

#endregion Designer generated code
