// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Friend.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DC.Packet {

  /// <summary>Holder for reflection information generated from Friend.proto</summary>
  public static partial class FriendReflection {

    #region Descriptor
    /// <summary>File descriptor for Friend.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FriendReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgxGcmllbmQucHJvdG8SCURDLlBhY2tldBoQX0NoYXJhY3Rlci5wcm90byI/",
            "ChRTQzJTX0ZSSUVORF9MSVNUX1JFURIRCglwYWdlSW5kZXgYASABKA0SFAoM",
            "cGFnZUNhcGFjaXR5GAIgASgNIrQBChRTUzJDX0ZSSUVORF9MSVNUX1JFUxI5",
            "Cg5mcmllbmRJbmZvTGlzdBgBIAMoCzIhLkRDLlBhY2tldC5TQ0hBUkFDVEVS",
            "X0ZSSUVORF9JTkZPEhEKCXBhZ2VJbmRleBgCIAEoDRIYChB0b3RhbEZyaWVu",
            "ZENvdW50GAMgASgNEhgKEGxvYmJ5TG9jYXRlQ291bnQYBCABKA0SGgoSZHVu",
            "Z2VvbkxvY2F0ZUNvdW50GAUgASgNIhoKGFNDMlNfRlJJRU5EX0xJU1RfQUxM",
            "X1JFUSK1AQoYU1MyQ19GUklFTkRfTElTVF9BTExfUkVTEjkKDmZyaWVuZElu",
            "Zm9MaXN0GAEgAygLMiEuREMuUGFja2V0LlNDSEFSQUNURVJfRlJJRU5EX0lO",
            "Rk8SEAoIbG9vcEZsYWcYAiABKA0SFgoOdG90YWxVc2VyQ291bnQYAyABKA0S",
            "GAoQbG9iYnlMb2NhdGVDb3VudBgEIAEoDRIaChJkdW5nZW9uTG9jYXRlQ291",
            "bnQYBSABKA0iRgoUU0MyU19GUklFTkRfRklORF9SRVESLgoIbmlja05hbWUY",
            "ASABKAsyHC5EQy5QYWNrZXQuU0FDQ09VTlRfTklDS05BTUUiXQoUU1MyQ19G",
            "UklFTkRfRklORF9SRVMSDgoGcmVzdWx0GAEgASgNEjUKCmZyaWVuZEluZm8Y",
            "AiABKAsyIS5EQy5QYWNrZXQuU0NIQVJBQ1RFUl9GUklFTkRfSU5GT0IeChJj",
            "b20ucGFja2V0cy5mcmllbmRCBmZyaWVuZFAAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DC.Packet.CharacterReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SC2S_FRIEND_LIST_REQ), global::DC.Packet.SC2S_FRIEND_LIST_REQ.Parser, new[]{ "PageIndex", "PageCapacity" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SS2C_FRIEND_LIST_RES), global::DC.Packet.SS2C_FRIEND_LIST_RES.Parser, new[]{ "FriendInfoList", "PageIndex", "TotalFriendCount", "LobbyLocateCount", "DungeonLocateCount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SC2S_FRIEND_LIST_ALL_REQ), global::DC.Packet.SC2S_FRIEND_LIST_ALL_REQ.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SS2C_FRIEND_LIST_ALL_RES), global::DC.Packet.SS2C_FRIEND_LIST_ALL_RES.Parser, new[]{ "FriendInfoList", "LoopFlag", "TotalUserCount", "LobbyLocateCount", "DungeonLocateCount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SC2S_FRIEND_FIND_REQ), global::DC.Packet.SC2S_FRIEND_FIND_REQ.Parser, new[]{ "NickName" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SS2C_FRIEND_FIND_RES), global::DC.Packet.SS2C_FRIEND_FIND_RES.Parser, new[]{ "Result", "FriendInfo" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SC2S_FRIEND_LIST_REQ : pb::IMessage<SC2S_FRIEND_LIST_REQ>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SC2S_FRIEND_LIST_REQ> _parser = new pb::MessageParser<SC2S_FRIEND_LIST_REQ>(() => new SC2S_FRIEND_LIST_REQ());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SC2S_FRIEND_LIST_REQ> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.FriendReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_FRIEND_LIST_REQ() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_FRIEND_LIST_REQ(SC2S_FRIEND_LIST_REQ other) : this() {
      pageIndex_ = other.pageIndex_;
      pageCapacity_ = other.pageCapacity_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_FRIEND_LIST_REQ Clone() {
      return new SC2S_FRIEND_LIST_REQ(this);
    }

    /// <summary>Field number for the "pageIndex" field.</summary>
    public const int PageIndexFieldNumber = 1;
    private uint pageIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PageIndex {
      get { return pageIndex_; }
      set {
        pageIndex_ = value;
      }
    }

    /// <summary>Field number for the "pageCapacity" field.</summary>
    public const int PageCapacityFieldNumber = 2;
    private uint pageCapacity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PageCapacity {
      get { return pageCapacity_; }
      set {
        pageCapacity_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SC2S_FRIEND_LIST_REQ);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SC2S_FRIEND_LIST_REQ other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PageIndex != other.PageIndex) return false;
      if (PageCapacity != other.PageCapacity) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PageIndex != 0) hash ^= PageIndex.GetHashCode();
      if (PageCapacity != 0) hash ^= PageCapacity.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PageIndex != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PageIndex);
      }
      if (PageCapacity != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(PageCapacity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PageIndex != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PageIndex);
      }
      if (PageCapacity != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(PageCapacity);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PageIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PageIndex);
      }
      if (PageCapacity != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PageCapacity);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SC2S_FRIEND_LIST_REQ other) {
      if (other == null) {
        return;
      }
      if (other.PageIndex != 0) {
        PageIndex = other.PageIndex;
      }
      if (other.PageCapacity != 0) {
        PageCapacity = other.PageCapacity;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PageIndex = input.ReadUInt32();
            break;
          }
          case 16: {
            PageCapacity = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PageIndex = input.ReadUInt32();
            break;
          }
          case 16: {
            PageCapacity = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SS2C_FRIEND_LIST_RES : pb::IMessage<SS2C_FRIEND_LIST_RES>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SS2C_FRIEND_LIST_RES> _parser = new pb::MessageParser<SS2C_FRIEND_LIST_RES>(() => new SS2C_FRIEND_LIST_RES());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SS2C_FRIEND_LIST_RES> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.FriendReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_FRIEND_LIST_RES() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_FRIEND_LIST_RES(SS2C_FRIEND_LIST_RES other) : this() {
      friendInfoList_ = other.friendInfoList_.Clone();
      pageIndex_ = other.pageIndex_;
      totalFriendCount_ = other.totalFriendCount_;
      lobbyLocateCount_ = other.lobbyLocateCount_;
      dungeonLocateCount_ = other.dungeonLocateCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_FRIEND_LIST_RES Clone() {
      return new SS2C_FRIEND_LIST_RES(this);
    }

    /// <summary>Field number for the "friendInfoList" field.</summary>
    public const int FriendInfoListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::DC.Packet.SCHARACTER_FRIEND_INFO> _repeated_friendInfoList_codec
        = pb::FieldCodec.ForMessage(10, global::DC.Packet.SCHARACTER_FRIEND_INFO.Parser);
    private readonly pbc::RepeatedField<global::DC.Packet.SCHARACTER_FRIEND_INFO> friendInfoList_ = new pbc::RepeatedField<global::DC.Packet.SCHARACTER_FRIEND_INFO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::DC.Packet.SCHARACTER_FRIEND_INFO> FriendInfoList {
      get { return friendInfoList_; }
    }

    /// <summary>Field number for the "pageIndex" field.</summary>
    public const int PageIndexFieldNumber = 2;
    private uint pageIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PageIndex {
      get { return pageIndex_; }
      set {
        pageIndex_ = value;
      }
    }

    /// <summary>Field number for the "totalFriendCount" field.</summary>
    public const int TotalFriendCountFieldNumber = 3;
    private uint totalFriendCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TotalFriendCount {
      get { return totalFriendCount_; }
      set {
        totalFriendCount_ = value;
      }
    }

    /// <summary>Field number for the "lobbyLocateCount" field.</summary>
    public const int LobbyLocateCountFieldNumber = 4;
    private uint lobbyLocateCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LobbyLocateCount {
      get { return lobbyLocateCount_; }
      set {
        lobbyLocateCount_ = value;
      }
    }

    /// <summary>Field number for the "dungeonLocateCount" field.</summary>
    public const int DungeonLocateCountFieldNumber = 5;
    private uint dungeonLocateCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DungeonLocateCount {
      get { return dungeonLocateCount_; }
      set {
        dungeonLocateCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SS2C_FRIEND_LIST_RES);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SS2C_FRIEND_LIST_RES other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!friendInfoList_.Equals(other.friendInfoList_)) return false;
      if (PageIndex != other.PageIndex) return false;
      if (TotalFriendCount != other.TotalFriendCount) return false;
      if (LobbyLocateCount != other.LobbyLocateCount) return false;
      if (DungeonLocateCount != other.DungeonLocateCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= friendInfoList_.GetHashCode();
      if (PageIndex != 0) hash ^= PageIndex.GetHashCode();
      if (TotalFriendCount != 0) hash ^= TotalFriendCount.GetHashCode();
      if (LobbyLocateCount != 0) hash ^= LobbyLocateCount.GetHashCode();
      if (DungeonLocateCount != 0) hash ^= DungeonLocateCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      friendInfoList_.WriteTo(output, _repeated_friendInfoList_codec);
      if (PageIndex != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(PageIndex);
      }
      if (TotalFriendCount != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(TotalFriendCount);
      }
      if (LobbyLocateCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(LobbyLocateCount);
      }
      if (DungeonLocateCount != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(DungeonLocateCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      friendInfoList_.WriteTo(ref output, _repeated_friendInfoList_codec);
      if (PageIndex != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(PageIndex);
      }
      if (TotalFriendCount != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(TotalFriendCount);
      }
      if (LobbyLocateCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(LobbyLocateCount);
      }
      if (DungeonLocateCount != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(DungeonLocateCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += friendInfoList_.CalculateSize(_repeated_friendInfoList_codec);
      if (PageIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PageIndex);
      }
      if (TotalFriendCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TotalFriendCount);
      }
      if (LobbyLocateCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LobbyLocateCount);
      }
      if (DungeonLocateCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DungeonLocateCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SS2C_FRIEND_LIST_RES other) {
      if (other == null) {
        return;
      }
      friendInfoList_.Add(other.friendInfoList_);
      if (other.PageIndex != 0) {
        PageIndex = other.PageIndex;
      }
      if (other.TotalFriendCount != 0) {
        TotalFriendCount = other.TotalFriendCount;
      }
      if (other.LobbyLocateCount != 0) {
        LobbyLocateCount = other.LobbyLocateCount;
      }
      if (other.DungeonLocateCount != 0) {
        DungeonLocateCount = other.DungeonLocateCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            friendInfoList_.AddEntriesFrom(input, _repeated_friendInfoList_codec);
            break;
          }
          case 16: {
            PageIndex = input.ReadUInt32();
            break;
          }
          case 24: {
            TotalFriendCount = input.ReadUInt32();
            break;
          }
          case 32: {
            LobbyLocateCount = input.ReadUInt32();
            break;
          }
          case 40: {
            DungeonLocateCount = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            friendInfoList_.AddEntriesFrom(ref input, _repeated_friendInfoList_codec);
            break;
          }
          case 16: {
            PageIndex = input.ReadUInt32();
            break;
          }
          case 24: {
            TotalFriendCount = input.ReadUInt32();
            break;
          }
          case 32: {
            LobbyLocateCount = input.ReadUInt32();
            break;
          }
          case 40: {
            DungeonLocateCount = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SC2S_FRIEND_LIST_ALL_REQ : pb::IMessage<SC2S_FRIEND_LIST_ALL_REQ>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SC2S_FRIEND_LIST_ALL_REQ> _parser = new pb::MessageParser<SC2S_FRIEND_LIST_ALL_REQ>(() => new SC2S_FRIEND_LIST_ALL_REQ());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SC2S_FRIEND_LIST_ALL_REQ> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.FriendReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_FRIEND_LIST_ALL_REQ() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_FRIEND_LIST_ALL_REQ(SC2S_FRIEND_LIST_ALL_REQ other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_FRIEND_LIST_ALL_REQ Clone() {
      return new SC2S_FRIEND_LIST_ALL_REQ(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SC2S_FRIEND_LIST_ALL_REQ);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SC2S_FRIEND_LIST_ALL_REQ other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SC2S_FRIEND_LIST_ALL_REQ other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class SS2C_FRIEND_LIST_ALL_RES : pb::IMessage<SS2C_FRIEND_LIST_ALL_RES>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SS2C_FRIEND_LIST_ALL_RES> _parser = new pb::MessageParser<SS2C_FRIEND_LIST_ALL_RES>(() => new SS2C_FRIEND_LIST_ALL_RES());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SS2C_FRIEND_LIST_ALL_RES> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.FriendReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_FRIEND_LIST_ALL_RES() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_FRIEND_LIST_ALL_RES(SS2C_FRIEND_LIST_ALL_RES other) : this() {
      friendInfoList_ = other.friendInfoList_.Clone();
      loopFlag_ = other.loopFlag_;
      totalUserCount_ = other.totalUserCount_;
      lobbyLocateCount_ = other.lobbyLocateCount_;
      dungeonLocateCount_ = other.dungeonLocateCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_FRIEND_LIST_ALL_RES Clone() {
      return new SS2C_FRIEND_LIST_ALL_RES(this);
    }

    /// <summary>Field number for the "friendInfoList" field.</summary>
    public const int FriendInfoListFieldNumber = 1;
    private static readonly pb::FieldCodec<global::DC.Packet.SCHARACTER_FRIEND_INFO> _repeated_friendInfoList_codec
        = pb::FieldCodec.ForMessage(10, global::DC.Packet.SCHARACTER_FRIEND_INFO.Parser);
    private readonly pbc::RepeatedField<global::DC.Packet.SCHARACTER_FRIEND_INFO> friendInfoList_ = new pbc::RepeatedField<global::DC.Packet.SCHARACTER_FRIEND_INFO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::DC.Packet.SCHARACTER_FRIEND_INFO> FriendInfoList {
      get { return friendInfoList_; }
    }

    /// <summary>Field number for the "loopFlag" field.</summary>
    public const int LoopFlagFieldNumber = 2;
    private uint loopFlag_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LoopFlag {
      get { return loopFlag_; }
      set {
        loopFlag_ = value;
      }
    }

    /// <summary>Field number for the "totalUserCount" field.</summary>
    public const int TotalUserCountFieldNumber = 3;
    private uint totalUserCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint TotalUserCount {
      get { return totalUserCount_; }
      set {
        totalUserCount_ = value;
      }
    }

    /// <summary>Field number for the "lobbyLocateCount" field.</summary>
    public const int LobbyLocateCountFieldNumber = 4;
    private uint lobbyLocateCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint LobbyLocateCount {
      get { return lobbyLocateCount_; }
      set {
        lobbyLocateCount_ = value;
      }
    }

    /// <summary>Field number for the "dungeonLocateCount" field.</summary>
    public const int DungeonLocateCountFieldNumber = 5;
    private uint dungeonLocateCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint DungeonLocateCount {
      get { return dungeonLocateCount_; }
      set {
        dungeonLocateCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SS2C_FRIEND_LIST_ALL_RES);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SS2C_FRIEND_LIST_ALL_RES other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!friendInfoList_.Equals(other.friendInfoList_)) return false;
      if (LoopFlag != other.LoopFlag) return false;
      if (TotalUserCount != other.TotalUserCount) return false;
      if (LobbyLocateCount != other.LobbyLocateCount) return false;
      if (DungeonLocateCount != other.DungeonLocateCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= friendInfoList_.GetHashCode();
      if (LoopFlag != 0) hash ^= LoopFlag.GetHashCode();
      if (TotalUserCount != 0) hash ^= TotalUserCount.GetHashCode();
      if (LobbyLocateCount != 0) hash ^= LobbyLocateCount.GetHashCode();
      if (DungeonLocateCount != 0) hash ^= DungeonLocateCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      friendInfoList_.WriteTo(output, _repeated_friendInfoList_codec);
      if (LoopFlag != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(LoopFlag);
      }
      if (TotalUserCount != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(TotalUserCount);
      }
      if (LobbyLocateCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(LobbyLocateCount);
      }
      if (DungeonLocateCount != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(DungeonLocateCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      friendInfoList_.WriteTo(ref output, _repeated_friendInfoList_codec);
      if (LoopFlag != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(LoopFlag);
      }
      if (TotalUserCount != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(TotalUserCount);
      }
      if (LobbyLocateCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(LobbyLocateCount);
      }
      if (DungeonLocateCount != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(DungeonLocateCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += friendInfoList_.CalculateSize(_repeated_friendInfoList_codec);
      if (LoopFlag != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LoopFlag);
      }
      if (TotalUserCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(TotalUserCount);
      }
      if (LobbyLocateCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(LobbyLocateCount);
      }
      if (DungeonLocateCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DungeonLocateCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SS2C_FRIEND_LIST_ALL_RES other) {
      if (other == null) {
        return;
      }
      friendInfoList_.Add(other.friendInfoList_);
      if (other.LoopFlag != 0) {
        LoopFlag = other.LoopFlag;
      }
      if (other.TotalUserCount != 0) {
        TotalUserCount = other.TotalUserCount;
      }
      if (other.LobbyLocateCount != 0) {
        LobbyLocateCount = other.LobbyLocateCount;
      }
      if (other.DungeonLocateCount != 0) {
        DungeonLocateCount = other.DungeonLocateCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            friendInfoList_.AddEntriesFrom(input, _repeated_friendInfoList_codec);
            break;
          }
          case 16: {
            LoopFlag = input.ReadUInt32();
            break;
          }
          case 24: {
            TotalUserCount = input.ReadUInt32();
            break;
          }
          case 32: {
            LobbyLocateCount = input.ReadUInt32();
            break;
          }
          case 40: {
            DungeonLocateCount = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            friendInfoList_.AddEntriesFrom(ref input, _repeated_friendInfoList_codec);
            break;
          }
          case 16: {
            LoopFlag = input.ReadUInt32();
            break;
          }
          case 24: {
            TotalUserCount = input.ReadUInt32();
            break;
          }
          case 32: {
            LobbyLocateCount = input.ReadUInt32();
            break;
          }
          case 40: {
            DungeonLocateCount = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SC2S_FRIEND_FIND_REQ : pb::IMessage<SC2S_FRIEND_FIND_REQ>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SC2S_FRIEND_FIND_REQ> _parser = new pb::MessageParser<SC2S_FRIEND_FIND_REQ>(() => new SC2S_FRIEND_FIND_REQ());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SC2S_FRIEND_FIND_REQ> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.FriendReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_FRIEND_FIND_REQ() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_FRIEND_FIND_REQ(SC2S_FRIEND_FIND_REQ other) : this() {
      nickName_ = other.nickName_ != null ? other.nickName_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_FRIEND_FIND_REQ Clone() {
      return new SC2S_FRIEND_FIND_REQ(this);
    }

    /// <summary>Field number for the "nickName" field.</summary>
    public const int NickNameFieldNumber = 1;
    private global::DC.Packet.SACCOUNT_NICKNAME nickName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DC.Packet.SACCOUNT_NICKNAME NickName {
      get { return nickName_; }
      set {
        nickName_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SC2S_FRIEND_FIND_REQ);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SC2S_FRIEND_FIND_REQ other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(NickName, other.NickName)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (nickName_ != null) hash ^= NickName.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (nickName_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(NickName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (nickName_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(NickName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (nickName_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NickName);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SC2S_FRIEND_FIND_REQ other) {
      if (other == null) {
        return;
      }
      if (other.nickName_ != null) {
        if (nickName_ == null) {
          NickName = new global::DC.Packet.SACCOUNT_NICKNAME();
        }
        NickName.MergeFrom(other.NickName);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (nickName_ == null) {
              NickName = new global::DC.Packet.SACCOUNT_NICKNAME();
            }
            input.ReadMessage(NickName);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (nickName_ == null) {
              NickName = new global::DC.Packet.SACCOUNT_NICKNAME();
            }
            input.ReadMessage(NickName);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SS2C_FRIEND_FIND_RES : pb::IMessage<SS2C_FRIEND_FIND_RES>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SS2C_FRIEND_FIND_RES> _parser = new pb::MessageParser<SS2C_FRIEND_FIND_RES>(() => new SS2C_FRIEND_FIND_RES());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SS2C_FRIEND_FIND_RES> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.FriendReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_FRIEND_FIND_RES() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_FRIEND_FIND_RES(SS2C_FRIEND_FIND_RES other) : this() {
      result_ = other.result_;
      friendInfo_ = other.friendInfo_ != null ? other.friendInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_FRIEND_FIND_RES Clone() {
      return new SS2C_FRIEND_FIND_RES(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private uint result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "friendInfo" field.</summary>
    public const int FriendInfoFieldNumber = 2;
    private global::DC.Packet.SCHARACTER_FRIEND_INFO friendInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DC.Packet.SCHARACTER_FRIEND_INFO FriendInfo {
      get { return friendInfo_; }
      set {
        friendInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SS2C_FRIEND_FIND_RES);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SS2C_FRIEND_FIND_RES other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (!object.Equals(FriendInfo, other.FriendInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (friendInfo_ != null) hash ^= FriendInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Result);
      }
      if (friendInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FriendInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Result);
      }
      if (friendInfo_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(FriendInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Result);
      }
      if (friendInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(FriendInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SS2C_FRIEND_FIND_RES other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.friendInfo_ != null) {
        if (friendInfo_ == null) {
          FriendInfo = new global::DC.Packet.SCHARACTER_FRIEND_INFO();
        }
        FriendInfo.MergeFrom(other.FriendInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadUInt32();
            break;
          }
          case 18: {
            if (friendInfo_ == null) {
              FriendInfo = new global::DC.Packet.SCHARACTER_FRIEND_INFO();
            }
            input.ReadMessage(FriendInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = input.ReadUInt32();
            break;
          }
          case 18: {
            if (friendInfo_ == null) {
              FriendInfo = new global::DC.Packet.SCHARACTER_FRIEND_INFO();
            }
            input.ReadMessage(FriendInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
