// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: InGame.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DC.Packet
{

    /// <summary>Holder for reflection information generated from InGame.proto</summary>
    public static partial class InGameReflection
    {

        #region Descriptor
        /// <summary>File descriptor for InGame.proto</summary>
        public static pbr::FileDescriptor Descriptor
        {
            get { return descriptor; }
        }
        private static pbr::FileDescriptor descriptor;

        static InGameReflection()
        {
            byte[] descriptorData = global::System.Convert.FromBase64String(
                string.Concat(
                  "CgxJbkdhbWUucHJvdG8SCURDLlBhY2tldBoQX0NoYXJhY3Rlci5wcm90byKh",
                  "AQoaU1MyQ19FTlRFUl9HQU1FX1NFUlZFUl9OT1QSDAoEcG9ydBgBIAEoDRIK",
                  "CgJpcBgCIAEoCRIRCglzZXNzaW9uSWQYAyABKAkSEQoJYWNjb3VudElkGAQg",
                  "ASgJEhMKC2lzUmVjb25uZWN0GAUgASgNEi4KCG5pY2tOYW1lGAYgASgLMhwu",
                  "REMuUGFja2V0LlNBQ0NPVU5UX05JQ0tOQU1FInsKF1NDMlNfQVVUT19NQVRD",
                  "SF9SRUdfUkVREgwKBG1vZGUYASABKA0SDgoGcmVnaW9uGAIgASgNEhYKDmRp",
                  "ZmZpY3VsdHlUeXBlGAMgASgNIioKBE1PREUSCAoETk9ORRAAEgwKCFJFR0lT",
                  "VEVSEAESCgoGQ0FOQ0VMEAIijAIKF1NTMkNfQVVUT19NQVRDSF9SRUdfUkVT",
                  "Eg4KBnJlc3VsdBgBIAEoDSLgAQoGUkVTVUxUEggKBE5PTkUQABILCgdTVUND",
                  "RVNTEAESCAoERkFJTBACEhcKE0ZBSUxfQUxSRUFEWV9UUllJTkcQAxIeChpG",
                  "QUlMX05PX1JFQURZX1BBUlRZX01FTUJFUhAEEhYKEkZBSUxfUkVHSU9OX1NF",
                  "TEVDVBAFEhcKE0ZBSUxfU0VSVkVSX0RJU0FCTEUQBhIeChpGQUlMX1NIT1JU",
                  "QUdFX0VOVFJBTkNFX0ZFRRAHEhIKDkZBSUxfU09MT19PTkxZEAgSFwoTRkFJ",
                  "TF9TSE9SVEFHRV9MRVZFTBAJIjEKHFNDMlNfR0FNRV9FTlRFUl9DT01QTEVU",
                  "RV9OT1QSEQoJaXNTdWNjZXNzGAEgASgNIjwKHFNTMkNfQVVUT19NQVRDSF9S",
                  "RUdfVEVBTV9OT1QSDgoGcmVzdWx0GAEgASgNEgwKBG1vZGUYAiABKA0iXgoZ",
                  "U0MyU19SRUNPTk5FQ1RfSU5HQU1FX1JFURIRCglpc1JlZnVzYWwYASABKA0S",
                  "LgoIbmlja05hbWUYAiABKAsyHC5EQy5QYWNrZXQuU0FDQ09VTlRfTklDS05B",
                  "TUUiPwoZU1MyQ19SRUNPTk5FQ1RfSU5HQU1FX1JFUxIOCgZyZXN1bHQYASAB",
                  "KA0SEgoKc2VydmljZVVybBgCIAEoCUIeChJjb20ucGFja2V0cy5pbmdhbWVC",
                  "BmluZ2FtZVAAYgZwcm90bzM="));
            descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
                new pbr::FileDescriptor[] { global::DC.Packet.CharacterReflection.Descriptor, },
                new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SS2C_ENTER_GAME_SERVER_NOT), global::DC.Packet.SS2C_ENTER_GAME_SERVER_NOT.Parser, new[]{ "Port", "Ip", "SessionId", "AccountId", "IsReconnect", "NickName" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SC2S_AUTO_MATCH_REG_REQ), global::DC.Packet.SC2S_AUTO_MATCH_REG_REQ.Parser, new[]{ "Mode", "Region", "DifficultyType" }, null, new[]{ typeof(global::DC.Packet.SC2S_AUTO_MATCH_REG_REQ.Types.MODE) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SS2C_AUTO_MATCH_REG_RES), global::DC.Packet.SS2C_AUTO_MATCH_REG_RES.Parser, new[]{ "Result" }, null, new[]{ typeof(global::DC.Packet.SS2C_AUTO_MATCH_REG_RES.Types.RESULT) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SC2S_GAME_ENTER_COMPLETE_NOT), global::DC.Packet.SC2S_GAME_ENTER_COMPLETE_NOT.Parser, new[]{ "IsSuccess" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SS2C_AUTO_MATCH_REG_TEAM_NOT), global::DC.Packet.SS2C_AUTO_MATCH_REG_TEAM_NOT.Parser, new[]{ "Result", "Mode" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SC2S_RECONNECT_INGAME_REQ), global::DC.Packet.SC2S_RECONNECT_INGAME_REQ.Parser, new[]{ "IsRefusal", "NickName" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SS2C_RECONNECT_INGAME_RES), global::DC.Packet.SS2C_RECONNECT_INGAME_RES.Parser, new[]{ "Result", "ServiceUrl" }, null, null, null, null)
                }));
        }
        #endregion

    }
    #region Messages
    public sealed partial class SS2C_ENTER_GAME_SERVER_NOT : pb::IMessage<SS2C_ENTER_GAME_SERVER_NOT>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<SS2C_ENTER_GAME_SERVER_NOT> _parser = new pb::MessageParser<SS2C_ENTER_GAME_SERVER_NOT>(() => new SS2C_ENTER_GAME_SERVER_NOT());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SS2C_ENTER_GAME_SERVER_NOT> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::DC.Packet.InGameReflection.Descriptor.MessageTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_ENTER_GAME_SERVER_NOT()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_ENTER_GAME_SERVER_NOT(SS2C_ENTER_GAME_SERVER_NOT other) : this()
        {
            port_ = other.port_;
            ip_ = other.ip_;
            sessionId_ = other.sessionId_;
            accountId_ = other.accountId_;
            isReconnect_ = other.isReconnect_;
            nickName_ = other.nickName_ != null ? other.nickName_.Clone() : null;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_ENTER_GAME_SERVER_NOT Clone()
        {
            return new SS2C_ENTER_GAME_SERVER_NOT(this);
        }

        /// <summary>Field number for the "port" field.</summary>
        public const int PortFieldNumber = 1;
        private uint port_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Port
        {
            get { return port_; }
            set
            {
                port_ = value;
            }
        }

        /// <summary>Field number for the "ip" field.</summary>
        public const int IpFieldNumber = 2;
        private string ip_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string Ip
        {
            get { return ip_; }
            set
            {
                ip_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "sessionId" field.</summary>
        public const int SessionIdFieldNumber = 3;
        private string sessionId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string SessionId
        {
            get { return sessionId_; }
            set
            {
                sessionId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "accountId" field.</summary>
        public const int AccountIdFieldNumber = 4;
        private string accountId_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string AccountId
        {
            get { return accountId_; }
            set
            {
                accountId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        /// <summary>Field number for the "isReconnect" field.</summary>
        public const int IsReconnectFieldNumber = 5;
        private uint isReconnect_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint IsReconnect
        {
            get { return isReconnect_; }
            set
            {
                isReconnect_ = value;
            }
        }

        /// <summary>Field number for the "nickName" field.</summary>
        public const int NickNameFieldNumber = 6;
        private global::DC.Packet.SACCOUNT_NICKNAME nickName_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::DC.Packet.SACCOUNT_NICKNAME NickName
        {
            get { return nickName_; }
            set
            {
                nickName_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as SS2C_ENTER_GAME_SERVER_NOT);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SS2C_ENTER_GAME_SERVER_NOT other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Port != other.Port) return false;
            if (Ip != other.Ip) return false;
            if (SessionId != other.SessionId) return false;
            if (AccountId != other.AccountId) return false;
            if (IsReconnect != other.IsReconnect) return false;
            if (!object.Equals(NickName, other.NickName)) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Port != 0) hash ^= Port.GetHashCode();
            if (Ip.Length != 0) hash ^= Ip.GetHashCode();
            if (SessionId.Length != 0) hash ^= SessionId.GetHashCode();
            if (AccountId.Length != 0) hash ^= AccountId.GetHashCode();
            if (IsReconnect != 0) hash ^= IsReconnect.GetHashCode();
            if (nickName_ != null) hash ^= NickName.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Port != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Port);
      }
      if (Ip.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Ip);
      }
      if (SessionId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SessionId);
      }
      if (AccountId.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AccountId);
      }
      if (IsReconnect != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(IsReconnect);
      }
      if (nickName_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(NickName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Port != 0)
            {
                output.WriteRawTag(8);
                output.WriteUInt32(Port);
            }
            if (Ip.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(Ip);
            }
            if (SessionId.Length != 0)
            {
                output.WriteRawTag(26);
                output.WriteString(SessionId);
            }
            if (AccountId.Length != 0)
            {
                output.WriteRawTag(34);
                output.WriteString(AccountId);
            }
            if (IsReconnect != 0)
            {
                output.WriteRawTag(40);
                output.WriteUInt32(IsReconnect);
            }
            if (nickName_ != null)
            {
                output.WriteRawTag(50);
                output.WriteMessage(NickName);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (Port != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Port);
            }
            if (Ip.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(Ip);
            }
            if (SessionId.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(SessionId);
            }
            if (AccountId.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountId);
            }
            if (IsReconnect != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IsReconnect);
            }
            if (nickName_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(NickName);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SS2C_ENTER_GAME_SERVER_NOT other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Port != 0)
            {
                Port = other.Port;
            }
            if (other.Ip.Length != 0)
            {
                Ip = other.Ip;
            }
            if (other.SessionId.Length != 0)
            {
                SessionId = other.SessionId;
            }
            if (other.AccountId.Length != 0)
            {
                AccountId = other.AccountId;
            }
            if (other.IsReconnect != 0)
            {
                IsReconnect = other.IsReconnect;
            }
            if (other.nickName_ != null)
            {
                if (nickName_ == null)
                {
                    NickName = new global::DC.Packet.SACCOUNT_NICKNAME();
                }
                NickName.MergeFrom(other.NickName);
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Port = input.ReadUInt32();
            break;
          }
          case 18: {
            Ip = input.ReadString();
            break;
          }
          case 26: {
            SessionId = input.ReadString();
            break;
          }
          case 34: {
            AccountId = input.ReadString();
            break;
          }
          case 40: {
            IsReconnect = input.ReadUInt32();
            break;
          }
          case 50: {
            if (nickName_ == null) {
              NickName = new global::DC.Packet.SACCOUNT_NICKNAME();
            }
            input.ReadMessage(NickName);
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            Port = input.ReadUInt32();
                            break;
                        }
                    case 18:
                        {
                            Ip = input.ReadString();
                            break;
                        }
                    case 26:
                        {
                            SessionId = input.ReadString();
                            break;
                        }
                    case 34:
                        {
                            AccountId = input.ReadString();
                            break;
                        }
                    case 40:
                        {
                            IsReconnect = input.ReadUInt32();
                            break;
                        }
                    case 50:
                        {
                            if (nickName_ == null)
                            {
                                NickName = new global::DC.Packet.SACCOUNT_NICKNAME();
                            }
                            input.ReadMessage(NickName);
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class SC2S_AUTO_MATCH_REG_REQ : pb::IMessage<SC2S_AUTO_MATCH_REG_REQ>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<SC2S_AUTO_MATCH_REG_REQ> _parser = new pb::MessageParser<SC2S_AUTO_MATCH_REG_REQ>(() => new SC2S_AUTO_MATCH_REG_REQ());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SC2S_AUTO_MATCH_REG_REQ> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::DC.Packet.InGameReflection.Descriptor.MessageTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SC2S_AUTO_MATCH_REG_REQ()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SC2S_AUTO_MATCH_REG_REQ(SC2S_AUTO_MATCH_REG_REQ other) : this()
        {
            mode_ = other.mode_;
            region_ = other.region_;
            difficultyType_ = other.difficultyType_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SC2S_AUTO_MATCH_REG_REQ Clone()
        {
            return new SC2S_AUTO_MATCH_REG_REQ(this);
        }

        /// <summary>Field number for the "mode" field.</summary>
        public const int ModeFieldNumber = 1;
        private uint mode_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Mode
        {
            get { return mode_; }
            set
            {
                mode_ = value;
            }
        }

        /// <summary>Field number for the "region" field.</summary>
        public const int RegionFieldNumber = 2;
        private uint region_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Region
        {
            get { return region_; }
            set
            {
                region_ = value;
            }
        }

        /// <summary>Field number for the "difficultyType" field.</summary>
        public const int DifficultyTypeFieldNumber = 3;
        private uint difficultyType_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint DifficultyType
        {
            get { return difficultyType_; }
            set
            {
                difficultyType_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as SC2S_AUTO_MATCH_REG_REQ);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SC2S_AUTO_MATCH_REG_REQ other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Mode != other.Mode) return false;
            if (Region != other.Region) return false;
            if (DifficultyType != other.DifficultyType) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Mode != 0) hash ^= Mode.GetHashCode();
            if (Region != 0) hash ^= Region.GetHashCode();
            if (DifficultyType != 0) hash ^= DifficultyType.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Mode != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Mode);
      }
      if (Region != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Region);
      }
      if (DifficultyType != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(DifficultyType);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Mode != 0)
            {
                output.WriteRawTag(8);
                output.WriteUInt32(Mode);
            }
            if (Region != 0)
            {
                output.WriteRawTag(16);
                output.WriteUInt32(Region);
            }
            if (DifficultyType != 0)
            {
                output.WriteRawTag(24);
                output.WriteUInt32(DifficultyType);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (Mode != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Mode);
            }
            if (Region != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Region);
            }
            if (DifficultyType != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(DifficultyType);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SC2S_AUTO_MATCH_REG_REQ other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Mode != 0)
            {
                Mode = other.Mode;
            }
            if (other.Region != 0)
            {
                Region = other.Region;
            }
            if (other.DifficultyType != 0)
            {
                DifficultyType = other.DifficultyType;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Mode = input.ReadUInt32();
            break;
          }
          case 16: {
            Region = input.ReadUInt32();
            break;
          }
          case 24: {
            DifficultyType = input.ReadUInt32();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            Mode = input.ReadUInt32();
                            break;
                        }
                    case 16:
                        {
                            Region = input.ReadUInt32();
                            break;
                        }
                    case 24:
                        {
                            DifficultyType = input.ReadUInt32();
                            break;
                        }
                }
            }
        }
#endif

        #region Nested types
        /// <summary>Container for nested types declared in the SC2S_AUTO_MATCH_REG_REQ message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types
        {
            public enum MODE
            {
                [pbr::OriginalName("NONE")] None = 0,
                [pbr::OriginalName("REGISTER")] Register = 1,
                [pbr::OriginalName("CANCEL")] Cancel = 2,
            }

        }
        #endregion

    }

    public sealed partial class SS2C_AUTO_MATCH_REG_RES : pb::IMessage<SS2C_AUTO_MATCH_REG_RES>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<SS2C_AUTO_MATCH_REG_RES> _parser = new pb::MessageParser<SS2C_AUTO_MATCH_REG_RES>(() => new SS2C_AUTO_MATCH_REG_RES());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SS2C_AUTO_MATCH_REG_RES> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::DC.Packet.InGameReflection.Descriptor.MessageTypes[2]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_AUTO_MATCH_REG_RES()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_AUTO_MATCH_REG_RES(SS2C_AUTO_MATCH_REG_RES other) : this()
        {
            result_ = other.result_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_AUTO_MATCH_REG_RES Clone()
        {
            return new SS2C_AUTO_MATCH_REG_RES(this);
        }

        /// <summary>Field number for the "result" field.</summary>
        public const int ResultFieldNumber = 1;
        private uint result_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Result
        {
            get { return result_; }
            set
            {
                result_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as SS2C_AUTO_MATCH_REG_RES);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SS2C_AUTO_MATCH_REG_RES other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Result != other.Result) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Result != 0) hash ^= Result.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Result);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Result != 0)
            {
                output.WriteRawTag(8);
                output.WriteUInt32(Result);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (Result != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Result);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SS2C_AUTO_MATCH_REG_RES other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Result != 0)
            {
                Result = other.Result;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadUInt32();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            Result = input.ReadUInt32();
                            break;
                        }
                }
            }
        }
#endif

        #region Nested types
        /// <summary>Container for nested types declared in the SS2C_AUTO_MATCH_REG_RES message type.</summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static partial class Types
        {
            public enum RESULT
            {
                [pbr::OriginalName("NONE")] None = 0,
                [pbr::OriginalName("SUCCESS")] Success = 1,
                [pbr::OriginalName("FAIL")] Fail = 2,
                [pbr::OriginalName("FAIL_ALREADY_TRYING")] FailAlreadyTrying = 3,
                [pbr::OriginalName("FAIL_NO_READY_PARTY_MEMBER")] FailNoReadyPartyMember = 4,
                [pbr::OriginalName("FAIL_REGION_SELECT")] FailRegionSelect = 5,
                [pbr::OriginalName("FAIL_SERVER_DISABLE")] FailServerDisable = 6,
                [pbr::OriginalName("FAIL_SHORTAGE_ENTRANCE_FEE")] FailShortageEntranceFee = 7,
                [pbr::OriginalName("FAIL_SOLO_ONLY")] FailSoloOnly = 8,
                [pbr::OriginalName("FAIL_SHORTAGE_LEVEL")] FailShortageLevel = 9,
            }

        }
        #endregion

    }

    public sealed partial class SC2S_GAME_ENTER_COMPLETE_NOT : pb::IMessage<SC2S_GAME_ENTER_COMPLETE_NOT>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<SC2S_GAME_ENTER_COMPLETE_NOT> _parser = new pb::MessageParser<SC2S_GAME_ENTER_COMPLETE_NOT>(() => new SC2S_GAME_ENTER_COMPLETE_NOT());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SC2S_GAME_ENTER_COMPLETE_NOT> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::DC.Packet.InGameReflection.Descriptor.MessageTypes[3]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SC2S_GAME_ENTER_COMPLETE_NOT()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SC2S_GAME_ENTER_COMPLETE_NOT(SC2S_GAME_ENTER_COMPLETE_NOT other) : this()
        {
            isSuccess_ = other.isSuccess_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SC2S_GAME_ENTER_COMPLETE_NOT Clone()
        {
            return new SC2S_GAME_ENTER_COMPLETE_NOT(this);
        }

        /// <summary>Field number for the "isSuccess" field.</summary>
        public const int IsSuccessFieldNumber = 1;
        private uint isSuccess_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint IsSuccess
        {
            get { return isSuccess_; }
            set
            {
                isSuccess_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as SC2S_GAME_ENTER_COMPLETE_NOT);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SC2S_GAME_ENTER_COMPLETE_NOT other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (IsSuccess != other.IsSuccess) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (IsSuccess != 0) hash ^= IsSuccess.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (IsSuccess != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(IsSuccess);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (IsSuccess != 0)
            {
                output.WriteRawTag(8);
                output.WriteUInt32(IsSuccess);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (IsSuccess != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IsSuccess);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SC2S_GAME_ENTER_COMPLETE_NOT other)
        {
            if (other == null)
            {
                return;
            }
            if (other.IsSuccess != 0)
            {
                IsSuccess = other.IsSuccess;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IsSuccess = input.ReadUInt32();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            IsSuccess = input.ReadUInt32();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class SS2C_AUTO_MATCH_REG_TEAM_NOT : pb::IMessage<SS2C_AUTO_MATCH_REG_TEAM_NOT>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<SS2C_AUTO_MATCH_REG_TEAM_NOT> _parser = new pb::MessageParser<SS2C_AUTO_MATCH_REG_TEAM_NOT>(() => new SS2C_AUTO_MATCH_REG_TEAM_NOT());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SS2C_AUTO_MATCH_REG_TEAM_NOT> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::DC.Packet.InGameReflection.Descriptor.MessageTypes[4]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_AUTO_MATCH_REG_TEAM_NOT()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_AUTO_MATCH_REG_TEAM_NOT(SS2C_AUTO_MATCH_REG_TEAM_NOT other) : this()
        {
            result_ = other.result_;
            mode_ = other.mode_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_AUTO_MATCH_REG_TEAM_NOT Clone()
        {
            return new SS2C_AUTO_MATCH_REG_TEAM_NOT(this);
        }

        /// <summary>Field number for the "result" field.</summary>
        public const int ResultFieldNumber = 1;
        private uint result_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Result
        {
            get { return result_; }
            set
            {
                result_ = value;
            }
        }

        /// <summary>Field number for the "mode" field.</summary>
        public const int ModeFieldNumber = 2;
        private uint mode_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Mode
        {
            get { return mode_; }
            set
            {
                mode_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as SS2C_AUTO_MATCH_REG_TEAM_NOT);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SS2C_AUTO_MATCH_REG_TEAM_NOT other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Result != other.Result) return false;
            if (Mode != other.Mode) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Result != 0) hash ^= Result.GetHashCode();
            if (Mode != 0) hash ^= Mode.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Result);
      }
      if (Mode != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Mode);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Result != 0)
            {
                output.WriteRawTag(8);
                output.WriteUInt32(Result);
            }
            if (Mode != 0)
            {
                output.WriteRawTag(16);
                output.WriteUInt32(Mode);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (Result != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Result);
            }
            if (Mode != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Mode);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SS2C_AUTO_MATCH_REG_TEAM_NOT other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Result != 0)
            {
                Result = other.Result;
            }
            if (other.Mode != 0)
            {
                Mode = other.Mode;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadUInt32();
            break;
          }
          case 16: {
            Mode = input.ReadUInt32();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            Result = input.ReadUInt32();
                            break;
                        }
                    case 16:
                        {
                            Mode = input.ReadUInt32();
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class SC2S_RECONNECT_INGAME_REQ : pb::IMessage<SC2S_RECONNECT_INGAME_REQ>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<SC2S_RECONNECT_INGAME_REQ> _parser = new pb::MessageParser<SC2S_RECONNECT_INGAME_REQ>(() => new SC2S_RECONNECT_INGAME_REQ());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SC2S_RECONNECT_INGAME_REQ> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::DC.Packet.InGameReflection.Descriptor.MessageTypes[5]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SC2S_RECONNECT_INGAME_REQ()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SC2S_RECONNECT_INGAME_REQ(SC2S_RECONNECT_INGAME_REQ other) : this()
        {
            isRefusal_ = other.isRefusal_;
            nickName_ = other.nickName_ != null ? other.nickName_.Clone() : null;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SC2S_RECONNECT_INGAME_REQ Clone()
        {
            return new SC2S_RECONNECT_INGAME_REQ(this);
        }

        /// <summary>Field number for the "isRefusal" field.</summary>
        public const int IsRefusalFieldNumber = 1;
        private uint isRefusal_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint IsRefusal
        {
            get { return isRefusal_; }
            set
            {
                isRefusal_ = value;
            }
        }

        /// <summary>Field number for the "nickName" field.</summary>
        public const int NickNameFieldNumber = 2;
        private global::DC.Packet.SACCOUNT_NICKNAME nickName_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public global::DC.Packet.SACCOUNT_NICKNAME NickName
        {
            get { return nickName_; }
            set
            {
                nickName_ = value;
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as SC2S_RECONNECT_INGAME_REQ);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SC2S_RECONNECT_INGAME_REQ other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (IsRefusal != other.IsRefusal) return false;
            if (!object.Equals(NickName, other.NickName)) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (IsRefusal != 0) hash ^= IsRefusal.GetHashCode();
            if (nickName_ != null) hash ^= NickName.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (IsRefusal != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(IsRefusal);
      }
      if (nickName_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(NickName);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (IsRefusal != 0)
            {
                output.WriteRawTag(8);
                output.WriteUInt32(IsRefusal);
            }
            if (nickName_ != null)
            {
                output.WriteRawTag(18);
                output.WriteMessage(NickName);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (IsRefusal != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IsRefusal);
            }
            if (nickName_ != null)
            {
                size += 1 + pb::CodedOutputStream.ComputeMessageSize(NickName);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SC2S_RECONNECT_INGAME_REQ other)
        {
            if (other == null)
            {
                return;
            }
            if (other.IsRefusal != 0)
            {
                IsRefusal = other.IsRefusal;
            }
            if (other.nickName_ != null)
            {
                if (nickName_ == null)
                {
                    NickName = new global::DC.Packet.SACCOUNT_NICKNAME();
                }
                NickName.MergeFrom(other.NickName);
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            IsRefusal = input.ReadUInt32();
            break;
          }
          case 18: {
            if (nickName_ == null) {
              NickName = new global::DC.Packet.SACCOUNT_NICKNAME();
            }
            input.ReadMessage(NickName);
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            IsRefusal = input.ReadUInt32();
                            break;
                        }
                    case 18:
                        {
                            if (nickName_ == null)
                            {
                                NickName = new global::DC.Packet.SACCOUNT_NICKNAME();
                            }
                            input.ReadMessage(NickName);
                            break;
                        }
                }
            }
        }
#endif

    }

    public sealed partial class SS2C_RECONNECT_INGAME_RES : pb::IMessage<SS2C_RECONNECT_INGAME_RES>
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        , pb::IBufferMessage
#endif
    {
        private static readonly pb::MessageParser<SS2C_RECONNECT_INGAME_RES> _parser = new pb::MessageParser<SS2C_RECONNECT_INGAME_RES>(() => new SS2C_RECONNECT_INGAME_RES());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pb::MessageParser<SS2C_RECONNECT_INGAME_RES> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public static pbr::MessageDescriptor Descriptor
        {
            get { return global::DC.Packet.InGameReflection.Descriptor.MessageTypes[6]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        pbr::MessageDescriptor pb::IMessage.Descriptor
        {
            get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_RECONNECT_INGAME_RES()
        {
            OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_RECONNECT_INGAME_RES(SS2C_RECONNECT_INGAME_RES other) : this()
        {
            result_ = other.result_;
            serviceUrl_ = other.serviceUrl_;
            _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public SS2C_RECONNECT_INGAME_RES Clone()
        {
            return new SS2C_RECONNECT_INGAME_RES(this);
        }

        /// <summary>Field number for the "result" field.</summary>
        public const int ResultFieldNumber = 1;
        private uint result_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public uint Result
        {
            get { return result_; }
            set
            {
                result_ = value;
            }
        }

        /// <summary>Field number for the "serviceUrl" field.</summary>
        public const int ServiceUrlFieldNumber = 2;
        private string serviceUrl_ = "";
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public string ServiceUrl
        {
            get { return serviceUrl_; }
            set
            {
                serviceUrl_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
            }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override bool Equals(object other)
        {
            return Equals(other as SS2C_RECONNECT_INGAME_RES);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public bool Equals(SS2C_RECONNECT_INGAME_RES other)
        {
            if (ReferenceEquals(other, null))
            {
                return false;
            }
            if (ReferenceEquals(other, this))
            {
                return true;
            }
            if (Result != other.Result) return false;
            if (ServiceUrl != other.ServiceUrl) return false;
            return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override int GetHashCode()
        {
            int hash = 1;
            if (Result != 0) hash ^= Result.GetHashCode();
            if (ServiceUrl.Length != 0) hash ^= ServiceUrl.GetHashCode();
            if (_unknownFields != null)
            {
                hash ^= _unknownFields.GetHashCode();
            }
            return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public override string ToString()
        {
            return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void WriteTo(pb::CodedOutputStream output)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            output.WriteRawMessage(this);
#else
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Result);
      }
      if (ServiceUrl.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ServiceUrl);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output)
        {
            if (Result != 0)
            {
                output.WriteRawTag(8);
                output.WriteUInt32(Result);
            }
            if (ServiceUrl.Length != 0)
            {
                output.WriteRawTag(18);
                output.WriteString(ServiceUrl);
            }
            if (_unknownFields != null)
            {
                _unknownFields.WriteTo(ref output);
            }
        }
#endif

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public int CalculateSize()
        {
            int size = 0;
            if (Result != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Result);
            }
            if (ServiceUrl.Length != 0)
            {
                size += 1 + pb::CodedOutputStream.ComputeStringSize(ServiceUrl);
            }
            if (_unknownFields != null)
            {
                size += _unknownFields.CalculateSize();
            }
            return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(SS2C_RECONNECT_INGAME_RES other)
        {
            if (other == null)
            {
                return;
            }
            if (other.Result != 0)
            {
                Result = other.Result;
            }
            if (other.ServiceUrl.Length != 0)
            {
                ServiceUrl = other.ServiceUrl;
            }
            _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        public void MergeFrom(pb::CodedInputStream input)
        {
#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
            input.ReadRawMessage(this);
#else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadUInt32();
            break;
          }
          case 18: {
            ServiceUrl = input.ReadString();
            break;
          }
        }
      }
#endif
        }

#if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
        void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input)
        {
            uint tag;
            while ((tag = input.ReadTag()) != 0)
            {
                switch (tag)
                {
                    default:
                        _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
                        break;
                    case 8:
                        {
                            Result = input.ReadUInt32();
                            break;
                        }
                    case 18:
                        {
                            ServiceUrl = input.ReadString();
                            break;
                        }
                }
            }
        }
#endif

    }

    #endregion

}

#endregion Designer generated code
