// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Karma.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DC.Packet {

  /// <summary>Holder for reflection information generated from Karma.proto</summary>
  public static partial class KarmaReflection {

    #region Descriptor
    /// <summary>File descriptor for Karma.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static KarmaReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CgtLYXJtYS5wcm90bxIJREMuUGFja2V0GhBfQ2hhcmFjdGVyLnByb3RvItEB",
            "ChVTS0FSTUFfQ0hBUkFDVEVSX0lORk8SEQoJYWNjb3VudElkGAEgASgJEhMK",
            "C2NoYXJhY3RlcklkGAIgASgJEi4KCG5pY2tOYW1lGAMgASgLMhwuREMuUGFj",
            "a2V0LlNBQ0NPVU5UX05JQ0tOQU1FEhYKDmNoYXJhY3RlckNsYXNzGAQgASgJ",
            "Eg4KBmdlbmRlchgFIAEoDRIOCgZpc1ZvdGUYBiABKA0SEwoLa2FybWFBY3Rp",
            "b24YByABKA0SEwoLa2FybWFTdGF0dXMYCCABKA0iawodU0tBUk1BX01PU1Rf",
            "UkVDRU5UX01BVENIX0lORk8SEAoIbWF0Y2hJZHgYASABKA0SOAoOY2hhcmFj",
            "dGVySW5mb3MYAiADKAsyIC5EQy5QYWNrZXQuU0tBUk1BX0NIQVJBQ1RFUl9J",
            "TkZPIhwKGlNDMlNfS0FSTUFfUkVQT1JUX0xJU1RfUkVRIscBChpTUzJDX0tB",
            "Uk1BX1JFUE9SVF9MSVNUX1JFUxI8CgptYXRjaEluZm9zGAEgAygLMiguREMu",
            "UGFja2V0LlNLQVJNQV9NT1NUX1JFQ0VOVF9NQVRDSF9JTkZPEhoKEmN1cnJl",
            "bnRUaWNrZXRDb3VudBgCIAEoDRIbChNjb2xsZWN0aW9uU3RlcENvdW50GAMg",
            "ASgNEhoKEm1heENvbGxlY3Rpb25Db3VudBgEIAEoDRIWCg5tYXhUaWNrZXRD",
            "b3VudBgFIAEoDSJoChxTQzJTX0tBUk1BX1JFUE9SVF9BQ1RJT05fUkVREhAK",
            "CG1hdGNoSWR4GAEgASgNEhEKCWFjY291bnRJZBgCIAEoCRITCgtjaGFyYWN0",
            "ZXJJZBgDIAEoCRIOCgZhY3Rpb24YBCABKA0i7AEKHFNTMkNfS0FSTUFfUkVQ",
            "T1JUX0FDVElPTl9SRVMSDgoGcmVzdWx0GAEgASgNEhAKCG1hdGNoSWR4GAIg",
            "ASgNEj0KE3VwZGF0ZUNoYXJhY3RlckluZm8YAyABKAsyIC5EQy5QYWNrZXQu",
            "U0tBUk1BX0NIQVJBQ1RFUl9JTkZPEhoKEmN1cnJlbnRUaWNrZXRDb3VudBgE",
            "IAEoDRIbChNjb2xsZWN0aW9uU3RlcENvdW50GAUgASgNEhoKEm1heENvbGxl",
            "Y3Rpb25Db3VudBgGIAEoDRIWCg5tYXhUaWNrZXRDb3VudBgHIAEoDSJhChxT",
            "UzJDX0tBUk1BX1JBVElOR19VUERBVEVfTk9UEhkKEXVwZGF0ZUthcm1hUmF0",
            "aW5nGAEgASgFEhEKCWFjY291bnRJZBgCIAEoCRITCgtjaGFyYWN0ZXJJZBgD",
            "IAEoCUIcChFjb20ucGFja2V0cy5rYXJtYUIFa2FybWFQAGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DC.Packet.CharacterReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SKARMA_CHARACTER_INFO), global::DC.Packet.SKARMA_CHARACTER_INFO.Parser, new[]{ "AccountId", "CharacterId", "NickName", "CharacterClass", "Gender", "IsVote", "KarmaAction", "KarmaStatus" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SKARMA_MOST_RECENT_MATCH_INFO), global::DC.Packet.SKARMA_MOST_RECENT_MATCH_INFO.Parser, new[]{ "MatchIdx", "CharacterInfos" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SC2S_KARMA_REPORT_LIST_REQ), global::DC.Packet.SC2S_KARMA_REPORT_LIST_REQ.Parser, null, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SS2C_KARMA_REPORT_LIST_RES), global::DC.Packet.SS2C_KARMA_REPORT_LIST_RES.Parser, new[]{ "MatchInfos", "CurrentTicketCount", "CollectionStepCount", "MaxCollectionCount", "MaxTicketCount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SC2S_KARMA_REPORT_ACTION_REQ), global::DC.Packet.SC2S_KARMA_REPORT_ACTION_REQ.Parser, new[]{ "MatchIdx", "AccountId", "CharacterId", "Action" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SS2C_KARMA_REPORT_ACTION_RES), global::DC.Packet.SS2C_KARMA_REPORT_ACTION_RES.Parser, new[]{ "Result", "MatchIdx", "UpdateCharacterInfo", "CurrentTicketCount", "CollectionStepCount", "MaxCollectionCount", "MaxTicketCount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SS2C_KARMA_RATING_UPDATE_NOT), global::DC.Packet.SS2C_KARMA_RATING_UPDATE_NOT.Parser, new[]{ "UpdateKarmaRating", "AccountId", "CharacterId" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class SKARMA_CHARACTER_INFO : pb::IMessage<SKARMA_CHARACTER_INFO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SKARMA_CHARACTER_INFO> _parser = new pb::MessageParser<SKARMA_CHARACTER_INFO>(() => new SKARMA_CHARACTER_INFO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SKARMA_CHARACTER_INFO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.KarmaReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SKARMA_CHARACTER_INFO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SKARMA_CHARACTER_INFO(SKARMA_CHARACTER_INFO other) : this() {
      accountId_ = other.accountId_;
      characterId_ = other.characterId_;
      nickName_ = other.nickName_ != null ? other.nickName_.Clone() : null;
      characterClass_ = other.characterClass_;
      gender_ = other.gender_;
      isVote_ = other.isVote_;
      karmaAction_ = other.karmaAction_;
      karmaStatus_ = other.karmaStatus_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SKARMA_CHARACTER_INFO Clone() {
      return new SKARMA_CHARACTER_INFO(this);
    }

    /// <summary>Field number for the "accountId" field.</summary>
    public const int AccountIdFieldNumber = 1;
    private string accountId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccountId {
      get { return accountId_; }
      set {
        accountId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "characterId" field.</summary>
    public const int CharacterIdFieldNumber = 2;
    private string characterId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CharacterId {
      get { return characterId_; }
      set {
        characterId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nickName" field.</summary>
    public const int NickNameFieldNumber = 3;
    private global::DC.Packet.SACCOUNT_NICKNAME nickName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DC.Packet.SACCOUNT_NICKNAME NickName {
      get { return nickName_; }
      set {
        nickName_ = value;
      }
    }

    /// <summary>Field number for the "characterClass" field.</summary>
    public const int CharacterClassFieldNumber = 4;
    private string characterClass_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CharacterClass {
      get { return characterClass_; }
      set {
        characterClass_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 5;
    private uint gender_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Gender {
      get { return gender_; }
      set {
        gender_ = value;
      }
    }

    /// <summary>Field number for the "isVote" field.</summary>
    public const int IsVoteFieldNumber = 6;
    private uint isVote_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint IsVote {
      get { return isVote_; }
      set {
        isVote_ = value;
      }
    }

    /// <summary>Field number for the "karmaAction" field.</summary>
    public const int KarmaActionFieldNumber = 7;
    private uint karmaAction_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint KarmaAction {
      get { return karmaAction_; }
      set {
        karmaAction_ = value;
      }
    }

    /// <summary>Field number for the "karmaStatus" field.</summary>
    public const int KarmaStatusFieldNumber = 8;
    private uint karmaStatus_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint KarmaStatus {
      get { return karmaStatus_; }
      set {
        karmaStatus_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SKARMA_CHARACTER_INFO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SKARMA_CHARACTER_INFO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AccountId != other.AccountId) return false;
      if (CharacterId != other.CharacterId) return false;
      if (!object.Equals(NickName, other.NickName)) return false;
      if (CharacterClass != other.CharacterClass) return false;
      if (Gender != other.Gender) return false;
      if (IsVote != other.IsVote) return false;
      if (KarmaAction != other.KarmaAction) return false;
      if (KarmaStatus != other.KarmaStatus) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (AccountId.Length != 0) hash ^= AccountId.GetHashCode();
      if (CharacterId.Length != 0) hash ^= CharacterId.GetHashCode();
      if (nickName_ != null) hash ^= NickName.GetHashCode();
      if (CharacterClass.Length != 0) hash ^= CharacterClass.GetHashCode();
      if (Gender != 0) hash ^= Gender.GetHashCode();
      if (IsVote != 0) hash ^= IsVote.GetHashCode();
      if (KarmaAction != 0) hash ^= KarmaAction.GetHashCode();
      if (KarmaStatus != 0) hash ^= KarmaStatus.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (AccountId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AccountId);
      }
      if (CharacterId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CharacterId);
      }
      if (nickName_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(NickName);
      }
      if (CharacterClass.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CharacterClass);
      }
      if (Gender != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Gender);
      }
      if (IsVote != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(IsVote);
      }
      if (KarmaAction != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(KarmaAction);
      }
      if (KarmaStatus != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(KarmaStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (AccountId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(AccountId);
      }
      if (CharacterId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(CharacterId);
      }
      if (nickName_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(NickName);
      }
      if (CharacterClass.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CharacterClass);
      }
      if (Gender != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Gender);
      }
      if (IsVote != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(IsVote);
      }
      if (KarmaAction != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(KarmaAction);
      }
      if (KarmaStatus != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(KarmaStatus);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (AccountId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountId);
      }
      if (CharacterId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharacterId);
      }
      if (nickName_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NickName);
      }
      if (CharacterClass.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharacterClass);
      }
      if (Gender != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Gender);
      }
      if (IsVote != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(IsVote);
      }
      if (KarmaAction != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(KarmaAction);
      }
      if (KarmaStatus != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(KarmaStatus);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SKARMA_CHARACTER_INFO other) {
      if (other == null) {
        return;
      }
      if (other.AccountId.Length != 0) {
        AccountId = other.AccountId;
      }
      if (other.CharacterId.Length != 0) {
        CharacterId = other.CharacterId;
      }
      if (other.nickName_ != null) {
        if (nickName_ == null) {
          NickName = new global::DC.Packet.SACCOUNT_NICKNAME();
        }
        NickName.MergeFrom(other.NickName);
      }
      if (other.CharacterClass.Length != 0) {
        CharacterClass = other.CharacterClass;
      }
      if (other.Gender != 0) {
        Gender = other.Gender;
      }
      if (other.IsVote != 0) {
        IsVote = other.IsVote;
      }
      if (other.KarmaAction != 0) {
        KarmaAction = other.KarmaAction;
      }
      if (other.KarmaStatus != 0) {
        KarmaStatus = other.KarmaStatus;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            AccountId = input.ReadString();
            break;
          }
          case 18: {
            CharacterId = input.ReadString();
            break;
          }
          case 26: {
            if (nickName_ == null) {
              NickName = new global::DC.Packet.SACCOUNT_NICKNAME();
            }
            input.ReadMessage(NickName);
            break;
          }
          case 34: {
            CharacterClass = input.ReadString();
            break;
          }
          case 40: {
            Gender = input.ReadUInt32();
            break;
          }
          case 48: {
            IsVote = input.ReadUInt32();
            break;
          }
          case 56: {
            KarmaAction = input.ReadUInt32();
            break;
          }
          case 64: {
            KarmaStatus = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            AccountId = input.ReadString();
            break;
          }
          case 18: {
            CharacterId = input.ReadString();
            break;
          }
          case 26: {
            if (nickName_ == null) {
              NickName = new global::DC.Packet.SACCOUNT_NICKNAME();
            }
            input.ReadMessage(NickName);
            break;
          }
          case 34: {
            CharacterClass = input.ReadString();
            break;
          }
          case 40: {
            Gender = input.ReadUInt32();
            break;
          }
          case 48: {
            IsVote = input.ReadUInt32();
            break;
          }
          case 56: {
            KarmaAction = input.ReadUInt32();
            break;
          }
          case 64: {
            KarmaStatus = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SKARMA_MOST_RECENT_MATCH_INFO : pb::IMessage<SKARMA_MOST_RECENT_MATCH_INFO>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SKARMA_MOST_RECENT_MATCH_INFO> _parser = new pb::MessageParser<SKARMA_MOST_RECENT_MATCH_INFO>(() => new SKARMA_MOST_RECENT_MATCH_INFO());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SKARMA_MOST_RECENT_MATCH_INFO> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.KarmaReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SKARMA_MOST_RECENT_MATCH_INFO() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SKARMA_MOST_RECENT_MATCH_INFO(SKARMA_MOST_RECENT_MATCH_INFO other) : this() {
      matchIdx_ = other.matchIdx_;
      characterInfos_ = other.characterInfos_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SKARMA_MOST_RECENT_MATCH_INFO Clone() {
      return new SKARMA_MOST_RECENT_MATCH_INFO(this);
    }

    /// <summary>Field number for the "matchIdx" field.</summary>
    public const int MatchIdxFieldNumber = 1;
    private uint matchIdx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MatchIdx {
      get { return matchIdx_; }
      set {
        matchIdx_ = value;
      }
    }

    /// <summary>Field number for the "characterInfos" field.</summary>
    public const int CharacterInfosFieldNumber = 2;
    private static readonly pb::FieldCodec<global::DC.Packet.SKARMA_CHARACTER_INFO> _repeated_characterInfos_codec
        = pb::FieldCodec.ForMessage(18, global::DC.Packet.SKARMA_CHARACTER_INFO.Parser);
    private readonly pbc::RepeatedField<global::DC.Packet.SKARMA_CHARACTER_INFO> characterInfos_ = new pbc::RepeatedField<global::DC.Packet.SKARMA_CHARACTER_INFO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::DC.Packet.SKARMA_CHARACTER_INFO> CharacterInfos {
      get { return characterInfos_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SKARMA_MOST_RECENT_MATCH_INFO);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SKARMA_MOST_RECENT_MATCH_INFO other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MatchIdx != other.MatchIdx) return false;
      if(!characterInfos_.Equals(other.characterInfos_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MatchIdx != 0) hash ^= MatchIdx.GetHashCode();
      hash ^= characterInfos_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MatchIdx != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MatchIdx);
      }
      characterInfos_.WriteTo(output, _repeated_characterInfos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MatchIdx != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MatchIdx);
      }
      characterInfos_.WriteTo(ref output, _repeated_characterInfos_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MatchIdx != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MatchIdx);
      }
      size += characterInfos_.CalculateSize(_repeated_characterInfos_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SKARMA_MOST_RECENT_MATCH_INFO other) {
      if (other == null) {
        return;
      }
      if (other.MatchIdx != 0) {
        MatchIdx = other.MatchIdx;
      }
      characterInfos_.Add(other.characterInfos_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MatchIdx = input.ReadUInt32();
            break;
          }
          case 18: {
            characterInfos_.AddEntriesFrom(input, _repeated_characterInfos_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MatchIdx = input.ReadUInt32();
            break;
          }
          case 18: {
            characterInfos_.AddEntriesFrom(ref input, _repeated_characterInfos_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SC2S_KARMA_REPORT_LIST_REQ : pb::IMessage<SC2S_KARMA_REPORT_LIST_REQ>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SC2S_KARMA_REPORT_LIST_REQ> _parser = new pb::MessageParser<SC2S_KARMA_REPORT_LIST_REQ>(() => new SC2S_KARMA_REPORT_LIST_REQ());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SC2S_KARMA_REPORT_LIST_REQ> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.KarmaReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_KARMA_REPORT_LIST_REQ() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_KARMA_REPORT_LIST_REQ(SC2S_KARMA_REPORT_LIST_REQ other) : this() {
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_KARMA_REPORT_LIST_REQ Clone() {
      return new SC2S_KARMA_REPORT_LIST_REQ(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SC2S_KARMA_REPORT_LIST_REQ);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SC2S_KARMA_REPORT_LIST_REQ other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SC2S_KARMA_REPORT_LIST_REQ other) {
      if (other == null) {
        return;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
        }
      }
    }
    #endif

  }

  public sealed partial class SS2C_KARMA_REPORT_LIST_RES : pb::IMessage<SS2C_KARMA_REPORT_LIST_RES>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SS2C_KARMA_REPORT_LIST_RES> _parser = new pb::MessageParser<SS2C_KARMA_REPORT_LIST_RES>(() => new SS2C_KARMA_REPORT_LIST_RES());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SS2C_KARMA_REPORT_LIST_RES> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.KarmaReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_KARMA_REPORT_LIST_RES() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_KARMA_REPORT_LIST_RES(SS2C_KARMA_REPORT_LIST_RES other) : this() {
      matchInfos_ = other.matchInfos_.Clone();
      currentTicketCount_ = other.currentTicketCount_;
      collectionStepCount_ = other.collectionStepCount_;
      maxCollectionCount_ = other.maxCollectionCount_;
      maxTicketCount_ = other.maxTicketCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_KARMA_REPORT_LIST_RES Clone() {
      return new SS2C_KARMA_REPORT_LIST_RES(this);
    }

    /// <summary>Field number for the "matchInfos" field.</summary>
    public const int MatchInfosFieldNumber = 1;
    private static readonly pb::FieldCodec<global::DC.Packet.SKARMA_MOST_RECENT_MATCH_INFO> _repeated_matchInfos_codec
        = pb::FieldCodec.ForMessage(10, global::DC.Packet.SKARMA_MOST_RECENT_MATCH_INFO.Parser);
    private readonly pbc::RepeatedField<global::DC.Packet.SKARMA_MOST_RECENT_MATCH_INFO> matchInfos_ = new pbc::RepeatedField<global::DC.Packet.SKARMA_MOST_RECENT_MATCH_INFO>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::DC.Packet.SKARMA_MOST_RECENT_MATCH_INFO> MatchInfos {
      get { return matchInfos_; }
    }

    /// <summary>Field number for the "currentTicketCount" field.</summary>
    public const int CurrentTicketCountFieldNumber = 2;
    private uint currentTicketCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CurrentTicketCount {
      get { return currentTicketCount_; }
      set {
        currentTicketCount_ = value;
      }
    }

    /// <summary>Field number for the "collectionStepCount" field.</summary>
    public const int CollectionStepCountFieldNumber = 3;
    private uint collectionStepCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CollectionStepCount {
      get { return collectionStepCount_; }
      set {
        collectionStepCount_ = value;
      }
    }

    /// <summary>Field number for the "maxCollectionCount" field.</summary>
    public const int MaxCollectionCountFieldNumber = 4;
    private uint maxCollectionCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MaxCollectionCount {
      get { return maxCollectionCount_; }
      set {
        maxCollectionCount_ = value;
      }
    }

    /// <summary>Field number for the "maxTicketCount" field.</summary>
    public const int MaxTicketCountFieldNumber = 5;
    private uint maxTicketCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MaxTicketCount {
      get { return maxTicketCount_; }
      set {
        maxTicketCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SS2C_KARMA_REPORT_LIST_RES);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SS2C_KARMA_REPORT_LIST_RES other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!matchInfos_.Equals(other.matchInfos_)) return false;
      if (CurrentTicketCount != other.CurrentTicketCount) return false;
      if (CollectionStepCount != other.CollectionStepCount) return false;
      if (MaxCollectionCount != other.MaxCollectionCount) return false;
      if (MaxTicketCount != other.MaxTicketCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= matchInfos_.GetHashCode();
      if (CurrentTicketCount != 0) hash ^= CurrentTicketCount.GetHashCode();
      if (CollectionStepCount != 0) hash ^= CollectionStepCount.GetHashCode();
      if (MaxCollectionCount != 0) hash ^= MaxCollectionCount.GetHashCode();
      if (MaxTicketCount != 0) hash ^= MaxTicketCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      matchInfos_.WriteTo(output, _repeated_matchInfos_codec);
      if (CurrentTicketCount != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(CurrentTicketCount);
      }
      if (CollectionStepCount != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(CollectionStepCount);
      }
      if (MaxCollectionCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(MaxCollectionCount);
      }
      if (MaxTicketCount != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(MaxTicketCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      matchInfos_.WriteTo(ref output, _repeated_matchInfos_codec);
      if (CurrentTicketCount != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(CurrentTicketCount);
      }
      if (CollectionStepCount != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(CollectionStepCount);
      }
      if (MaxCollectionCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(MaxCollectionCount);
      }
      if (MaxTicketCount != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(MaxTicketCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += matchInfos_.CalculateSize(_repeated_matchInfos_codec);
      if (CurrentTicketCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CurrentTicketCount);
      }
      if (CollectionStepCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CollectionStepCount);
      }
      if (MaxCollectionCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MaxCollectionCount);
      }
      if (MaxTicketCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MaxTicketCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SS2C_KARMA_REPORT_LIST_RES other) {
      if (other == null) {
        return;
      }
      matchInfos_.Add(other.matchInfos_);
      if (other.CurrentTicketCount != 0) {
        CurrentTicketCount = other.CurrentTicketCount;
      }
      if (other.CollectionStepCount != 0) {
        CollectionStepCount = other.CollectionStepCount;
      }
      if (other.MaxCollectionCount != 0) {
        MaxCollectionCount = other.MaxCollectionCount;
      }
      if (other.MaxTicketCount != 0) {
        MaxTicketCount = other.MaxTicketCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            matchInfos_.AddEntriesFrom(input, _repeated_matchInfos_codec);
            break;
          }
          case 16: {
            CurrentTicketCount = input.ReadUInt32();
            break;
          }
          case 24: {
            CollectionStepCount = input.ReadUInt32();
            break;
          }
          case 32: {
            MaxCollectionCount = input.ReadUInt32();
            break;
          }
          case 40: {
            MaxTicketCount = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            matchInfos_.AddEntriesFrom(ref input, _repeated_matchInfos_codec);
            break;
          }
          case 16: {
            CurrentTicketCount = input.ReadUInt32();
            break;
          }
          case 24: {
            CollectionStepCount = input.ReadUInt32();
            break;
          }
          case 32: {
            MaxCollectionCount = input.ReadUInt32();
            break;
          }
          case 40: {
            MaxTicketCount = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SC2S_KARMA_REPORT_ACTION_REQ : pb::IMessage<SC2S_KARMA_REPORT_ACTION_REQ>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SC2S_KARMA_REPORT_ACTION_REQ> _parser = new pb::MessageParser<SC2S_KARMA_REPORT_ACTION_REQ>(() => new SC2S_KARMA_REPORT_ACTION_REQ());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SC2S_KARMA_REPORT_ACTION_REQ> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.KarmaReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_KARMA_REPORT_ACTION_REQ() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_KARMA_REPORT_ACTION_REQ(SC2S_KARMA_REPORT_ACTION_REQ other) : this() {
      matchIdx_ = other.matchIdx_;
      accountId_ = other.accountId_;
      characterId_ = other.characterId_;
      action_ = other.action_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_KARMA_REPORT_ACTION_REQ Clone() {
      return new SC2S_KARMA_REPORT_ACTION_REQ(this);
    }

    /// <summary>Field number for the "matchIdx" field.</summary>
    public const int MatchIdxFieldNumber = 1;
    private uint matchIdx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MatchIdx {
      get { return matchIdx_; }
      set {
        matchIdx_ = value;
      }
    }

    /// <summary>Field number for the "accountId" field.</summary>
    public const int AccountIdFieldNumber = 2;
    private string accountId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccountId {
      get { return accountId_; }
      set {
        accountId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "characterId" field.</summary>
    public const int CharacterIdFieldNumber = 3;
    private string characterId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CharacterId {
      get { return characterId_; }
      set {
        characterId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "action" field.</summary>
    public const int ActionFieldNumber = 4;
    private uint action_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Action {
      get { return action_; }
      set {
        action_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SC2S_KARMA_REPORT_ACTION_REQ);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SC2S_KARMA_REPORT_ACTION_REQ other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MatchIdx != other.MatchIdx) return false;
      if (AccountId != other.AccountId) return false;
      if (CharacterId != other.CharacterId) return false;
      if (Action != other.Action) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (MatchIdx != 0) hash ^= MatchIdx.GetHashCode();
      if (AccountId.Length != 0) hash ^= AccountId.GetHashCode();
      if (CharacterId.Length != 0) hash ^= CharacterId.GetHashCode();
      if (Action != 0) hash ^= Action.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (MatchIdx != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MatchIdx);
      }
      if (AccountId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AccountId);
      }
      if (CharacterId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CharacterId);
      }
      if (Action != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Action);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (MatchIdx != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(MatchIdx);
      }
      if (AccountId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AccountId);
      }
      if (CharacterId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CharacterId);
      }
      if (Action != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Action);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (MatchIdx != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MatchIdx);
      }
      if (AccountId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountId);
      }
      if (CharacterId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharacterId);
      }
      if (Action != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Action);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SC2S_KARMA_REPORT_ACTION_REQ other) {
      if (other == null) {
        return;
      }
      if (other.MatchIdx != 0) {
        MatchIdx = other.MatchIdx;
      }
      if (other.AccountId.Length != 0) {
        AccountId = other.AccountId;
      }
      if (other.CharacterId.Length != 0) {
        CharacterId = other.CharacterId;
      }
      if (other.Action != 0) {
        Action = other.Action;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            MatchIdx = input.ReadUInt32();
            break;
          }
          case 18: {
            AccountId = input.ReadString();
            break;
          }
          case 26: {
            CharacterId = input.ReadString();
            break;
          }
          case 32: {
            Action = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            MatchIdx = input.ReadUInt32();
            break;
          }
          case 18: {
            AccountId = input.ReadString();
            break;
          }
          case 26: {
            CharacterId = input.ReadString();
            break;
          }
          case 32: {
            Action = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SS2C_KARMA_REPORT_ACTION_RES : pb::IMessage<SS2C_KARMA_REPORT_ACTION_RES>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SS2C_KARMA_REPORT_ACTION_RES> _parser = new pb::MessageParser<SS2C_KARMA_REPORT_ACTION_RES>(() => new SS2C_KARMA_REPORT_ACTION_RES());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SS2C_KARMA_REPORT_ACTION_RES> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.KarmaReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_KARMA_REPORT_ACTION_RES() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_KARMA_REPORT_ACTION_RES(SS2C_KARMA_REPORT_ACTION_RES other) : this() {
      result_ = other.result_;
      matchIdx_ = other.matchIdx_;
      updateCharacterInfo_ = other.updateCharacterInfo_ != null ? other.updateCharacterInfo_.Clone() : null;
      currentTicketCount_ = other.currentTicketCount_;
      collectionStepCount_ = other.collectionStepCount_;
      maxCollectionCount_ = other.maxCollectionCount_;
      maxTicketCount_ = other.maxTicketCount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_KARMA_REPORT_ACTION_RES Clone() {
      return new SS2C_KARMA_REPORT_ACTION_RES(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private uint result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "matchIdx" field.</summary>
    public const int MatchIdxFieldNumber = 2;
    private uint matchIdx_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MatchIdx {
      get { return matchIdx_; }
      set {
        matchIdx_ = value;
      }
    }

    /// <summary>Field number for the "updateCharacterInfo" field.</summary>
    public const int UpdateCharacterInfoFieldNumber = 3;
    private global::DC.Packet.SKARMA_CHARACTER_INFO updateCharacterInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DC.Packet.SKARMA_CHARACTER_INFO UpdateCharacterInfo {
      get { return updateCharacterInfo_; }
      set {
        updateCharacterInfo_ = value;
      }
    }

    /// <summary>Field number for the "currentTicketCount" field.</summary>
    public const int CurrentTicketCountFieldNumber = 4;
    private uint currentTicketCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CurrentTicketCount {
      get { return currentTicketCount_; }
      set {
        currentTicketCount_ = value;
      }
    }

    /// <summary>Field number for the "collectionStepCount" field.</summary>
    public const int CollectionStepCountFieldNumber = 5;
    private uint collectionStepCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint CollectionStepCount {
      get { return collectionStepCount_; }
      set {
        collectionStepCount_ = value;
      }
    }

    /// <summary>Field number for the "maxCollectionCount" field.</summary>
    public const int MaxCollectionCountFieldNumber = 6;
    private uint maxCollectionCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MaxCollectionCount {
      get { return maxCollectionCount_; }
      set {
        maxCollectionCount_ = value;
      }
    }

    /// <summary>Field number for the "maxTicketCount" field.</summary>
    public const int MaxTicketCountFieldNumber = 7;
    private uint maxTicketCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint MaxTicketCount {
      get { return maxTicketCount_; }
      set {
        maxTicketCount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SS2C_KARMA_REPORT_ACTION_RES);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SS2C_KARMA_REPORT_ACTION_RES other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (MatchIdx != other.MatchIdx) return false;
      if (!object.Equals(UpdateCharacterInfo, other.UpdateCharacterInfo)) return false;
      if (CurrentTicketCount != other.CurrentTicketCount) return false;
      if (CollectionStepCount != other.CollectionStepCount) return false;
      if (MaxCollectionCount != other.MaxCollectionCount) return false;
      if (MaxTicketCount != other.MaxTicketCount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (MatchIdx != 0) hash ^= MatchIdx.GetHashCode();
      if (updateCharacterInfo_ != null) hash ^= UpdateCharacterInfo.GetHashCode();
      if (CurrentTicketCount != 0) hash ^= CurrentTicketCount.GetHashCode();
      if (CollectionStepCount != 0) hash ^= CollectionStepCount.GetHashCode();
      if (MaxCollectionCount != 0) hash ^= MaxCollectionCount.GetHashCode();
      if (MaxTicketCount != 0) hash ^= MaxTicketCount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Result);
      }
      if (MatchIdx != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(MatchIdx);
      }
      if (updateCharacterInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(UpdateCharacterInfo);
      }
      if (CurrentTicketCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(CurrentTicketCount);
      }
      if (CollectionStepCount != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(CollectionStepCount);
      }
      if (MaxCollectionCount != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(MaxCollectionCount);
      }
      if (MaxTicketCount != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(MaxTicketCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Result);
      }
      if (MatchIdx != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(MatchIdx);
      }
      if (updateCharacterInfo_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(UpdateCharacterInfo);
      }
      if (CurrentTicketCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(CurrentTicketCount);
      }
      if (CollectionStepCount != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(CollectionStepCount);
      }
      if (MaxCollectionCount != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(MaxCollectionCount);
      }
      if (MaxTicketCount != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(MaxTicketCount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Result);
      }
      if (MatchIdx != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MatchIdx);
      }
      if (updateCharacterInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(UpdateCharacterInfo);
      }
      if (CurrentTicketCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CurrentTicketCount);
      }
      if (CollectionStepCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(CollectionStepCount);
      }
      if (MaxCollectionCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MaxCollectionCount);
      }
      if (MaxTicketCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(MaxTicketCount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SS2C_KARMA_REPORT_ACTION_RES other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.MatchIdx != 0) {
        MatchIdx = other.MatchIdx;
      }
      if (other.updateCharacterInfo_ != null) {
        if (updateCharacterInfo_ == null) {
          UpdateCharacterInfo = new global::DC.Packet.SKARMA_CHARACTER_INFO();
        }
        UpdateCharacterInfo.MergeFrom(other.UpdateCharacterInfo);
      }
      if (other.CurrentTicketCount != 0) {
        CurrentTicketCount = other.CurrentTicketCount;
      }
      if (other.CollectionStepCount != 0) {
        CollectionStepCount = other.CollectionStepCount;
      }
      if (other.MaxCollectionCount != 0) {
        MaxCollectionCount = other.MaxCollectionCount;
      }
      if (other.MaxTicketCount != 0) {
        MaxTicketCount = other.MaxTicketCount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadUInt32();
            break;
          }
          case 16: {
            MatchIdx = input.ReadUInt32();
            break;
          }
          case 26: {
            if (updateCharacterInfo_ == null) {
              UpdateCharacterInfo = new global::DC.Packet.SKARMA_CHARACTER_INFO();
            }
            input.ReadMessage(UpdateCharacterInfo);
            break;
          }
          case 32: {
            CurrentTicketCount = input.ReadUInt32();
            break;
          }
          case 40: {
            CollectionStepCount = input.ReadUInt32();
            break;
          }
          case 48: {
            MaxCollectionCount = input.ReadUInt32();
            break;
          }
          case 56: {
            MaxTicketCount = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = input.ReadUInt32();
            break;
          }
          case 16: {
            MatchIdx = input.ReadUInt32();
            break;
          }
          case 26: {
            if (updateCharacterInfo_ == null) {
              UpdateCharacterInfo = new global::DC.Packet.SKARMA_CHARACTER_INFO();
            }
            input.ReadMessage(UpdateCharacterInfo);
            break;
          }
          case 32: {
            CurrentTicketCount = input.ReadUInt32();
            break;
          }
          case 40: {
            CollectionStepCount = input.ReadUInt32();
            break;
          }
          case 48: {
            MaxCollectionCount = input.ReadUInt32();
            break;
          }
          case 56: {
            MaxTicketCount = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SS2C_KARMA_RATING_UPDATE_NOT : pb::IMessage<SS2C_KARMA_RATING_UPDATE_NOT>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SS2C_KARMA_RATING_UPDATE_NOT> _parser = new pb::MessageParser<SS2C_KARMA_RATING_UPDATE_NOT>(() => new SS2C_KARMA_RATING_UPDATE_NOT());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SS2C_KARMA_RATING_UPDATE_NOT> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.KarmaReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_KARMA_RATING_UPDATE_NOT() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_KARMA_RATING_UPDATE_NOT(SS2C_KARMA_RATING_UPDATE_NOT other) : this() {
      updateKarmaRating_ = other.updateKarmaRating_;
      accountId_ = other.accountId_;
      characterId_ = other.characterId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_KARMA_RATING_UPDATE_NOT Clone() {
      return new SS2C_KARMA_RATING_UPDATE_NOT(this);
    }

    /// <summary>Field number for the "updateKarmaRating" field.</summary>
    public const int UpdateKarmaRatingFieldNumber = 1;
    private int updateKarmaRating_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int UpdateKarmaRating {
      get { return updateKarmaRating_; }
      set {
        updateKarmaRating_ = value;
      }
    }

    /// <summary>Field number for the "accountId" field.</summary>
    public const int AccountIdFieldNumber = 2;
    private string accountId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccountId {
      get { return accountId_; }
      set {
        accountId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "characterId" field.</summary>
    public const int CharacterIdFieldNumber = 3;
    private string characterId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CharacterId {
      get { return characterId_; }
      set {
        characterId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SS2C_KARMA_RATING_UPDATE_NOT);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SS2C_KARMA_RATING_UPDATE_NOT other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (UpdateKarmaRating != other.UpdateKarmaRating) return false;
      if (AccountId != other.AccountId) return false;
      if (CharacterId != other.CharacterId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (UpdateKarmaRating != 0) hash ^= UpdateKarmaRating.GetHashCode();
      if (AccountId.Length != 0) hash ^= AccountId.GetHashCode();
      if (CharacterId.Length != 0) hash ^= CharacterId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (UpdateKarmaRating != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UpdateKarmaRating);
      }
      if (AccountId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AccountId);
      }
      if (CharacterId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CharacterId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (UpdateKarmaRating != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(UpdateKarmaRating);
      }
      if (AccountId.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(AccountId);
      }
      if (CharacterId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CharacterId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (UpdateKarmaRating != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(UpdateKarmaRating);
      }
      if (AccountId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountId);
      }
      if (CharacterId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharacterId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SS2C_KARMA_RATING_UPDATE_NOT other) {
      if (other == null) {
        return;
      }
      if (other.UpdateKarmaRating != 0) {
        UpdateKarmaRating = other.UpdateKarmaRating;
      }
      if (other.AccountId.Length != 0) {
        AccountId = other.AccountId;
      }
      if (other.CharacterId.Length != 0) {
        CharacterId = other.CharacterId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            UpdateKarmaRating = input.ReadInt32();
            break;
          }
          case 18: {
            AccountId = input.ReadString();
            break;
          }
          case 26: {
            CharacterId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            UpdateKarmaRating = input.ReadInt32();
            break;
          }
          case 18: {
            AccountId = input.ReadString();
            break;
          }
          case 26: {
            CharacterId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
