// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Ranking.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace DC.Packet {

  /// <summary>Holder for reflection information generated from Ranking.proto</summary>
  public static partial class RankingReflection {

    #region Descriptor
    /// <summary>File descriptor for Ranking.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static RankingReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1SYW5raW5nLnByb3RvEglEQy5QYWNrZXQaEF9DaGFyYWN0ZXIucHJvdG8i",
            "rAEKC1NSYW5rUmVjb3JkEhEKCXBhZ2VJbmRleBgBIAEoDRIMCgRyYW5rGAIg",
            "ASgNEg0KBXNjb3JlGAMgASgNEhIKCnBlcmNlbnRhZ2UYBCABKAISEQoJYWNj",
            "b3VudElkGAUgASgJEi4KCG5pY2tOYW1lGAYgASgLMhwuREMuUGFja2V0LlNB",
            "Q0NPVU5UX05JQ0tOQU1FEhYKDmNoYXJhY3RlckNsYXNzGAcgASgJImgKFlND",
            "MlNfUkFOS0lOR19SQU5HRV9SRVESEAoIcmFua1R5cGUYASABKA0SEgoKc3Rh",
            "cnRJbmRleBgCIAEoDRIQCghlbmRJbmRleBgDIAEoDRIWCg5jaGFyYWN0ZXJD",
            "bGFzcxgEIAEoCSK2AQoWU1MyQ19SQU5LSU5HX1JBTkdFX1JFUxIOCgZyZXN1",
            "bHQYASABKA0SJwoHcmVjb3JkcxgCIAMoCzIWLkRDLlBhY2tldC5TUmFua1Jl",
            "Y29yZBIQCghyYW5rVHlwZRgDIAEoDRITCgthbGxSb3dDb3VudBgEIAEoDRIS",
            "CgpzdGFydEluZGV4GAUgASgNEhAKCGVuZEluZGV4GAYgASgNEhYKDmNoYXJh",
            "Y3RlckNsYXNzGAcgASgJIm0KF1NDMlNfUkFOS0lOR19ORUFSQllfUkVREhAK",
            "CHJhbmtUeXBlGAEgASgNEhMKC3NlYXJjaFJhbmdlGAIgASgNEhMKC3NlYXJj",
            "aEluZGV4GAMgASgNEhYKDmNoYXJhY3RlckNsYXNzGAQgASgJIqYBChdTUzJD",
            "X1JBTktJTkdfTkVBUkJZX1JFUxIOCgZyZXN1bHQYASABKA0SJwoHcmVjb3Jk",
            "cxgCIAMoCzIWLkRDLlBhY2tldC5TUmFua1JlY29yZBIQCghyYW5rVHlwZRgD",
            "IAEoDRITCgthbGxSb3dDb3VudBgEIAEoDRITCgtzZWFyY2hSYW5nZRgFIAEo",
            "DRIWCg5jaGFyYWN0ZXJDbGFzcxgGIAEoCSJ2ChpTQzJTX1JBTktJTkdfQ0hB",
            "UkFDVEVSX1JFURIQCghyYW5rVHlwZRgBIAEoDRIuCghuaWNrTmFtZRgCIAEo",
            "CzIcLkRDLlBhY2tldC5TQUNDT1VOVF9OSUNLTkFNRRIWCg5jaGFyYWN0ZXJD",
            "bGFzcxgDIAEoCSKXAQoaU1MyQ19SQU5LSU5HX0NIQVJBQ1RFUl9SRVMSDgoG",
            "cmVzdWx0GAEgASgNEioKCnJhbmtSZWNvcmQYAiABKAsyFi5EQy5QYWNrZXQu",
            "U1JhbmtSZWNvcmQSEAoIcmFua1R5cGUYAyABKA0SEwoLYWxsUm93Q291bnQY",
            "BCABKA0SFgoOY2hhcmFjdGVyQ2xhc3MYBSABKAkqcgoMUkFOS0lOR19UWVBF",
            "EggKBE5PTkUQABIICgRDT0lOEAESCAoES0lMTBACEgoKBkVTQ0FQRRADEg0K",
            "CUFEVkVOVFVSRRAEEhEKDUJPU1NLSUxMX0xJQ0gQBRIWChJCT1NTS0lMTF9H",
            "SE9TVEtJTkcQBkIgChNjb20ucGFja2V0cy5yYW5raW5nQgdyYW5raW5nUABi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::DC.Packet.CharacterReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::DC.Packet.RANKING_TYPE), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SRankRecord), global::DC.Packet.SRankRecord.Parser, new[]{ "PageIndex", "Rank", "Score", "Percentage", "AccountId", "NickName", "CharacterClass" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SC2S_RANKING_RANGE_REQ), global::DC.Packet.SC2S_RANKING_RANGE_REQ.Parser, new[]{ "RankType", "StartIndex", "EndIndex", "CharacterClass" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SS2C_RANKING_RANGE_RES), global::DC.Packet.SS2C_RANKING_RANGE_RES.Parser, new[]{ "Result", "Records", "RankType", "AllRowCount", "StartIndex", "EndIndex", "CharacterClass" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SC2S_RANKING_NEARBY_REQ), global::DC.Packet.SC2S_RANKING_NEARBY_REQ.Parser, new[]{ "RankType", "SearchRange", "SearchIndex", "CharacterClass" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SS2C_RANKING_NEARBY_RES), global::DC.Packet.SS2C_RANKING_NEARBY_RES.Parser, new[]{ "Result", "Records", "RankType", "AllRowCount", "SearchRange", "CharacterClass" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SC2S_RANKING_CHARACTER_REQ), global::DC.Packet.SC2S_RANKING_CHARACTER_REQ.Parser, new[]{ "RankType", "NickName", "CharacterClass" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::DC.Packet.SS2C_RANKING_CHARACTER_RES), global::DC.Packet.SS2C_RANKING_CHARACTER_RES.Parser, new[]{ "Result", "RankRecord", "RankType", "AllRowCount", "CharacterClass" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum RANKING_TYPE {
    [pbr::OriginalName("NONE")] None = 0,
    [pbr::OriginalName("COIN")] Coin = 1,
    [pbr::OriginalName("KILL")] Kill = 2,
    [pbr::OriginalName("ESCAPE")] Escape = 3,
    [pbr::OriginalName("ADVENTURE")] Adventure = 4,
    [pbr::OriginalName("BOSSKILL_LICH")] BosskillLich = 5,
    [pbr::OriginalName("BOSSKILL_GHOSTKING")] BosskillGhostking = 6,
  }

  #endregion

  #region Messages
  public sealed partial class SRankRecord : pb::IMessage<SRankRecord>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SRankRecord> _parser = new pb::MessageParser<SRankRecord>(() => new SRankRecord());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SRankRecord> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.RankingReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SRankRecord() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SRankRecord(SRankRecord other) : this() {
      pageIndex_ = other.pageIndex_;
      rank_ = other.rank_;
      score_ = other.score_;
      percentage_ = other.percentage_;
      accountId_ = other.accountId_;
      nickName_ = other.nickName_ != null ? other.nickName_.Clone() : null;
      characterClass_ = other.characterClass_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SRankRecord Clone() {
      return new SRankRecord(this);
    }

    /// <summary>Field number for the "pageIndex" field.</summary>
    public const int PageIndexFieldNumber = 1;
    private uint pageIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint PageIndex {
      get { return pageIndex_; }
      set {
        pageIndex_ = value;
      }
    }

    /// <summary>Field number for the "rank" field.</summary>
    public const int RankFieldNumber = 2;
    private uint rank_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Rank {
      get { return rank_; }
      set {
        rank_ = value;
      }
    }

    /// <summary>Field number for the "score" field.</summary>
    public const int ScoreFieldNumber = 3;
    private uint score_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Score {
      get { return score_; }
      set {
        score_ = value;
      }
    }

    /// <summary>Field number for the "percentage" field.</summary>
    public const int PercentageFieldNumber = 4;
    private float percentage_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Percentage {
      get { return percentage_; }
      set {
        percentage_ = value;
      }
    }

    /// <summary>Field number for the "accountId" field.</summary>
    public const int AccountIdFieldNumber = 5;
    private string accountId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccountId {
      get { return accountId_; }
      set {
        accountId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "nickName" field.</summary>
    public const int NickNameFieldNumber = 6;
    private global::DC.Packet.SACCOUNT_NICKNAME nickName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DC.Packet.SACCOUNT_NICKNAME NickName {
      get { return nickName_; }
      set {
        nickName_ = value;
      }
    }

    /// <summary>Field number for the "characterClass" field.</summary>
    public const int CharacterClassFieldNumber = 7;
    private string characterClass_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CharacterClass {
      get { return characterClass_; }
      set {
        characterClass_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SRankRecord);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SRankRecord other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (PageIndex != other.PageIndex) return false;
      if (Rank != other.Rank) return false;
      if (Score != other.Score) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Percentage, other.Percentage)) return false;
      if (AccountId != other.AccountId) return false;
      if (!object.Equals(NickName, other.NickName)) return false;
      if (CharacterClass != other.CharacterClass) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (PageIndex != 0) hash ^= PageIndex.GetHashCode();
      if (Rank != 0) hash ^= Rank.GetHashCode();
      if (Score != 0) hash ^= Score.GetHashCode();
      if (Percentage != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Percentage);
      if (AccountId.Length != 0) hash ^= AccountId.GetHashCode();
      if (nickName_ != null) hash ^= NickName.GetHashCode();
      if (CharacterClass.Length != 0) hash ^= CharacterClass.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (PageIndex != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PageIndex);
      }
      if (Rank != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Rank);
      }
      if (Score != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Score);
      }
      if (Percentage != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Percentage);
      }
      if (AccountId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(AccountId);
      }
      if (nickName_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(NickName);
      }
      if (CharacterClass.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(CharacterClass);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (PageIndex != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(PageIndex);
      }
      if (Rank != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Rank);
      }
      if (Score != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Score);
      }
      if (Percentage != 0F) {
        output.WriteRawTag(37);
        output.WriteFloat(Percentage);
      }
      if (AccountId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(AccountId);
      }
      if (nickName_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(NickName);
      }
      if (CharacterClass.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(CharacterClass);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (PageIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(PageIndex);
      }
      if (Rank != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Rank);
      }
      if (Score != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Score);
      }
      if (Percentage != 0F) {
        size += 1 + 4;
      }
      if (AccountId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountId);
      }
      if (nickName_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NickName);
      }
      if (CharacterClass.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharacterClass);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SRankRecord other) {
      if (other == null) {
        return;
      }
      if (other.PageIndex != 0) {
        PageIndex = other.PageIndex;
      }
      if (other.Rank != 0) {
        Rank = other.Rank;
      }
      if (other.Score != 0) {
        Score = other.Score;
      }
      if (other.Percentage != 0F) {
        Percentage = other.Percentage;
      }
      if (other.AccountId.Length != 0) {
        AccountId = other.AccountId;
      }
      if (other.nickName_ != null) {
        if (nickName_ == null) {
          NickName = new global::DC.Packet.SACCOUNT_NICKNAME();
        }
        NickName.MergeFrom(other.NickName);
      }
      if (other.CharacterClass.Length != 0) {
        CharacterClass = other.CharacterClass;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            PageIndex = input.ReadUInt32();
            break;
          }
          case 16: {
            Rank = input.ReadUInt32();
            break;
          }
          case 24: {
            Score = input.ReadUInt32();
            break;
          }
          case 37: {
            Percentage = input.ReadFloat();
            break;
          }
          case 42: {
            AccountId = input.ReadString();
            break;
          }
          case 50: {
            if (nickName_ == null) {
              NickName = new global::DC.Packet.SACCOUNT_NICKNAME();
            }
            input.ReadMessage(NickName);
            break;
          }
          case 58: {
            CharacterClass = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            PageIndex = input.ReadUInt32();
            break;
          }
          case 16: {
            Rank = input.ReadUInt32();
            break;
          }
          case 24: {
            Score = input.ReadUInt32();
            break;
          }
          case 37: {
            Percentage = input.ReadFloat();
            break;
          }
          case 42: {
            AccountId = input.ReadString();
            break;
          }
          case 50: {
            if (nickName_ == null) {
              NickName = new global::DC.Packet.SACCOUNT_NICKNAME();
            }
            input.ReadMessage(NickName);
            break;
          }
          case 58: {
            CharacterClass = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SC2S_RANKING_RANGE_REQ : pb::IMessage<SC2S_RANKING_RANGE_REQ>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SC2S_RANKING_RANGE_REQ> _parser = new pb::MessageParser<SC2S_RANKING_RANGE_REQ>(() => new SC2S_RANKING_RANGE_REQ());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SC2S_RANKING_RANGE_REQ> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.RankingReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_RANKING_RANGE_REQ() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_RANKING_RANGE_REQ(SC2S_RANKING_RANGE_REQ other) : this() {
      rankType_ = other.rankType_;
      startIndex_ = other.startIndex_;
      endIndex_ = other.endIndex_;
      characterClass_ = other.characterClass_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_RANKING_RANGE_REQ Clone() {
      return new SC2S_RANKING_RANGE_REQ(this);
    }

    /// <summary>Field number for the "rankType" field.</summary>
    public const int RankTypeFieldNumber = 1;
    private uint rankType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RankType {
      get { return rankType_; }
      set {
        rankType_ = value;
      }
    }

    /// <summary>Field number for the "startIndex" field.</summary>
    public const int StartIndexFieldNumber = 2;
    private uint startIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint StartIndex {
      get { return startIndex_; }
      set {
        startIndex_ = value;
      }
    }

    /// <summary>Field number for the "endIndex" field.</summary>
    public const int EndIndexFieldNumber = 3;
    private uint endIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EndIndex {
      get { return endIndex_; }
      set {
        endIndex_ = value;
      }
    }

    /// <summary>Field number for the "characterClass" field.</summary>
    public const int CharacterClassFieldNumber = 4;
    private string characterClass_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CharacterClass {
      get { return characterClass_; }
      set {
        characterClass_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SC2S_RANKING_RANGE_REQ);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SC2S_RANKING_RANGE_REQ other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RankType != other.RankType) return false;
      if (StartIndex != other.StartIndex) return false;
      if (EndIndex != other.EndIndex) return false;
      if (CharacterClass != other.CharacterClass) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RankType != 0) hash ^= RankType.GetHashCode();
      if (StartIndex != 0) hash ^= StartIndex.GetHashCode();
      if (EndIndex != 0) hash ^= EndIndex.GetHashCode();
      if (CharacterClass.Length != 0) hash ^= CharacterClass.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RankType != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(RankType);
      }
      if (StartIndex != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(StartIndex);
      }
      if (EndIndex != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(EndIndex);
      }
      if (CharacterClass.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CharacterClass);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RankType != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(RankType);
      }
      if (StartIndex != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(StartIndex);
      }
      if (EndIndex != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(EndIndex);
      }
      if (CharacterClass.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CharacterClass);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RankType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RankType);
      }
      if (StartIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(StartIndex);
      }
      if (EndIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EndIndex);
      }
      if (CharacterClass.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharacterClass);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SC2S_RANKING_RANGE_REQ other) {
      if (other == null) {
        return;
      }
      if (other.RankType != 0) {
        RankType = other.RankType;
      }
      if (other.StartIndex != 0) {
        StartIndex = other.StartIndex;
      }
      if (other.EndIndex != 0) {
        EndIndex = other.EndIndex;
      }
      if (other.CharacterClass.Length != 0) {
        CharacterClass = other.CharacterClass;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RankType = input.ReadUInt32();
            break;
          }
          case 16: {
            StartIndex = input.ReadUInt32();
            break;
          }
          case 24: {
            EndIndex = input.ReadUInt32();
            break;
          }
          case 34: {
            CharacterClass = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RankType = input.ReadUInt32();
            break;
          }
          case 16: {
            StartIndex = input.ReadUInt32();
            break;
          }
          case 24: {
            EndIndex = input.ReadUInt32();
            break;
          }
          case 34: {
            CharacterClass = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SS2C_RANKING_RANGE_RES : pb::IMessage<SS2C_RANKING_RANGE_RES>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SS2C_RANKING_RANGE_RES> _parser = new pb::MessageParser<SS2C_RANKING_RANGE_RES>(() => new SS2C_RANKING_RANGE_RES());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SS2C_RANKING_RANGE_RES> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.RankingReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_RANKING_RANGE_RES() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_RANKING_RANGE_RES(SS2C_RANKING_RANGE_RES other) : this() {
      result_ = other.result_;
      records_ = other.records_.Clone();
      rankType_ = other.rankType_;
      allRowCount_ = other.allRowCount_;
      startIndex_ = other.startIndex_;
      endIndex_ = other.endIndex_;
      characterClass_ = other.characterClass_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_RANKING_RANGE_RES Clone() {
      return new SS2C_RANKING_RANGE_RES(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private uint result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "records" field.</summary>
    public const int RecordsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::DC.Packet.SRankRecord> _repeated_records_codec
        = pb::FieldCodec.ForMessage(18, global::DC.Packet.SRankRecord.Parser);
    private readonly pbc::RepeatedField<global::DC.Packet.SRankRecord> records_ = new pbc::RepeatedField<global::DC.Packet.SRankRecord>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::DC.Packet.SRankRecord> Records {
      get { return records_; }
    }

    /// <summary>Field number for the "rankType" field.</summary>
    public const int RankTypeFieldNumber = 3;
    private uint rankType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RankType {
      get { return rankType_; }
      set {
        rankType_ = value;
      }
    }

    /// <summary>Field number for the "allRowCount" field.</summary>
    public const int AllRowCountFieldNumber = 4;
    private uint allRowCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AllRowCount {
      get { return allRowCount_; }
      set {
        allRowCount_ = value;
      }
    }

    /// <summary>Field number for the "startIndex" field.</summary>
    public const int StartIndexFieldNumber = 5;
    private uint startIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint StartIndex {
      get { return startIndex_; }
      set {
        startIndex_ = value;
      }
    }

    /// <summary>Field number for the "endIndex" field.</summary>
    public const int EndIndexFieldNumber = 6;
    private uint endIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint EndIndex {
      get { return endIndex_; }
      set {
        endIndex_ = value;
      }
    }

    /// <summary>Field number for the "characterClass" field.</summary>
    public const int CharacterClassFieldNumber = 7;
    private string characterClass_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CharacterClass {
      get { return characterClass_; }
      set {
        characterClass_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SS2C_RANKING_RANGE_RES);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SS2C_RANKING_RANGE_RES other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if(!records_.Equals(other.records_)) return false;
      if (RankType != other.RankType) return false;
      if (AllRowCount != other.AllRowCount) return false;
      if (StartIndex != other.StartIndex) return false;
      if (EndIndex != other.EndIndex) return false;
      if (CharacterClass != other.CharacterClass) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      hash ^= records_.GetHashCode();
      if (RankType != 0) hash ^= RankType.GetHashCode();
      if (AllRowCount != 0) hash ^= AllRowCount.GetHashCode();
      if (StartIndex != 0) hash ^= StartIndex.GetHashCode();
      if (EndIndex != 0) hash ^= EndIndex.GetHashCode();
      if (CharacterClass.Length != 0) hash ^= CharacterClass.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Result);
      }
      records_.WriteTo(output, _repeated_records_codec);
      if (RankType != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(RankType);
      }
      if (AllRowCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(AllRowCount);
      }
      if (StartIndex != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(StartIndex);
      }
      if (EndIndex != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(EndIndex);
      }
      if (CharacterClass.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(CharacterClass);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Result);
      }
      records_.WriteTo(ref output, _repeated_records_codec);
      if (RankType != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(RankType);
      }
      if (AllRowCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(AllRowCount);
      }
      if (StartIndex != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(StartIndex);
      }
      if (EndIndex != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(EndIndex);
      }
      if (CharacterClass.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(CharacterClass);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Result);
      }
      size += records_.CalculateSize(_repeated_records_codec);
      if (RankType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RankType);
      }
      if (AllRowCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AllRowCount);
      }
      if (StartIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(StartIndex);
      }
      if (EndIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(EndIndex);
      }
      if (CharacterClass.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharacterClass);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SS2C_RANKING_RANGE_RES other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      records_.Add(other.records_);
      if (other.RankType != 0) {
        RankType = other.RankType;
      }
      if (other.AllRowCount != 0) {
        AllRowCount = other.AllRowCount;
      }
      if (other.StartIndex != 0) {
        StartIndex = other.StartIndex;
      }
      if (other.EndIndex != 0) {
        EndIndex = other.EndIndex;
      }
      if (other.CharacterClass.Length != 0) {
        CharacterClass = other.CharacterClass;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadUInt32();
            break;
          }
          case 18: {
            records_.AddEntriesFrom(input, _repeated_records_codec);
            break;
          }
          case 24: {
            RankType = input.ReadUInt32();
            break;
          }
          case 32: {
            AllRowCount = input.ReadUInt32();
            break;
          }
          case 40: {
            StartIndex = input.ReadUInt32();
            break;
          }
          case 48: {
            EndIndex = input.ReadUInt32();
            break;
          }
          case 58: {
            CharacterClass = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = input.ReadUInt32();
            break;
          }
          case 18: {
            records_.AddEntriesFrom(ref input, _repeated_records_codec);
            break;
          }
          case 24: {
            RankType = input.ReadUInt32();
            break;
          }
          case 32: {
            AllRowCount = input.ReadUInt32();
            break;
          }
          case 40: {
            StartIndex = input.ReadUInt32();
            break;
          }
          case 48: {
            EndIndex = input.ReadUInt32();
            break;
          }
          case 58: {
            CharacterClass = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SC2S_RANKING_NEARBY_REQ : pb::IMessage<SC2S_RANKING_NEARBY_REQ>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SC2S_RANKING_NEARBY_REQ> _parser = new pb::MessageParser<SC2S_RANKING_NEARBY_REQ>(() => new SC2S_RANKING_NEARBY_REQ());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SC2S_RANKING_NEARBY_REQ> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.RankingReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_RANKING_NEARBY_REQ() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_RANKING_NEARBY_REQ(SC2S_RANKING_NEARBY_REQ other) : this() {
      rankType_ = other.rankType_;
      searchRange_ = other.searchRange_;
      searchIndex_ = other.searchIndex_;
      characterClass_ = other.characterClass_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_RANKING_NEARBY_REQ Clone() {
      return new SC2S_RANKING_NEARBY_REQ(this);
    }

    /// <summary>Field number for the "rankType" field.</summary>
    public const int RankTypeFieldNumber = 1;
    private uint rankType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RankType {
      get { return rankType_; }
      set {
        rankType_ = value;
      }
    }

    /// <summary>Field number for the "searchRange" field.</summary>
    public const int SearchRangeFieldNumber = 2;
    private uint searchRange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SearchRange {
      get { return searchRange_; }
      set {
        searchRange_ = value;
      }
    }

    /// <summary>Field number for the "searchIndex" field.</summary>
    public const int SearchIndexFieldNumber = 3;
    private uint searchIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SearchIndex {
      get { return searchIndex_; }
      set {
        searchIndex_ = value;
      }
    }

    /// <summary>Field number for the "characterClass" field.</summary>
    public const int CharacterClassFieldNumber = 4;
    private string characterClass_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CharacterClass {
      get { return characterClass_; }
      set {
        characterClass_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SC2S_RANKING_NEARBY_REQ);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SC2S_RANKING_NEARBY_REQ other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RankType != other.RankType) return false;
      if (SearchRange != other.SearchRange) return false;
      if (SearchIndex != other.SearchIndex) return false;
      if (CharacterClass != other.CharacterClass) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RankType != 0) hash ^= RankType.GetHashCode();
      if (SearchRange != 0) hash ^= SearchRange.GetHashCode();
      if (SearchIndex != 0) hash ^= SearchIndex.GetHashCode();
      if (CharacterClass.Length != 0) hash ^= CharacterClass.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RankType != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(RankType);
      }
      if (SearchRange != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(SearchRange);
      }
      if (SearchIndex != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(SearchIndex);
      }
      if (CharacterClass.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CharacterClass);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RankType != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(RankType);
      }
      if (SearchRange != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(SearchRange);
      }
      if (SearchIndex != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(SearchIndex);
      }
      if (CharacterClass.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(CharacterClass);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RankType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RankType);
      }
      if (SearchRange != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SearchRange);
      }
      if (SearchIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SearchIndex);
      }
      if (CharacterClass.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharacterClass);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SC2S_RANKING_NEARBY_REQ other) {
      if (other == null) {
        return;
      }
      if (other.RankType != 0) {
        RankType = other.RankType;
      }
      if (other.SearchRange != 0) {
        SearchRange = other.SearchRange;
      }
      if (other.SearchIndex != 0) {
        SearchIndex = other.SearchIndex;
      }
      if (other.CharacterClass.Length != 0) {
        CharacterClass = other.CharacterClass;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RankType = input.ReadUInt32();
            break;
          }
          case 16: {
            SearchRange = input.ReadUInt32();
            break;
          }
          case 24: {
            SearchIndex = input.ReadUInt32();
            break;
          }
          case 34: {
            CharacterClass = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RankType = input.ReadUInt32();
            break;
          }
          case 16: {
            SearchRange = input.ReadUInt32();
            break;
          }
          case 24: {
            SearchIndex = input.ReadUInt32();
            break;
          }
          case 34: {
            CharacterClass = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SS2C_RANKING_NEARBY_RES : pb::IMessage<SS2C_RANKING_NEARBY_RES>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SS2C_RANKING_NEARBY_RES> _parser = new pb::MessageParser<SS2C_RANKING_NEARBY_RES>(() => new SS2C_RANKING_NEARBY_RES());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SS2C_RANKING_NEARBY_RES> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.RankingReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_RANKING_NEARBY_RES() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_RANKING_NEARBY_RES(SS2C_RANKING_NEARBY_RES other) : this() {
      result_ = other.result_;
      records_ = other.records_.Clone();
      rankType_ = other.rankType_;
      allRowCount_ = other.allRowCount_;
      searchRange_ = other.searchRange_;
      characterClass_ = other.characterClass_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_RANKING_NEARBY_RES Clone() {
      return new SS2C_RANKING_NEARBY_RES(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private uint result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "records" field.</summary>
    public const int RecordsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::DC.Packet.SRankRecord> _repeated_records_codec
        = pb::FieldCodec.ForMessage(18, global::DC.Packet.SRankRecord.Parser);
    private readonly pbc::RepeatedField<global::DC.Packet.SRankRecord> records_ = new pbc::RepeatedField<global::DC.Packet.SRankRecord>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::DC.Packet.SRankRecord> Records {
      get { return records_; }
    }

    /// <summary>Field number for the "rankType" field.</summary>
    public const int RankTypeFieldNumber = 3;
    private uint rankType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RankType {
      get { return rankType_; }
      set {
        rankType_ = value;
      }
    }

    /// <summary>Field number for the "allRowCount" field.</summary>
    public const int AllRowCountFieldNumber = 4;
    private uint allRowCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AllRowCount {
      get { return allRowCount_; }
      set {
        allRowCount_ = value;
      }
    }

    /// <summary>Field number for the "searchRange" field.</summary>
    public const int SearchRangeFieldNumber = 5;
    private uint searchRange_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint SearchRange {
      get { return searchRange_; }
      set {
        searchRange_ = value;
      }
    }

    /// <summary>Field number for the "characterClass" field.</summary>
    public const int CharacterClassFieldNumber = 6;
    private string characterClass_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CharacterClass {
      get { return characterClass_; }
      set {
        characterClass_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SS2C_RANKING_NEARBY_RES);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SS2C_RANKING_NEARBY_RES other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if(!records_.Equals(other.records_)) return false;
      if (RankType != other.RankType) return false;
      if (AllRowCount != other.AllRowCount) return false;
      if (SearchRange != other.SearchRange) return false;
      if (CharacterClass != other.CharacterClass) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      hash ^= records_.GetHashCode();
      if (RankType != 0) hash ^= RankType.GetHashCode();
      if (AllRowCount != 0) hash ^= AllRowCount.GetHashCode();
      if (SearchRange != 0) hash ^= SearchRange.GetHashCode();
      if (CharacterClass.Length != 0) hash ^= CharacterClass.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Result);
      }
      records_.WriteTo(output, _repeated_records_codec);
      if (RankType != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(RankType);
      }
      if (AllRowCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(AllRowCount);
      }
      if (SearchRange != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(SearchRange);
      }
      if (CharacterClass.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(CharacterClass);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Result);
      }
      records_.WriteTo(ref output, _repeated_records_codec);
      if (RankType != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(RankType);
      }
      if (AllRowCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(AllRowCount);
      }
      if (SearchRange != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(SearchRange);
      }
      if (CharacterClass.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(CharacterClass);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Result);
      }
      size += records_.CalculateSize(_repeated_records_codec);
      if (RankType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RankType);
      }
      if (AllRowCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AllRowCount);
      }
      if (SearchRange != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(SearchRange);
      }
      if (CharacterClass.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharacterClass);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SS2C_RANKING_NEARBY_RES other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      records_.Add(other.records_);
      if (other.RankType != 0) {
        RankType = other.RankType;
      }
      if (other.AllRowCount != 0) {
        AllRowCount = other.AllRowCount;
      }
      if (other.SearchRange != 0) {
        SearchRange = other.SearchRange;
      }
      if (other.CharacterClass.Length != 0) {
        CharacterClass = other.CharacterClass;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadUInt32();
            break;
          }
          case 18: {
            records_.AddEntriesFrom(input, _repeated_records_codec);
            break;
          }
          case 24: {
            RankType = input.ReadUInt32();
            break;
          }
          case 32: {
            AllRowCount = input.ReadUInt32();
            break;
          }
          case 40: {
            SearchRange = input.ReadUInt32();
            break;
          }
          case 50: {
            CharacterClass = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = input.ReadUInt32();
            break;
          }
          case 18: {
            records_.AddEntriesFrom(ref input, _repeated_records_codec);
            break;
          }
          case 24: {
            RankType = input.ReadUInt32();
            break;
          }
          case 32: {
            AllRowCount = input.ReadUInt32();
            break;
          }
          case 40: {
            SearchRange = input.ReadUInt32();
            break;
          }
          case 50: {
            CharacterClass = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SC2S_RANKING_CHARACTER_REQ : pb::IMessage<SC2S_RANKING_CHARACTER_REQ>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SC2S_RANKING_CHARACTER_REQ> _parser = new pb::MessageParser<SC2S_RANKING_CHARACTER_REQ>(() => new SC2S_RANKING_CHARACTER_REQ());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SC2S_RANKING_CHARACTER_REQ> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.RankingReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_RANKING_CHARACTER_REQ() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_RANKING_CHARACTER_REQ(SC2S_RANKING_CHARACTER_REQ other) : this() {
      rankType_ = other.rankType_;
      nickName_ = other.nickName_ != null ? other.nickName_.Clone() : null;
      characterClass_ = other.characterClass_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SC2S_RANKING_CHARACTER_REQ Clone() {
      return new SC2S_RANKING_CHARACTER_REQ(this);
    }

    /// <summary>Field number for the "rankType" field.</summary>
    public const int RankTypeFieldNumber = 1;
    private uint rankType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RankType {
      get { return rankType_; }
      set {
        rankType_ = value;
      }
    }

    /// <summary>Field number for the "nickName" field.</summary>
    public const int NickNameFieldNumber = 2;
    private global::DC.Packet.SACCOUNT_NICKNAME nickName_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DC.Packet.SACCOUNT_NICKNAME NickName {
      get { return nickName_; }
      set {
        nickName_ = value;
      }
    }

    /// <summary>Field number for the "characterClass" field.</summary>
    public const int CharacterClassFieldNumber = 3;
    private string characterClass_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CharacterClass {
      get { return characterClass_; }
      set {
        characterClass_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SC2S_RANKING_CHARACTER_REQ);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SC2S_RANKING_CHARACTER_REQ other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (RankType != other.RankType) return false;
      if (!object.Equals(NickName, other.NickName)) return false;
      if (CharacterClass != other.CharacterClass) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (RankType != 0) hash ^= RankType.GetHashCode();
      if (nickName_ != null) hash ^= NickName.GetHashCode();
      if (CharacterClass.Length != 0) hash ^= CharacterClass.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (RankType != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(RankType);
      }
      if (nickName_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(NickName);
      }
      if (CharacterClass.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CharacterClass);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (RankType != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(RankType);
      }
      if (nickName_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(NickName);
      }
      if (CharacterClass.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(CharacterClass);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (RankType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RankType);
      }
      if (nickName_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(NickName);
      }
      if (CharacterClass.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharacterClass);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SC2S_RANKING_CHARACTER_REQ other) {
      if (other == null) {
        return;
      }
      if (other.RankType != 0) {
        RankType = other.RankType;
      }
      if (other.nickName_ != null) {
        if (nickName_ == null) {
          NickName = new global::DC.Packet.SACCOUNT_NICKNAME();
        }
        NickName.MergeFrom(other.NickName);
      }
      if (other.CharacterClass.Length != 0) {
        CharacterClass = other.CharacterClass;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            RankType = input.ReadUInt32();
            break;
          }
          case 18: {
            if (nickName_ == null) {
              NickName = new global::DC.Packet.SACCOUNT_NICKNAME();
            }
            input.ReadMessage(NickName);
            break;
          }
          case 26: {
            CharacterClass = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            RankType = input.ReadUInt32();
            break;
          }
          case 18: {
            if (nickName_ == null) {
              NickName = new global::DC.Packet.SACCOUNT_NICKNAME();
            }
            input.ReadMessage(NickName);
            break;
          }
          case 26: {
            CharacterClass = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SS2C_RANKING_CHARACTER_RES : pb::IMessage<SS2C_RANKING_CHARACTER_RES>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SS2C_RANKING_CHARACTER_RES> _parser = new pb::MessageParser<SS2C_RANKING_CHARACTER_RES>(() => new SS2C_RANKING_CHARACTER_RES());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SS2C_RANKING_CHARACTER_RES> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::DC.Packet.RankingReflection.Descriptor.MessageTypes[6]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_RANKING_CHARACTER_RES() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_RANKING_CHARACTER_RES(SS2C_RANKING_CHARACTER_RES other) : this() {
      result_ = other.result_;
      rankRecord_ = other.rankRecord_ != null ? other.rankRecord_.Clone() : null;
      rankType_ = other.rankType_;
      allRowCount_ = other.allRowCount_;
      characterClass_ = other.characterClass_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SS2C_RANKING_CHARACTER_RES Clone() {
      return new SS2C_RANKING_CHARACTER_RES(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private uint result_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "rankRecord" field.</summary>
    public const int RankRecordFieldNumber = 2;
    private global::DC.Packet.SRankRecord rankRecord_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::DC.Packet.SRankRecord RankRecord {
      get { return rankRecord_; }
      set {
        rankRecord_ = value;
      }
    }

    /// <summary>Field number for the "rankType" field.</summary>
    public const int RankTypeFieldNumber = 3;
    private uint rankType_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint RankType {
      get { return rankType_; }
      set {
        rankType_ = value;
      }
    }

    /// <summary>Field number for the "allRowCount" field.</summary>
    public const int AllRowCountFieldNumber = 4;
    private uint allRowCount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint AllRowCount {
      get { return allRowCount_; }
      set {
        allRowCount_ = value;
      }
    }

    /// <summary>Field number for the "characterClass" field.</summary>
    public const int CharacterClassFieldNumber = 5;
    private string characterClass_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CharacterClass {
      get { return characterClass_; }
      set {
        characterClass_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SS2C_RANKING_CHARACTER_RES);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SS2C_RANKING_CHARACTER_RES other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (!object.Equals(RankRecord, other.RankRecord)) return false;
      if (RankType != other.RankType) return false;
      if (AllRowCount != other.AllRowCount) return false;
      if (CharacterClass != other.CharacterClass) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (rankRecord_ != null) hash ^= RankRecord.GetHashCode();
      if (RankType != 0) hash ^= RankType.GetHashCode();
      if (AllRowCount != 0) hash ^= AllRowCount.GetHashCode();
      if (CharacterClass.Length != 0) hash ^= CharacterClass.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Result);
      }
      if (rankRecord_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(RankRecord);
      }
      if (RankType != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(RankType);
      }
      if (AllRowCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(AllRowCount);
      }
      if (CharacterClass.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(CharacterClass);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Result);
      }
      if (rankRecord_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(RankRecord);
      }
      if (RankType != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(RankType);
      }
      if (AllRowCount != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(AllRowCount);
      }
      if (CharacterClass.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(CharacterClass);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Result);
      }
      if (rankRecord_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(RankRecord);
      }
      if (RankType != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(RankType);
      }
      if (AllRowCount != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(AllRowCount);
      }
      if (CharacterClass.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CharacterClass);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SS2C_RANKING_CHARACTER_RES other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.rankRecord_ != null) {
        if (rankRecord_ == null) {
          RankRecord = new global::DC.Packet.SRankRecord();
        }
        RankRecord.MergeFrom(other.RankRecord);
      }
      if (other.RankType != 0) {
        RankType = other.RankType;
      }
      if (other.AllRowCount != 0) {
        AllRowCount = other.AllRowCount;
      }
      if (other.CharacterClass.Length != 0) {
        CharacterClass = other.CharacterClass;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Result = input.ReadUInt32();
            break;
          }
          case 18: {
            if (rankRecord_ == null) {
              RankRecord = new global::DC.Packet.SRankRecord();
            }
            input.ReadMessage(RankRecord);
            break;
          }
          case 24: {
            RankType = input.ReadUInt32();
            break;
          }
          case 32: {
            AllRowCount = input.ReadUInt32();
            break;
          }
          case 42: {
            CharacterClass = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Result = input.ReadUInt32();
            break;
          }
          case 18: {
            if (rankRecord_ == null) {
              RankRecord = new global::DC.Packet.SRankRecord();
            }
            input.ReadMessage(RankRecord);
            break;
          }
          case 24: {
            RankType = input.ReadUInt32();
            break;
          }
          case 32: {
            AllRowCount = input.ReadUInt32();
            break;
          }
          case 42: {
            CharacterClass = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
